### ISSUE TITLE
Investigate supporting Koa and other frameworks

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#100]
Discussion in #92 and #97 talks about supporting Koa and other frameworks.

I'm hesitant to do this. Helmet is already a fair bit for me to maintain and I don't want it to get too complex. [koa-helmet](https://github.com/venables/koa-helmet) seems to solve this issue, but I'm not sure.

I'd like to bring the discussion here. What do people want? How should we approach this problem?

**Comment by MarkHerhold** [comment]
Simply from the standpoint of helmet staying relevant, I think that there should be a story for getting helmet to work with Koa. In my opinion, I see Koa gaining popularity as it embraces newer ES6/JS2015 features like generator functions and is simpler to use than Express (not trying to start a war here, this is just my opinion and why I think it is going to become more and more popular).

There are existing solutions to getting connect middleware to work with Koa such as [koa-connect](https://www.npmjs.com/package/koa-connect) but I admit I have never tried it (yet).

I could see helmet directly supporting both Koa and Express, but that will likely add dependencies Express or Koa don't need. And when ShinyNewFrameWork9000 comes out helmet will have to squeeze in support for yet another stack into the same repo. Not a good idea.

Maybe helmet could turn into two libraries like `koa-helmet` and `express-helmet` which handle wrapping the helmet sub-projects like `helmetjs/hide-powered-by` and `helmetjs/frameguard` for their respective stacks?

**Comment by burabure** [comment]
+1 @MarkHerhold . ideally helmet should abstract/decouple its core away from any framework implentation. Also koa is probably going to take over in a year or less because of standards and esnext

**Comment by EvanHahn** [comment]
I'd argue that helmet _does_ decouple its core away from a framework implementation.

Here's how to use one of Helmet's middlewares with Koa:

```js
var koa = require('koa');
var xssFilter = require('x-xss-protection');

function noop() {}

var app = koa();

app.use(function *(next) {
  xssFilter()(this.req, this.res, noop);
  yield next;
});

// ...
```

I think I'd prefer to submit some patches to [koa-helmet](https://github.com/venables/koa-helmet) to make it simpler (it doesn't have to be a fork, just a wrapper).

**Comment by MarkHerhold** [comment]
I like that idea @EvanHahn. I don't see any reason for koa-helmet to be a fork. I would like it even more if you owned it under the `helmetjs` github org. What are your thoughts here?

I'll make an issue on the koa-hemet repo and see if we can get the author involved in this discussion. See https://github.com/venables/koa-helmet/issues/13

**Comment by EvanHahn** [comment]
@MarkHerhold I'd certainly feel comfortable putting `koa-helmet` under the `helmetjs` org. I'd be a little more wary to merge its code into the "main" Helmet repo, but I'm on the fence.

**Comment by MarkHerhold** [comment]
@EvanHahn I'm not sure that it would be a merge rather than a rewrite, maybe keeping some tests. The way `koa-helmet` currently keeps the "subprojects" in sync is via the 'copy-paste & commit' method is not good from multiple (maintenance, security, sanity, etc) perspectives.

**Comment by EvanHahn** [comment]
Agreed. I could imagine `koa-helmet` having just one dependency: `helmet`.

**Comment by venables** [comment]
Happy to help however I can & happy to move the project under the `helmetjs` org.

I love the simplicity of a wrapper with a single `helmet` dependency.   I can see future wrappers for other frameworks following the same pattern.

**Comment by venables** [comment]
Made a quick, rough PR to koa-helmet which provides the wrapper behavior.  Comments welcome: https://github.com/venables/koa-helmet/pull/14

**Comment by EvanHahn** [comment]
I think the answer is to use `koa-helmet` and include it in the `helmetjs` GitHub org.

I've left comments at https://github.com/venables/koa-helmet/pull/14 and encourage others to do the same. Once that's merged, I'll talk to @venables about transferring ownership to the GitHub org and next steps.

**Comment by EvanHahn** [comment]
I think this issue has been closed—[koa-helmet](https://github.com/venables/koa-helmet) has been endorsed in the readme a couple of times.

Thanks everyone!
