### ISSUE TITLE
International Domain Name in connectSrc of csp not working in Firefox.

### ISSUE THREAD

**Issue by ZiCog** [helmetjs/helmet#106]
I have a simple web app that uses web sockets (socket.io) and operates from an international domain name "2π.net" or "xn--2-umb.net" in punny code. So I use this to configure CSP allowing access to the websocket:

    app.use(helmet.csp({
        defaultSrc:  ["'self'"],
        scriptSrc:   ["'self'"],
        styleSrc:    ["'self'","'unsafe-inline'"],
        imgSrc:      ["'self'"],
        connectSrc:  [
            "'self'",
            "wss://" + "xn--2-umb.net"
        ],
        fontSrc:     ["'self'"],
        objectSrc:   [],
        mediaSrc:    [],
        frameSrc:    []
    }));

This works fine in Chrome but Firefox complains about a CSP violation. It seems to be trying to match  "xn--2-umb.net" against "2π.net" and failing. Even if I enter the URL to FF as "xn--2-umb.net"

This is perhaps not a helmet issue but  I wondered if anyone here knows what to do about this.

For now I have changed that connecSrc to "wss://*.net;" to get it working.

**Comment by EvanHahn** [comment]
I'd be very surprised if this were a Helmet issue. Could you try setting the header like this and seeing if it still breaks?

```js
// This is instead of app.use(helmet.csp).
app.use(function (req, res, next) {
  res.setHeader("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self' wss://xn--2-umb.net font-src 'self'; object-src; media-src; frame-src");
  next();
});
```

If it still fails, then this isn't an issue with Helmet.

**Comment by ZiCog** [comment]
Yep, seems to be an issue with Firefox

This:

    // This is instead of app.use(helmet.csp).
    app.use(function (req, res, next) {
        res.setHeader("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self' wss://xn--2-umb.net font-src 'self'; ");
        next();
    });

Results in this:

    Content Security Policy: The page's settings blocked the loading of a resource at wss://2π.net/socket.io/?EIO=3&transport=websocket&sid=o8tbCzxDVk7p8ld9AAAB ("connect-src https://2π.net wss://xn--2-umb.net https://font-src https://2π.net").

**Comment by EvanHahn** [comment]
Okay. I'm gonna close this issue. We can use this spot for any further discussion.

**Comment by ZiCog** [comment]
OK, I progressed this issue to Bugzilla@Mozilla. Seems they accept that it is a Firefox bug.
