### ISSUE TITLE
Disable Helmet when working locally

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#107]
From [@kaushik94's comment in another thread](https://github.com/helmetjs/helmet/issues/105#issuecomment-157045844):

> How do we use helmet or disable it when working locally. For example I am implementing a share button and it makes a request to https://cdn.api.twitter.com/ but helmet blocks. I don't want to frequently change the helmet configuration since it might screw things up if I don't revert back. Is there a way to work with this on local ?

Let's discuss this here.

**Comment by EvanHahn** [comment]
@kaushik94 Do you want to disable Helmet in development mode?

**Comment by kaushik94** [comment]
@EvanHahn yes.

**Comment by EvanHahn** [comment]
Are you using Express?

**Comment by kaushik94** [comment]
yes

**Comment by EvanHahn** [comment]
@kaushik94 Did my solution help?

**Comment by kaushik94** [comment]
@EvanHahn I did something similar but I'm sorry I forgot to reply back. I had a config yaml file and I set a flag for dev and prod and it works now. Thanks a lot, helmet was amazing.

**Comment by EvanHahn** [comment]
Sounds good. I'll close this issue for now; feel free to open a new one if you have any problems.
