### ISSUE TITLE
Add a confige path for config.json to the options

### ISSUE THREAD

**Issue by kivi** [helmetjs/helmet#108]
It would be great to have the possibility to change the default config. I have seen workarounds to changing the config.json in node_modules/helmet. Custom config file could be also useful to #107

**Comment by evilpacket** [comment]
I thought we used to have an option to load values from a config file. I could be wrong though as a quick glance through the docs didn't show it. It's been a while since I've been in the code base.

**Comment by EvanHahn** [comment]
@kivi Do you want this so that you can only include certain middlewares? What's the use case for changing that file?

**Comment by kivi** [comment]
@EvanHahn, configuration for one of the environment is different, a use case is: I have to take out "ienoopen" from the config make it work for certain clients working inside the company. Whereas the public access is not affected.

**Comment by EvanHahn** [comment]
@kivi It sounds like you're looking for something that can be done at the Express level. Would something like this help you?

```js
if (shouldHaveIeNoOpen) {
  app.use(helmet.ienoopen());
}
app.use(helmet.frameguard());
// ...
```

**Comment by kivi** [comment]
@EvanHahn, sure, I would need 8 out of 9. So maybe an exclude list or just a list as a config param 

```JavaScript
if (!shouldHaveIeNoOpen) {
  app.use(helmet({
    exclude: [helmet.ienoopen]
  }));
} else {
  app.use();
}
```

**Comment by EvanHahn** [comment]
@kivi Would this work?

```js
app.use(
  helmet.hidePoweredBy(),
  helmet.hsts(),
  helmet.noSniff(),
  helmet.frameguard(),
  helmet.xssFilter()
);

if (shouldHaveIeNoOpen) {
  app.use(helmet.ienoopen());
}
```

**Comment by kivi** [comment]
@EvanHahn I was thinking of something like this, in case further middleware are included or removed in helmet versions.

```JavaScript
helmet.ienoopen = function() {
    return function (req, res, next) {
        next();
    }
}
app.use(helmet());
```
read/write access to `helmet.config`

```JavaScript
delete helmet.config.ienoopen
app.use(helmet());
```

**Comment by EvanHahn** [comment]
Helmet is soon to reach 1.0 and its defaults will stay that way for a long time.

I hesitate to add more than one way to do something—it will increase my support burden and the surface area for potential bugs.

**Comment by kivi** [comment]
Fair enough, :+1: 
As for the time being I have some options as mentioned above, thanks!

**Comment by EvanHahn** [comment]
Sounds good! Feel free to open a new issue if you have more problems/questions.
