### ISSUE TITLE
Cannot find module 'helmet-csp'

### ISSUE THREAD

**Issue by edlerner-TU** [helmetjs/helmet#109]
Following the direction of the README (`var csp = require('helmet-csp');`), I fail to require the CSP sub-package, even though the install of Helmet et al was successful and all other Helmet packages (e.g. frameguard) perform as expected

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'helmet-csp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by EvanHahn** [comment]
The readme was unclear. This is what you should be doing:

```js
var helmet = require('helmet');

// ...

app.use(helmet.csp({
  // ...
});
```

Does that work?

**Comment by edlerner-TU** [comment]
Yes it did, thank you for clarifying.

**Comment by EvanHahn** [comment]
Thanks for bringing this up—the readme was unclear.
