### ISSUE TITLE
Contributing guidelines for this project?

### ISSUE THREAD

**Issue by grtjn** [helmetjs/helmet#113]
Are there particular contributing guidelines for this project? I typically use either of these as example:

https://github.com/marklogic/slush-marklogic-node/blob/master/CONTRIBUTING.md

https://github.com/grtjn/ml-google-maps-ng/blob/master/CONTRIBUTING.md

(yes, they look very similar.. ;))

**Comment by EvanHahn** [comment]
I like these. Can I use one of those as a template?

**Comment by grtjn** [comment]
Of course, nothing special about them. Read through carefully though, particularly the links. You probably want to tweak here an there to your liking..

**Comment by EvanHahn** [comment]
This is now in `helmet@2.0.0`.
