### ISSUE TITLE
How to remove a preloaded hsts entry?

### ISSUE THREAD

**Issue by binarykitchen** [helmetjs/helmet#115]
I mistakenly used this for a local site to be developed

```
        app.use(helmet.hsts({
          maxAge:            108864000000, // Must be at least 18 weeks to be approved by Google
          preload:           true
        }))
```

But now, I can't visit the local site with plain HTTP anymore.

How can I undo this? Googled a lot, no luck. Any ideas?

Maybe setting `maxAge` to `-1` does the trick?

**Comment by EvanHahn** [comment]
I'm not sure about this one. Because `preload`ed stuff is preloaded into browsers, it might be tricky to undo.

In reading [the spec](http://tools.ietf.org/html/rfc6797#page-19), I see two things:

- The browser should update its HSTS cache if it sees a new header:

  > Update the UA's cached information for the Known HSTS Host if either or both of the max-age and includeSubDomains header field value tokens are conveying information different than that already maintained by the UA.

- A `max-age` of `0` should obliterate the entry in the browser's cache:

  > If the max-age header field value token has a value of zero, the UA MUST remove its cached HSTS Policy information (including the includeSubDomains directive, if asserted) if the HSTS Host is known, or the UA MUST NOT note this HSTS Host if it is not yet known.

Maybe try setting the `max-age` to `0`?

**Comment by EvanHahn** [comment]
I'm happy to keep helping you with this (I'd love to know the answer!) but I'm going to close this issue unless you think it's a problem with Helmet itself, in which case I'll reopen.

**Comment by binarykitchen** [comment]
@EvanHahn do you think you could test this if max-age=0 helps?

**Comment by EvanHahn** [comment]
Would you be able to try it? It sounds like conditions are right for you to test it out.

**Comment by binarykitchen** [comment]
okay, i tried and nope, it doesn't work. setting max-age to 0 or 1 won't remove it from cache.

makes sense because google chrome must be fetching that (cached?) hsts list from somewhere else. and it is added on their remote serves when parsed/detected for the first time, even if it's a locally developed site.

i think this should be documented or even better, come along with a warning when not in production.

**Comment by EvanHahn** [comment]
I thought they only added it to their cache if you submitted it to them (I recall there being a form). I'll look into this further.

**Comment by EvanHahn** [comment]
Any chance this helps? http://superuser.com/questions/480200/how-to-disable-ssl-for-some-websites-in-chrome/481277

**Comment by binarykitchen** [comment]
@EvanHahn nope, this doesn't help but thanks anyway. Will have to wait until the hsts entry has expired :(

**Comment by EvanHahn** [comment]
Let me know how it goes!

**Comment by binarykitchen** [comment]
not sure if i ll remember to report back here in two months

**Comment by EvanHahn** [comment]
No worries—I'll follow up.

**Comment by EvanHahn** [comment]
@binarykitchen Did this get resolved?

**Comment by binarykitchen** [comment]
the 3 months aren't over yet, so can't say. ping me again end of june.

**Comment by EvanHahn** [comment]
@binarykitchen Any updates?

**Comment by binarykitchen** [comment]
arrgh, still does not work on firefox and am seeing

```
local.videomail.io:8080 uses an invalid security certificate. The certificate is not trusted because it is self-signed. Error code: SEC_ERROR_UNKNOWN_ISSUER
```

**Comment by EvanHahn** [comment]
Could you set the max age to 0, visit the HTTPS URL, and then see if that fixes it?

**Comment by binarykitchen** [comment]
Tried that, no difference. The request parameters remain unchanged. And Firefox still complains:

```
local.videomail.io:8080 uses an invalid security certificate. The certificate is not trusted because it is self-signed. Error code: SEC_ERROR_UNKNOWN_ISSUER
```

whereas Chrome doesn't complain. Huh?

**Comment by EvanHahn** [comment]
Do you think this would work?

http://classically.me/blogs/how-clear-hsts-settings-major-browsers

**Comment by binarykitchen** [comment]
thanks but that link is pretty old and `about:permissions` seems not to work on latest firefox :/

**Comment by EvanHahn** [comment]
What about this? http://superuser.com/questions/539580/how-can-i-remove-a-website-accidentally-added-to-firefoxs-list-of-hsts-sites

Sorry I can't be more helpful here.

**Comment by binarykitchen** [comment]
Ahhh, finally I cracked that b**ch. That link helped. All I had to do was to edit SiteSecurityServiceState.txt .... phew

**Comment by EvanHahn** [comment]
Fantastic! Sorry this plagued you for so long.
