### ISSUE TITLE
helmet doesn't install correct hpkp

### ISSUE THREAD

**Issue by boysmovie** [helmetjs/helmet#116]
When npm i helmet, it installs probably an older version of hpkp.

So if you have a reportUri even when reportOnly is false you still get the header as "Public-Key-Pins-Report-Only"

```
  if (options.reportUri) {
    header += '-Report-Only';
  }
```

**Comment by EvanHahn** [comment]
The latest version of `hpkp` is [1.1.0](https://github.com/helmetjs/hpkp/commit/86ea3eded9df7092d0402fb4f4807caa85669b1b) and Helmet [specifies that version in its package.json](https://github.com/helmetjs/helmet/blob/aaf9130997ece10ec5cf03b4d6a60f730c016bc2/package.json#L35).

Can you try reinstalling Helmet?

**Comment by EvanHahn** [comment]
@boysmovie Any luck?

**Comment by EvanHahn** [comment]
I'm going to close this because it's been over a month since I've heard a response. Happy to reopen this issue if it's still a problem!
