### ISSUE TITLE
npm dependency installation

### ISSUE THREAD

**Issue by vhpezzolla** [helmetjs/helmet#118]
Hello, I'm fairly new to node development. I ran the 'npm install helmet --save' command and it added several hundred new node_modules along with modifying some existing node_modules within the project.  I thought a plug-in's (like helmet) dependencies were contained within its local internal node_module directory?  Having all helmet's dependencies at the same level as helmet caused the project's dependencies to get modified.  For example, the application depends on a particular version of connect-mongo and it was modified with the install.  Just a little confused.  Thank you

**Comment by evilpacket** [comment]
npm 3 flattens out the dep tree as much as possible. We (as helmet) don't have control of where npm decides to put your dependencies.

**Comment by evilpacket** [comment]
This is probably useful to you. https://docs.npmjs.com/how-npm-works/npm3

**Comment by vhpezzolla** [comment]
Indeed.  It answers the questions.  Thank you

_________________________________________________________________

Vic Pezzolla
Software Developer, OI&T Product Development
801.738.7135 (Office)
