### ISSUE TITLE
Replacing the default 404 and 500

### ISSUE THREAD

**Issue by naugtur** [helmetjs/helmet#120]
It's a good practice to replace default responses from express to hide what it is, otherwise disabling x-powered-by doesn't prevent an attacker from guessing you're using express.

The important thing is that it wouldn't be just 
```
app.use(helmet())
```
but it'd have to be a separate tool that's used as the last two middlewares in your stack. 

I'd like to contribute that to helmet, but I'd need to know if it's a welcome contribution :)

**Comment by EvanHahn** [comment]
Disabling X-Powered-By has [limited security benefit](https://github.com/expressjs/express/pull/2813#issuecomment-159270428), so I'd be hesitant to add new code to replace default error pages.

I don't want to discard this idea, though. What would you replace them with?

**Comment by naugtur** [comment]
It's a common practice and a requirement in some companies that have a person responsible for security audits :)

What I want to do addresses point 2 from the post you linked to. Along with disabling x-powered-by it prevents less-prepared hackers from guessing your server. 

I wanted to write a separate lib for hardening express that would wrap around helmet, but that's much worse than contributing what's not here.

Here's a snippet of what I'd like to add to helmet (the functionality, I need to work out the API/usage)

These two need to be added as the last two middlewares in an app.
```js
    custom404: function custom404(req, res, next) { //NEXT MUST BE HERE, express decides to run this handler based on arity
        res.status(404);
        res.end("I'm terribly sorry, but I can't find what you're looking for.");
    },
    custom500: function custom500(err, req, res, next) { //NEXT MUST BE HERE, express decides to run this handler based on arity
        res.status(500);
        res.end("Internal error");
    }
```

**Comment by EvanHahn** [comment]
I think this is a good idea and something we should recommend in the readme, but it feels a bit outside of Helmet's scope.

Perhaps we could link to a blog post or other module?

**Comment by naugtur** [comment]
Ok, I'll put it up somewhere and let you know.
