### ISSUE TITLE
Add support for SameSite cookie

### ISSUE THREAD

**Issue by ajinabraham** [helmetjs/helmet#121]
The new security cookie attribute is available in browsers.
Here is the RFC: https://tools.ietf.org/html/draft-west-first-party-cookies-06

**Comment by EvanHahn** [comment]
A quick look at this (sorry, I'm on my phone) makes this look like it'd be better suited to a cookie-setting library. I'm sure I'm missing a lot, though--does that seem right to you?

**Comment by ajinabraham** [comment]
Ok I noticed that you are not supporting `httpOnly` and `Secure` attributes for cookie either. 
So helmet is more like it provides security headers globally to all the routes of the application. The case of cookie is different as attributes needs to be set based on the priority of the cookie or the functionality of the app. 

Closing this.

**Comment by EvanHahn** [comment]
Yes, exactly.

If there's something we should recommend in the readme, let me know!
