### ISSUE TITLE
TypeError: helmet.xframe is not a function

### ISSUE THREAD

**Issue by binarykitchen** [helmetjs/helmet#122]
Just bumped to v2 and in Changelog xframe is nowhere mentioned.

```
    helmet.xframe('allow-from', 'http://www.responsinator.com')
           ^

TypeError: helmet.xframe is not a function
    at Object.module.exports.secure (/home/michael-heuberger/binarykitchen/code/videomail.io/src/middleware/headers.js:35:12)
```

what's missing?

**Comment by EvanHahn** [comment]
This is mentioned in [the 2.0.0 changelog](https://github.com/helmetjs/helmet/blob/master/HISTORY.md#200--2016-04-29) but should probably have been better clarified.

Try using `helmet.frameguard` instead.

**Comment by EvanHahn** [comment]
@binarykitchen Did that fix work for you?

**Comment by binarykitchen** [comment]
yes

**Comment by EvanHahn** [comment]
👍. Let me know if you run into other issues!

**Comment by aralroca** [comment]
I have this code:

    const SixMonths = 15778476000;

    app.use(helmet.xframe());
    app.use(helmet.xssFilter());
    app.use(helmet.nosniff());
    app.use(helmet.ienoopen());
    app.use(helmet.hsts({
      "maxAge": SixMonths,
      "includeSubdomains": true,
      "force": true
    }));
    app.disable("x-powered-by");

After `TypeError: helmet.xframe is not a function` issue, I changed this line:

     app.use(helmet.xframe());

to this:

     app.use(helmet.frameguard());

Is this okey? Because now I have this another issue:

`TypeError: helmet.nosniff is not a function` 😅

Thank you 😊

**Comment by EvanHahn** [comment]
@aralroca Try this:

```js
app.use(helmet.noSniff())
```

**Comment by aralroca** [comment]
Same error:

`    TypeError: helmet.nosniff is not a function`

**Comment by EvanHahn** [comment]
It looks like the S needs to be capitalized. It should be `noSniff`, not `nosniff`.

**Comment by ericofranco** [comment]
`app.use(helmet.noSniff())  `  worked here, thank you!

**Comment by ShahNewazKhan** [comment]
Another one I came across that I had to change from `app.use(helmet.ienoopen())` to `app.use(helmet.ieNoOpen());`
