### ISSUE TITLE
Helmet and nginx

### ISSUE THREAD

**Issue by titoesteves** [helmetjs/helmet#123]
Are there any known issues with using helmet and nginx? As it stands now, my site will not load if I have helmet and nginx enabled. If I disable either helmet or nginx, the site loads fine. However, when I have both enabled, my site does not load. Is there anything special that needs to be configured in nginx in order for helmet to work with it?

**Comment by EvanHahn** [comment]
I don't know anything about this but am curious as to the solution.

**Comment by EvanHahn** [comment]
My guess is that this problem would happen with other HTTP headers, too. Could you try setting a random header in your Express app and seeing if this still persists?

Something like this might work to set a random header:

```javascript
app.use(function (req, res, next) {
  res.setHeader('X-Titoesteves-Example', 'foo')
  next()
})
```

**Comment by titoesteves** [comment]
It seems to be working. Unfortunately I am not sure why. Feel free to close. Thanks for the reply

**Comment by EvanHahn** [comment]
Will do! Let me know if there are other issues you run into.
