### ISSUE TITLE
Helmet and nginx best practices

### ISSUE THREAD

**Issue by titoesteves** [helmetjs/helmet#126]
Currently I have an express app behind an nginx load balancer. 

I am curious to know what is the best practice when it comes to setting security policies such as CSP and http security headers such as HSTS? Should they be configured within my express.js application with helmetjs? Or is it best practice to configure them in nginx? 

Does the helmetjs team recommend setting security in nginx or express application?

**Comment by EvanHahn** [comment]
This is a good question and I don't know the answer.

My gut says to use nginx to set headers that never change because it's probably faster. Some headers, like CSP, have some logic required on the incoming request, so they shouldn't be set by nginx.

I don't know much about this, though—what do others think?

**Comment by AubreyHewes** [comment]
Good question. 

I use dokku(herokuish) to deploy a number of apps (dokku uses nginx as the balancer/app-proxy). I add security headers to the app-proxy (generic hsts policy + generic sec headers etc). This removes having to set these on the(every) application deployed.. keeping it dry. This entails a generic approach to sec (i.e. hsts does not include sub domains as an app could be on a subdomain). Though I can still override these on the app/deploy level (via custom nginx conf).

I think it eventually comes down to the individual use case.. and is therefore hard to say what the best solution should be... Though a proxy that is singular to an application should probably be the place to do it all.

**Comment by titoesteves** [comment]
@AubreyHewes @EvanHahn thanks for your insights. I now have a better understanding of where I should implement my headers/policies. Feel free to close.

**Comment by EvanHahn** [comment]
Will do. Feel free to open a new issue if something new comes up!
