### ISSUE TITLE
X-XSS Protection issue

### ISSUE THREAD

**Issue by prcongithub** [helmetjs/helmet#132]
```
Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
```
Getting this error in the google chrome console log after adding latest helmet-2.1.2 to an express-4.14.0

**Comment by prcongithub** [comment]
Closing this. Not a helmet issue. It Seems, if we have the same header added on nginx, it messes up with the one set by helmet.

**Comment by EvanHahn** [comment]
Let me know if you run into anything else!
