### ISSUE TITLE
dynamic import breaking webpack

### ISSUE THREAD

**Issue by omerts** [helmetjs/helmet#133]
Hello,

We are trying to make a webpack server bundle, which includes the needed packages inside the output file. The problem is that this package has dynamic requires, which cause webpack to throw a webpackMissingModule error. 

Code the causes the error:
```javascript
Object.keys(config.middlewares).forEach(function (moduleName) {
  var pkg = require(moduleName)
  var alias = config.middlewares[moduleName]
  helmet[alias] = pkg
})
```

Webpack bundled this into:
```javascript
Object.keys(config.middlewares).forEach(function (moduleName) {
  var pkg = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())
  var alias = config.middlewares[moduleName]
  helmet[alias] = pkg
})
```

**Comment by EvanHahn** [comment]
`helmet@2.1.3` has been published to fix this issue! Let me know if you run into any problems.
