### ISSUE TITLE
It does not work with Express 4.14.0 ?

### ISSUE THREAD

**Issue by eluizbr** [helmetjs/helmet#134]
I use the following:

let express = require('express'),
    app = express(),

// Run Helmet
app.use(helmet());
app.use(helmet.hidePoweredBy());

In headers i'm still seeing:

X-Powered-By →Express

Where is my error?
That is an bug ?

Thanks!

**Comment by EvanHahn** [comment]
Hmm, I'm not seeing the same issue on Express 4.14.0 and Helmet 2.1.3.

Here's a full app file:

```js
let express = require('express')
let helmet = require('helmet')

let app = express()

// Run Helmet
app.use(helmet())
app.use(helmet.hidePoweredBy())

app.listen(3000)
```

I didn't see the `X-Powered-By` header.

By the way, `helmet()` includes `helmet.hidePoweredBy()` so you don't need to use it separately.

Could you try using that app above and seeing if you spot the same bug?

**Comment by eluizbr** [comment]
I tried this way too, but I did not have success.

thats is my complete app.js:

https://gist.github.com/eluizbr/1f3f8736a5619cda75cade2f01162397

Thanks...

**Comment by EvanHahn** [comment]
Are the other Helmet headers (like `X-XSS-Protection`) set?

**Comment by eluizbr** [comment]
All headers...

Connection →keep-alive
Content-Length →264
Content-Type →application/json; charset=utf-8
Date →Wed, 14 Sep 2016 14:25:55 GMT
ETag →W/"108-p3Qqn2bAKWUiomJzRGr/3Q"
X-Content-Type-Options →nosniff
X-DNS-Prefetch-Control →off
X-Download-Options →noopen
X-Frame-Options →SAMEORIGIN
X-Powered-By →Express
X-XSS-Protection →1; mode=block

**Comment by EvanHahn** [comment]
The fact that those other headers exist is good news—it means that Helmet isn't completely broken.

Are your route handlers (like `usersRouteGet`) full Express apps (made with `express()`) or routers (made with `express.Router()`)?

**Comment by EvanHahn** [comment]
@eluizbr Bumping this—are you still having problems?

**Comment by fiznool** [comment]
I'm experiencing the same issue. My route handlers are pretty much exclusively created with `express.Router()` - does this mean I need to configure helmet in some other manner?

**Comment by EvanHahn** [comment]
@fiznool Are you doing `app.use(helmet())` before the static file middleware?

**Comment by fiznool** [comment]
No, afterwards... That's the issue?

**Comment by eluizbr** [comment]
@EvanHahn Is, i still have this issue. Sorry about delay.

**Comment by EvanHahn** [comment]
You should be doing something like this with your static middleware:

```js
app.use(helmet());
app.use(express.static(path.join(config.root, 'public')));
```

Let me know if that reordering helps.

**Comment by fiznool** [comment]
@EvanHahn thanks that sorted it! :smile:

**Comment by EvanHahn** [comment]
@eluizbr Does reordering solve your issue?

**Comment by matt-dalton** [comment]
I am having the same problem here but reordering isn't helping. You mentioned above there was a difference between 'express()' routers and 'express.Router()'s - could you elaborate on this? I am using `const router = express.Router()` - is this not what I should be doing?

**Comment by EvanHahn** [comment]
@matt-dalton Could you describe your problem in more detail (ideally with code snippets)? Feel free to open a new issue if you think that'll help.

**Comment by matt-dalton** [comment]
Yeah sure...here's my `server.js`:

    if (process.env.NODE_ENV === undefined) { const config = require('./config') } //this is just env variables
    const express = require('express')
    const path = require('path')
    const bodyParser = require('body-parser')
    const helmet = require('helmet')
    const app = express()
    app.use(helmet())

    const routes = require('./routes.js')

    app.use(bodyParser.json())

    app.use(express.static(path.join(__dirname, 'client/build')))
    require('./config/session')(app) //this sets up a Redis store for sessions

    app.use('/', routes)
    //blah blah

    module.exports = app

Then my `routes.js`:

    const express = require('express')
    const router = express.Router()

    router.get........
   
    modules.exports = router

In writing this out, I thought it could be because I am using a separate instance of express for my routes. I tried passing express into my `routes.js` and I still have the `x-powered-by` header. 

I also have the other Helmet headers in my responses:

    X-Content-Type-Options:nosniff
    X-DNS-Prefetch-Control:off
    X-Download-Options:noopen
    X-Frame-Options:SAMEORIGIN
    X-Powered-By:Express
    X-XSS-Protection:1; mode=block

Thanks for the help

**Comment by EvanHahn** [comment]
@matt-dalton Is the only issue that you're seeing `X-Powered-By: Express`?

I put together a [small test app](https://github.com/EvanHahn/helmet-issue134) that's similar to what you posted and I couldn't reproduce the problem you're seeing.

**Comment by philiiiiiipp** [comment]
Hey, I am experiencing exactly the same issue but only if I am running it in my dev environment. In production I do not see the X-Powered-By header. Maybe this has something to do with it?
```
webpack-dev-server@2.1.0-beta.10
express@4.14.0
helmet@3.1.0 
```

**Comment by EvanHahn** [comment]
The `webpack-dev-server` might be the culprit there, though I'm not sure.

You should also be able to do this:

```js
app.disable('x-powered-by');
```

**Comment by philiiiiiipp** [comment]
Hmm no that also does not seem to change it.
```
app.disable('x-powered-by');
console.log(app.disabled('x-powered-by')); // true
```
But in my chrome networks tab I still see it.
```
x-content-type-options:nosniff
x-dns-prefetch-control:off
x-download-options:noopen
x-frame-options:SAMEORIGIN
X-Powered-By:Express
x-xss-protection:1; mode=block
```
I suppose this is actually not an issue with helmet but express or likely the dev-server, are you using this as well @matt-dalton @eluizbr ?

**Comment by matt-dalton** [comment]
I was just thinking it's possible that might be it. Over the next couple of days I will try pushing `app.disable('x-powered-by')` to a production-like environment and see if that fixes it.

Sorry, I did mean to reply to your demo sooner @EvanHahn , as I tried it and also couldn't see the problem. I tried cutting out each bit of my code piece-by-piece to see if I could remove what was 'adding' the header back, but couldn't. Will give this new theory a try first...

**Comment by EvanHahn** [comment]
If the header is being added even when you add `app.disable('x-powered-by')`, I think it's very unlikely that this is a problem with Helmet.

Happy to help debug, but do you all mind if I close this issue?

**Comment by matt-dalton** [comment]
Well that's what I mean - was going to check if it does disappear when I move to prod which would imply webpack-dev-server was the culprit. I don't know enough about how helmet works to agree/disagree with your statement, but happy for you to use your judgement. It definitely still appears in development when I add `app.disable('x-powered-by')`, so you're probably right.

**Comment by EvanHahn** [comment]
Okay. I'm going to close this issue but I'm happy to help debug further.

**Comment by with0out** [comment]
I had same problem with express 4.14.0, with both 
```
app.disable('x-powered-by');   
app.use(helmet()); 
```
set, response still shows x-powered-by.
Then I followed the [doc](https://helmetjs.github.io/docs/hide-powered-by/) and set this
```
app.use(helmet.hidePoweredBy({ setTo: 'foo' })); 
```
and the header changed accordingly, don't know why it behaves like this...

**Comment by EvanHahn** [comment]
@with0out Are you using a "vanilla" Express app?

**Comment by with0out** [comment]
@EvanHahn My little project started with [this](https://github.com/madhums/node-express-mongoose) boilerplate, not very "vanilla" per se.

**Comment by EvanHahn** [comment]
@with0out Would you be able to put together a simple app that can reproduce this problem?

**Comment by with0out** [comment]
@EvanHahn I just tested, 2 lines of change from their [repo ](https://github.com/madhums/node-express-mongoose) would reproduce this problem.
Inside config/express.js:
```
...
var helmet = require('helmet');   // ADDED
...
module.exports = function (app, passport) {
  app.use(helmet());   // ADDED (not working)
  // app.use(helmet.hidePoweredBy({ setTo: 'foo' }));   // ADDED (working)
...
```

**Comment by EvanHahn** [comment]
@with0out Would you be able to make a pull request on their repo to fix that?

You can also do `app.disable('x-powered-by)` to remove this header without Helmet.

**Comment by JTCE** [comment]
Just to expand on the discussion above.....I've also run into this issue on my local development machine. app.disable('x-powered-by') and app.use(helmet.hidePoweredBy()) does not remove this header. Changing it with helmet does not remove it but only changes the value. Very puzzling indeed!

**Comment by JTCE** [comment]
Just thought I'd come back and mention removing etag does work via app.disable('etag'); Not sure why it doesn't work with x-powered-by.

**Comment by EvanHahn** [comment]
If the `X-Powered-By` header is being added without using Helmet (with `app.disable('x-powered-by')`), I'm confident this isn't an issue with Helmet but a problem elsewhere. Is there anything "between" you and the Express server, like nginx or some proxy?

**Comment by JTCE** [comment]
@EvanHahn I'm in agreement this isn't an issue with Helmet. I'll be glad to provide an update if I find the root cause but with deadlines looming it may be a while. Thanks for the great package, works like a charm otherwise!

**Comment by EvanHahn** [comment]
@JTCE Let me know what you find!

**Comment by frankdavidcorona** [comment]
I use this configuration:
```
app.use(helmet());
app.use(xFrameOptions());
```
And have this out:
```
Accept-Ranges:bytes
Cache-Control:public, max-age=0
Connection:keep-alive
Content-Length:1508
Content-Type:text/html; charset=UTF-8
Date:Thu, 20 Jul 2017 14:57:26 GMT
ETag:W/"5e4-15d607d6f7e"
Last-Modified:Thu, 20 Jul 2017 14:53:39 GMT
X-Content-Type-Options:nosniff
X-DNS-Prefetch-Control:off
X-Download-Options:noopen
X-Frame-Options:Deny
X-XSS-Protection:1; mode=block
```

**Comment by EvanHahn** [comment]
@frankdavidcorona That looks right to me!

**Comment by JAYiSON021** [comment]
Make sure other instance of Express like your routes uses helmet.js

```
import Router from 'express';
import helmet from 'helmet';

export default ({ config, db, ....}) => {
      let api = Router();
      api.use(helmet());    
      api.use(helmet.hidePoweredBy({ setTo: 'Blood, Sweat and Tears' }));

    api.post('/new',  (req, res, next) => {
        res.send('some content');
    });
return api;
}
```

**Comment by nagman** [comment]
Same issue here.

```
const express = require('express');
const compression = require('compression');
const helmet = require('helmet');
const morgan = require('morgan');

const app = express();

app.use(helmet({hidePoweredBy: {setTo: 'PHP 7.3.3'}}));

app.use(morgan('common'));

app.use(compression());

app.get('/', function(req, res) {
	res.send('Hi there');
});

app.listen(80, () => console.log(`API listening`));
```

If I don't specify a `setTo` for `hidePoweredBy`, the header X-Powered-By isn't removed in development env.

In production env, it works yet.

**Comment by EvanHahn** [comment]
@nagman Does your code look like this without the `setTo`?

```js
app.use(helmet());
```

What does it look like instead?

**Comment by nagman** [comment]
@EvanHahn yup, looks like this: 
```
app.use(helmet());
```

**Comment by EvanHahn** [comment]
@nagman I'm not able to reproduce this with the snippet you provided. What version of Node, Express, and Helmet are you using? And are you using anything "in front" of your app, like nginx?

If this issue isn't related to Express 4.14.0, I'd appreciate it if you could open a new issue so that we can move discussion there (it'll send fewer notifications to everyone else in the thread).

**Comment by neruchev** [comment]
Same problem. 

node: 10.13.0
express: 4.16.4
helmet: 3.16.0

Cause of the problem: when the `hide-powered-by` tries to remove the header, this header is not installed yet, so nothing happens.

It seems you need to use the `hide-powered-by` somewhere below by code.

**Comment by EvanHahn** [comment]
@neruchev Are Helmet's other headers, like `X-XSS-Protection`, being set?

**Comment by dianugroho** [comment]
> Make sure other instance of Express like your routes uses helmet.js
> 
> ```
> import Router from 'express';
> import helmet from 'helmet';
> 
> export default ({ config, db, ....}) => {
>       let api = Router();
>       api.use(helmet());    
>       api.use(helmet.hidePoweredBy({ setTo: 'Blood, Sweat and Tears' }));
> 
>     api.post('/new',  (req, res, next) => {
>         res.send('some content');
>     });
> return api;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/15644699/34355342-7e6395cc-ea6f-11e7-880d-b6e956012a3b.png)

Saved my life

**Comment by johnfrades** [comment]
cant make it work, tried any other thing, seems like helmet doesnt work for me.
The only thing worked for me is this

api.use(helmet.hidePoweredBy({ setTo: 'Blood, Sweat and Tears' }));

**Comment by EvanHahn** [comment]
@johnfrades Is `X-Powered-By` the only header that Helmet fails to set for you?

If so, does `app.disable('x-powered-by')` work?

**Comment by HristijanStrkovski** [comment]
Had exactly the same problem as the rest, fixed it by emptying cache and hard reloading the page.

**Comment by bres-JUPITAKA** [comment]
in my exprience, place 'app.use (helmet ())' at the last of routes/middleware then it well works.

**Comment by BartTK** [comment]
I was encountering the same problems. During development, my requests were going through a webpack dev server proxy. Bypassing this proxy solved the issue.

**Comment by pradeep-rajput13** [comment]
I faced the same issue. But I had one observation that this issue used to occur only on the Chrome browser. When I checked in safari I didn't get the x-powered-by header. Even through curl, I didn't get the x-powered-by header. So might be some issue with chrome version. And the issue was only with 'x-powered-by' header not for other headers.

**Comment by rolanday** [comment]
Just in case anybody else runs into the same problem, also found needed to hard reset cache and reload page as @HristijanStrkovski indicated.

**Comment by t4eng** [comment]
I same problem with browser X-Powered-By → Express. But when try open browser mode private browsing i don't found X-Powered-By. I suggest clear browser or try new browser

**Comment by wondertweaks** [comment]
> Just in case anybody else runs into the same problem, also found needed to hard reset cache and reload page as @HristijanStrkovski indicated.

It's also worth noting if you are using a domain scanning site to verify this info, check for vulnerabilities, etc. that these sites cache their data they are displaying. So if you first visited the site with X-Powered-By showing, each time you visit the site again it will show even if you have resolved the issue. 

As suggested previously, clear the cache in your browser and view the header info in your browser, or if using a scanning sites try a new site after attempting your fixes.

**Comment by engmsilva** [comment]
I'm using:
"express": "^4.17.1"
"helmet": "^4.6.0"

I managed to hide ETag and X-Powered-By making the calls in the following order:

```
import express from "express";
import helmet from "helmet";

const app = express();
app.use(helmet());
app.disable("x-powered-by");
app.disable("etag");
```

Note: X-Powered-By is only hidden if you disable the eTag too

**Comment by Manik-Jtg** [comment]
I'm using:
"express": "^4.17.2"
"helmet": "^5.1.1"

import express from "express";
import helmet from "helmet";
const app = express();
app.use(helmet());

None of the helmet headers show up and also x-powered-by remains there with value Express.

**Comment by classname-cyril** [comment]
https://phps.space/questions/is-it-possible-to-transmit-both-html-and-php-files-using-expressjs



I spent hours searching for a solution and finally uncovered the answer
