### ISSUE TITLE
504 error on POST requests through proxy

### ISSUE THREAD

**Issue by syakiruzair** [helmetjs/helmet#135]
I am not sure if this is bug or a misconfiguration at our side. It seems that this middleware is causing 504 error intermittently on POST requests through proxy. We are using this middleware on top of **connect** (https://github.com/senchalabs/connect) and the POST requests are proxied to another server by using **http-proxy-middleware** https://github.com/chimurai/http-proxy-middleware. 

This issue does not happen on GET requests which are also proxied and it happens even when all the modules are disabled.

**Comment by EvanHahn** [comment]
Could I see how you're using Helmet in your app? A code snippet would be perfect.

**Comment by syakiruzair** [comment]
This is just the general overview of the implementation. Hope it can help.

```
import connect from 'connect';
import proxyMiddleware from 'http-proxy-middleware';

const app = connect();
app.use(helmet());
app.use(proxyMiddleware('/api', {
    target: proxyUrl,
    pathRewrite: {
        '^/api/(.+)': proxyDir
    },
    changeOrigin: true
}));
app.listen(port);
```

**Comment by syakiruzair** [comment]
This is just the general overview of the implementation. Hope it can help.

```
import connect from 'connect';
import proxyMiddleware from 'http-proxy-middleware';
import helmet from 'helmet';

const app = connect();
app.use(helmet());
app.use(proxyMiddleware('/api', {
    target: proxyUrl,
    pathRewrite: {
        '^/api/(.+)': proxyDir
    },
    changeOrigin: true
}));
app.listen(port);
```

**Comment by EvanHahn** [comment]
I don't see anything yet...

A couple of questions:

1. Did you say that you see these 504 errors happen when `helmet` is removed?
1. Are you able to replicate these errors locally? If so, are you able to see any stack traces or anything?

**Comment by syakiruzair** [comment]
1. No, the 504 errors happen when **helmet** is used. They do not happen when I comment it out. What I meant was, they only happen during POST requests. 
2. These errors happen locally during development. I did not see any stack trace in **Node** console nor coming from the backend **API**.

**Comment by EvanHahn** [comment]
Could you try adding an error handling middleware to the end of your file? Maybe something like this:

```js
// ...

app.use(function (err, req, res, next) {
  console.error('Got an error!', err);
  res.end();
});

app.listen(port);
```

You might be able to see the error by doing that.

**Comment by syakiruzair** [comment]
I cannot reproduce the problem anymore. It seems that the problem was from our side and it got fixed somehow. I notice that when it happened before, the POST requests took a long time before receiving 504 errors. Now POST requests through **helmet** is working fine. Thank you for your help.

**Comment by EvanHahn** [comment]
Good to know things are working fine!

May I close this issue?

**Comment by syakiruzair** [comment]
Yes please. Thank you.

**Comment by EvanHahn** [comment]
Will do.

Feel free to open a new issue if you run into any problems!
