### ISSUE TITLE
Add X-Permitted-Cross-Domain-Policies middleware, off by default

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#140]
See [this page on OWASP](https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#X-Permitted-Cross-Domain-Policies).

Could be useful for protecting against some Flash-related attacks.

**Comment by EvanHahn** [comment]
I'm going to close this. While it may be a good idea, Helmet [kinda used to do this](https://github.com/helmetjs/crossdomain) and we stopped including at all, and Flash is on its way out.

**Comment by Malvoz** [comment]
This however applies to PDF aswell.

**Comment by EvanHahn** [comment]
That's true—perhaps this is worth reinstating.

I can't see any reason NOT to add it, so I'll consider adding this in Helmet 4.

**Comment by EvanHahn** [comment]
This has been added to Helmet in 3.13.0! You can see the [documentation here](https://helmetjs.github.io/docs/crossdomain/).

This isn't enabled by default but will be in Helmet 4—see #175 to track that change.
