### ISSUE TITLE
Suggestion: Move to using ES6 in examples

### ISSUE THREAD

**Issue by atjonathan** [helmetjs/helmet#141]
Basically all we would need to change is `var` to `const` and add `"use strict"`. We shouldn't use the new `import` syntax yet because that requires build systems like webpack.

If you are wanting to stick with ES5, to support older versions of Node, then no problem!

**Comment by EvanHahn** [comment]
This is something I've thought about and have gone back and forth on. But I think I'll stick with ES5 for now, until the `import` syntax is finalized.

Does that sound okay?

**Comment by atjonathan** [comment]
Sure!
