### ISSUE TITLE
Add a note to the documentation that helmet should be called first

### ISSUE THREAD

**Issue by Jonas-Drotleff** [helmetjs/helmet#144]
The order of middlewares in Express is very important as express is going through them sequentially. Helmet is preventing various vulnerabilities so it should be the first middleware to be called.

You should explicitly point this out in your documentation.

For more information see [this](http://stackoverflow.com/questions/41492312/middleware-order-express) stackoverflow post,

**Comment by EvanHahn** [comment]
There are two things to consider here.

## Making sure you send the response headers

If you want Helmet's protection for all of your responses, you should set it up early. For example, this will set Helmet's headers for all responses:

```js
const app = express();
app.use(helmet());
// ...
```

Where this may not—the static middleware may get to it first:

```js
const app = express();
app.use(express.static(/* ... */));
app.use(helmet());
// ...
```

There may be cases where you don't want to use Helmet for all responses. You may wish to have different configurations for different routes, or you may wish to avoid setting the headers for performance in rare cases. However, I expect most people will want to set it early and forget about it.

## Overwriting response headers

Helmet sets various headers, like `Content-Security-Policy`. It will override any header value that was previously set.

For example, this will override Helmet's default value for `X-Frame-Options`:

```javascript
// Final header: X-Frame-Options: DENY
app.use(helmet());
app.use((req, res, next) => {
  res.setHeader('X-Frame-Options', 'DENY');
  next();
});
```

This will use Helmet's default:

```javascript
// Final header: X-Frame-Options: SAMEORIGIN
app.use((req, res, next) => {
  res.setHeader('X-Frame-Options', 'DENY');
  next();
});
app.use(helmet());
```

I would not recommend doing something like this in most cases; you should probably just set the header in one place. But there may be cases where you need to set the header value twice, and that's okay. I hope this explains how it works.

**Comment by markdascher** [comment]
Perfect, thanks! Sounds like putting it first is still the most predictable choice. 👍
