### ISSUE TITLE
HSTS divides maxAge by 1000

### ISSUE THREAD

**Issue by andrao** [helmetjs/helmet#145]
The [documentation](https://helmetjs.github.io/docs/hsts/) suggests that the `maxAge` parameter be given in seconds. The [hsts](https://www.npmjs.com/package/hsts) package however divides the input by 1000.

**hsts** _index.js_, version 1.0.0:
```javascript
8    var maxAgeMS = options.maxAge != null ? options.maxAge : oneDay
35   var maxAge = Math.round(maxAgeMS / 1000)
36   var header = 'max-age=' + maxAge
```

**Comment by andrao** [comment]
Ah, I see that this has been addressed in version 3.3.0.

I just now ran a fresh `npm install --save helmet` but was given 2.3.0. Strange.

**Comment by EvanHahn** [comment]
That's odd...does it happen when you do it again? Was there a version specified in your package.json?

In any case, do you mind if I close this issue?

**Comment by andrao** [comment]
This is from helmet 2.3.0, which depends on hsts 1.0.0.

And yes, it may be closed.

**Comment by EvanHahn** [comment]
Sounds good. Feel free to open an issue if you run into any other problems!
