### ISSUE TITLE
Drop support for Node <10

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#146]
This will involve doing the following in all libraries:

- Updating the `engines` field in `package.json`
- Removing the versions from `.travis.yml`

**Comment by EvanHahn** [comment]
There's no real rush on this—just something to keep in mind for the next major version.

**Comment by EvanHahn** [comment]
Planning on releasing Helmet 4 in April, which is when Node 6 is scheduled to be deprecated, so we'll only allow Node 8+.

**Comment by XhmikosR** [comment]
You should also switch to ES6+ while at it :)

**Comment by EvanHahn** [comment]
@XhmikosR That's the plan!

**Comment by EvanHahn** [comment]
This was done in ab556c272f85c84f34ccc04d7417f3412e6afd39, which was merged into the `4.x` branch. See #197 for more.

**Comment by EvanHahn** [comment]
This was done in ab556c272f85c84f34ccc04d7417f3412e6afd39, which was merged into the `4.x` branch. See #197 for more.
