### ISSUE TITLE
Adding support for Expect-CT header

### ISSUE THREAD

**Issue by joostdebruijn** [helmetjs/helmet#147]
At this moment browsers (at least Chrome and Firefox) are implementing support for the Expect-CT header, which enforces browsers to check if there are public transparency log entries of the used website certificate. I think it would be great to add support for this header to Helmet!

The [(draft) specification of the header](https://datatracker.ietf.org/doc/draft-stark-expect-ct) is available and Scott Helme already wrote [a nice blog](https://scotthelme.co.uk/a-new-security-header-expect-ct/) about it.

If I can help, please let me know! 😄

**Comment by EvanHahn** [comment]
This is the first I've heard of this header—looks like a good candidate for Helmet. I'll do a little more reading and maybe get started on another submodule.

**Comment by EvanHahn** [comment]
[Here's a "first draft" of the module](https://github.com/helmetjs/expect-ct), not yet published to npm.

If that looks okay to you, I'll publish it and add it to Helmet.

**Comment by joostdebruijn** [comment]
Looks great! I did also a few tests within a simple Express-application and it worked well.

**Comment by EvanHahn** [comment]
Great!

I may be a bit, but I'll release that when I get a chance.

**Comment by EvanHahn** [comment]
Published! You can find the module in `helmet@3.6.0` under `helmet.expectCt` or as a standalone npm module with `npm install expect-ct`.
