### ISSUE TITLE
Add middleware to check Origin/Header for CSRF attacks

### ISSUE THREAD

**Issue by nickclaw** [helmetjs/helmet#150]
As mentioned by [OWASP](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet), a simple CSRF defense is simply by checking if the Origin/Referrer headers match your site.

It's fairly simple to implement and might be a good fit for a non-default module.

**Comment by EvanHahn** [comment]
I like this but don't think it's in Helmet's scope. Helmet is meant to set
HTTP headers but not to check them.

If you're interested, I'm happy to collaborate with you on a module. Is
that something you'd be interested in?

**Comment by nickclaw** [comment]
My confusion, it's a fairly simple module so I'll probably end up publishing something soon. If you ever think about expanding Helmet's scope let me know!

**Comment by EvanHahn** [comment]
Sounds good! Let me know if you want _any_ help on the new module—I think it's a good idea. Feel free to mention me on an issue or email me at <me@evanhahn.com>.

**Comment by Prinzhorn** [comment]
@nickclaw did you publish something? I just hacked together this middleware and wonder if there is something already out there that I could use instead?

```js
const { URL } = require('url');

module.exports = function(req, res, next) {
  let origin = req.header('origin') || req.header('referer');

  if (!origin) {
    let err = new Error(`CSRF protection, rejected request with missing Origin and Referer headers`);
    return next(err);
  }

  let originURL;

  try {
    originURL = new URL(origin);
  } catch (err) {
    return next(err);
  }

  if (originURL.hostname !== req.hostname) {
    let err = new Error(`CSRF detected, request coming from ${origin}`);
    return next(err);
  }

  next();
};

```

**Comment by Prinzhorn** [comment]
@nickclaw for our use-case we don't need the pattern matching I guess, because we can use the location of the page that is served (e.g. `req.hostname` etc.) and compare it with the referer and origin headers. However if you want to allow certain cross domain requests than you need more. But I'm not a fan of using regular expression for this and would rather have a whilelist to compare with and use a proper URL parser.
