### ISSUE TITLE
[feature request] Hapi support

### ISSUE THREAD

**Issue by sfabriece** [helmetjs/helmet#153]
It would be nice to add [Hapi](https://github.com/hapijs/hapi) support.

I know hapi already comes with some of the stuff provided here, but not all of them.

**Comment by EvanHahn** [comment]
This would be interesting. I know next to nothing about Hapi, so I don't know how we'd add this as a plugin.

Because Helmet uses a "traditional" Node callback structure, I'd imagine it could be added.

Do you know anything about Hapi plugins?

**Comment by sfabriece** [comment]
Yes I do, I could try to put together a PR when I get time.

**Comment by EvanHahn** [comment]
It might be worth making an entirely new package like `hapi-helmet`. I'm happy to help you work on it if you want!

**Comment by EvanHahn** [comment]
Because this is out of Helmet's scope, I'm going to close this issue. But if you'd like help on `hapi-helmet` (even if you have no idea where to start!), feel free to reply here or email me at <me@evanhahn.com>.

**Comment by labsvisual** [comment]
@EvanHahn, sorry for bumping this so late. I tried searching for `hapi-helmet`. I am more than willing to start working on it since we need it ASAP. 

Sounds like a plan?

**Comment by EvanHahn** [comment]
@labsvisual Sure! Feel free to ask me questions (again, my email is <me@evanhahn.com>) or add me as a reviewer on `hapi-helmet`.

I'm not familiar with Hapi but can help with the HTTP headers part.
