### ISSUE TITLE
is hsts default?

### ISSUE THREAD

**Issue by omryr** [helmetjs/helmet#154]
when I add the following:
app.use(helmet());
and run the code, i do not get hsts as default header, if i explicitly call it, it does work. 
from what I understand in the list it says it should be default, is this normal behavior?

**Comment by EvanHahn** [comment]
The header is only set when `req.secure` is true, which is likely not so in development. Does that sound like what's happening?

**Comment by EvanHahn** [comment]
@omryr Helmet 3.8.0 should set the HSTS header by default. That's almost certainly what's causing your problem here. Try updating and let me know if you are still experiencing the problem.
