### ISSUE TITLE
Brotli bundles not being recognized

### ISSUE THREAD

**Issue by timothydlee** [helmetjs/helmet#155]
Sorry if this is not the appropriate avenue to discuss this, but I'm having issues trying to implement Helmet in a React application. We're using Webpack 3.0 and we're chunking as well as compressing our JS bundle using the Brotli compression format. I'm getting these similar errors:

`Refused to execute script from 'http://localhost:3000/js/chunks.js.br' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.`

`Refused to execute script from 'http://localhost:3000/js/bundle.js.br' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.`

This is our code in our server file:

```
//Content Security Policy Headers

function generateNonce(req, res, next) {
  const rhyphen = /-/g
  res.locals.nonce = uuid.v4().replace(rhyphen, ``)
  next()
}

function getNonce(req, res) {
  return `'nonce-${ res.locals.nonce }'`
}

function getDirectives() {
  const self = "'self'";
  const none = "'none'";
  const unsafeInline = `'unsafe-inline'`;
  const scripts = [
    `cdn.smooch.io`,
    `cdn.headwayapp.co`,
    `helphero.co`,
    `app.helphero.co`,
    `cdn.heapanalytics.com`,
    `google-analytics.com`
  ]
  const styles = [
    `data:`,
    `www.google-analytics.com`
  ]
  const fonts = [
    `data:`
  ]
  const images = [
    `https:`,
    `data:`
  ]
  const connect = [
    `app.helphero.co`
  ]
  const pluginTypes = [
    `application/br`,
    `application/octet-stream`
  ]
  
  return {
    defaultSrc: [none],
    scriptSrc: [self, getNonce, ...scripts],
    styleSrc: [self, unsafeInline, ...styles],
    fontSrc: [self, ...fonts],
    imgSrc: [self, ...images],
    connectSrc: [self, ...connect],
    pluginTypes: [getNonce, ...pluginTypes]
  }  
}

app.use(generateNonce);

app.use(helmet.contentSecurityPolicy({
  directives: getDirectives()
}))
```

Is there something I'm doing wrong or is a .br extension not supported yet?

**Comment by EvanHahn** [comment]
I'm totally unfamiliar with Brotli, so please let me know if this is totally wrong:

The error you're getting seems to be because you're sending a `application/octet-stream` MIME type (or perhaps a `.js.br`) file extension, which I _think_ doesn't have much to do with Helmet, though I'm not sure.

Does this problem happen when you remove the use of `helmet.contentSecurityPolicy`?

**Comment by timothydlee** [comment]
@EvanHahn, there must have been something wonky going on in the branch that I was initially implementing this in. I tried it on a clean branch from our prerelease and things worked much more smoothly. I'm not sure what was causing this issue, but it's no longer breaking. Thanks for the help though!

**Comment by EvanHahn** [comment]
Glad I could help in some small way!
