### ISSUE TITLE
HTTP OPTIONS Request not secured

### ISSUE THREAD

**Issue by NicolaiSchmid** [helmetjs/helmet#157]
Hey, I've noticed a behaviour of my express server, which might be a bug in Helmet.
When Chrome sends a HTTP OPTIONS request to my server, all of helmets features are not invoked. Which means an `x-powered-by` tag is exposed, no `hsts` header is set, etc.
Is this an expected behaviour, or is this a bug?

**Comment by EvanHahn** [comment]
That's surprising!

I'm away from a computer right now. Do you know if this happens with a "vanilla" Express app? Would you be able to make a simple app and see if this behavior occurs?

**Comment by NicolaiSchmid** [comment]
Using this code
```
const express = require('express');
const helmet = require('helmet');
const app = express();

app.use(helmet());
app.listen(80);
```
with cURL I get this response:
```
HTTP/1.1 200 OK
X-DNS-Prefetch-Control: offX-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Allow: GET,HEAD
Content-Type: text/html; charset=utf-8
Content-Length: 8
ETag: W/"8-ZRAf8oNBS3Bjb/SU2GYZCmbtmXg"
Date: Mon, 07 Aug 2017 10:43:35 GMT
Connection: keep-alive

GET,HEAD
```
which seems fine. 

Searching around in my own code, I found that using `app.use(helmet())` after using the [`expressjs/cors`](https://github.com/expressjs/cors) middleware was causing the issue. When I switched the order around, everything works fine and as expected

**Comment by EvanHahn** [comment]
Sounds good! Please feel free to open another issue if you see something else wrong.

**Comment by attindersingh90** [comment]
The reordering did work perfectly. Thanks
