### ISSUE TITLE
custom content-security-policy scriptSrc for express.router()

### ISSUE THREAD

**Issue by hawleye** [helmetjs/helmet#158]
I am using express's router object, instead of just app.use(''/", ..., which I saw mentioned in another issue could be an issue.

I would like to add 'sha256-#hash#' to my csp header, only on a specific page as it represents an inline script I havn't figured out how to get around using. this hash value will be different for other pages. 
I tried the example used here: https://stackoverflow.com/questions/44511837/implement-helmet-csp-on-individual-routes but I was unable to make it work as it also used app.get() instead of a router object.

route structure is copied from here: https://scotch.io/tutorials/keeping-api-routing-clean-using-express-routers

helmet originally set in the examples below:
app.js
```
var helmet=require('helmet');
app.use(helmet({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            scriptSrc: ["'self'"],
            frameAncestors: ["'none'"]
        }
    },
    frameguard: {
        action: 'deny'
    }
}));
app.use('/', routes);
```

Here is a modified example of my ^link inspired attempt:
specificRoute.js
```
var router= require('express').Router();
var helmet = require('helmet');
var cspFillScripts = helmet.contentSecurityPolicy({
    directives: {
        scriptSrc: ['#hash#']
    }
});
router.route('/specificRoute')
.get(cspFillScripts, function(req, res, next) {
    //database call(... ... callback {
   res.render('/myView', {variable: databaseResult[0]});
});
```

Here is a modified example of my current attempt: 
specificRoute.js
```
var router = require('express').Router();
var myDb=require('../models/mysql.js');
var helmet=require('helmet');
router.route('/specificRoute')
.get(function (req, res, next) {
    //database call (.. .. callback {
         helmet.contentSecurityPolicy({
              directives: {
                    scriptSrc: ['sha256-#hash#']
              }
         })
        res.render('/myView', {variable: databaseResult[0]}):
    })
} );
module.exports=router;
```

I would appreciate any examples, explanations, or improved search terms that could point me in the right direction.

**Comment by EvanHahn** [comment]
Does something like your second example not work for you? 

```js
var cspFillScripts = helmet.contentSecurityPolicy({ /* ... */ });

router.route('/specificRoute')
.get(cspFillScripts, function (req, res) {
  // your route handler
});
```

**Comment by hawleye** [comment]
I believe that matches my first example (the middle one). I may be missing something

**Comment by EvanHahn** [comment]
Glad it worked!
