### ISSUE TITLE
chrome csp not recognizing 'self'

### ISSUE THREAD

**Issue by hawleye** [helmetjs/helmet#159]
Sorry to bother you again, but I can't figure out what I am doing wrong. Google only directs me toward chrome extensions or downloadable app development, not website development. 

**For a form page with custom js**
using:
```
var cspFillScripts = helmet.contentSecurityPolicy({
    directives: {
        defaultSrc: ["'self'"],
        scriptSrc: ['"self"', "'sha256-nsMhNx3hqXGnbmxJ+NiLNcusEXVvuMQqUopRWCGZhh8='"],
        frameAncestors: ['"none"']
    }
});
```
in proper route: 
`.post(cspFillScripts, function (req, res, next) {...`

produces:

> The source list for Content Security Policy directive 'default-src' contains an invalid source: '"self"'. It will be ignored.

for each source, followed by:

> Refused to load the image 'http://localhost:3000/img/poslinker_beF_icon.ico' because it violates the following Content Security Policy directive: "default-src "self"". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

for each request. this leaves my page as plain html, no css, images, js, nothing outside the ejs file. 

however, **For an ordinary page**
 using:
```
app.use(helmet({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            scriptSrc: ["'self'"],
            frameAncestors: ["'none'"]
        }
    },
    frameguard: {
        action: 'deny'
    }
}));
```
in app.js after setting view engine and views folder but before static declaration, database connection, route use, and server creation, works as it should to allow my various files to be used in page creation for a route with no custom csp as in the first example.

Where should I be looking for my error? Is there any difference in how I included 'self'?

**Comment by EvanHahn** [comment]
The error seems to be that you're writing `'"self"' ` instead of `"'self'"` (note the quotes). Could you try that and see if that works?

**Comment by hawleye** [comment]
well I had played with it only because of getting this error to begin with, so I have verified all are double, single, self, single, double. the only one I had to change was script-src "'self'", yet somehow that fixed the problem with default-src. it now only presents the invalid error for script-src and frame-ancestors. it allowed css and image, but still is blocking all js.

**Comment by hawleye** [comment]
both chromium and firefox appear to have accepted the csp swimmingly. It's just chrome (and maybe IE/Edge, as I can't test that on linux) that I am encountering this, if that matters.

**Comment by EvanHahn** [comment]
Hmm, that's odd.

Could you open the Network tab in an inspector (Chrome and Firefox should both have this tab) and tell me what the `Content-Security-Policy` header is?

**Comment by hawleye** [comment]
Content-Security-Policy: default-src 'self'; script-src 'self' 'sha256-nsMhNx3hqXGnbmxJ+NiLNcusEXVvuMQqUopRWCGZhh8='; frame-ancestors 'none'

**Comment by EvanHahn** [comment]
1. Do you still see the `The source list for Content Security Policy directive 'default-src' contains an invalid source: '"self"'. It will be ignored` error with that policy?
1. Does _nothing_ load when you have that CSP? It seems like things should be able to load from your development domain, which I assume is `localhost:3000`.

**Comment by hawleye** [comment]
current error list: 

> CustomerFile:1 The source list for Content Security Policy directive 'script-src' contains an invalid source: '"self"'. It will be ignored.
> CustomerFile:1 The source list for Content Security Policy directive 'frame-ancestors' contains an invalid source: '"none"'. It will be ignored.
> CustomerFile:1 Refused to load the script 'http://localhost:3000/libs/POS/Accounting/AccountsReceivable/customerFile.js' because it violates the following Content Security Policy directive: "script-src "self" 'sha256-nsMhNx3hqXGnbmxJ+NiLNcusEXVvuMQqUopRWCGZhh8='".
> 
> CustomerFile:1 Refused to load the script 'http://localhost:3000/libs/keyboard.js' because it violates the following Content Security Policy directive: "script-src "self" 'sha256-nsMhNx3hqXGnbmxJ+NiLNcusEXVvuMQqUopRWCGZhh8='".
> 
> CustomerFile:1 Refused to load the script 'http://localhost:3000/libs/clock.js' because it violates the following Content Security Policy directive: "script-src "self" 'sha256-nsMhNx3hqXGnbmxJ+NiLNcusEXVvuMQqUopRWCGZhh8='".

it is loading all css files and .gif now, after changing the script-src 'self'. all external js is blocked. it appears that the js represented by the sha256 hash has been allowed to go through, as it is found in the elements page. 
I am unsure why the script-src error was blocking the css and image, and why the external js is still being blocked.

**Comment by EvanHahn** [comment]
Those first two errors look like they're happening because of `"self"` instead of `'self'` and the same for `'none'`.

How are you loading your scripts?

```html
<!-- does it look more like this... -->
<script src="http://localhost:3000/libs/clock.js"></script>

<!-- or more like this? -->
<script src="/libs/clock.js"></script>
```

**Comment by hawleye** [comment]
my script declarations look like 

`<script src='/libs/clock.js'></script>`

because of 
```
app.set('view engine', 'ejs');
app.set('views', __dirname + '/views');
```
& 
`app.use(express.static(__dirname + '/public'));`

and my (shortened) file structure is 

> app.js
> views folder (set in app.js using express)
> ->partials folder
> -->footer.ejs
> ->POS folder
> -->...
> --->customerFile.ejs
> public folder (set in app.js using express)
> ->libs folder
> -->clock.js
> -->keyboard.js
> -->POS folder
> --->...
> ---->customerFile.js
> ->img
> -->poslinker.gif
> controllers folder
> ->...

**Comment by hawleye** [comment]
I have no idea why, because I didn't remove the csp yet this morning. But I ran it again to study the error before removing the csp so I could continue development. The errors are gone. I have no idea if/when they will come back. 

It may be related to a problem on Friday in which all my browsers kept crashing. I had to leave the computer off all weekend, since both restarting and full shutdown-turn on did not work. Browsers seem to be working fine + csp errors have left. 

I am very confused.

**Comment by EvanHahn** [comment]
That is confusing!

It sounds like the problems are gone. If they are, would you mind closing this issue?

**Comment by hawleye** [comment]
thanks so much for all your help

**Comment by EvanHahn** [comment]
No problem! Glad everything worked out.

Feel free to open a new issue if you encounter other problems.
