### ISSUE TITLE
Add flow support

### ISSUE THREAD

**Issue by followbl** [helmetjs/helmet#160]
hey @EvanHahn thanks for helmetjs

made this PR for helmet adding in flow-type support...not sure how into it you are, but figured wouldn't be bad to at least have your 👀  on it. It's my first flow-typed contribution so if you see anything worth mentioning, holler...otherwise I'll close this when it's merged 😺 

https://github.com/flowtype/flow-typed/pull/1228

**Comment by EvanHahn** [comment]
I'm not an expert at Flow but it seems alright!

Perhaps worth noting that Helmet isn't exclusively for Express—it should work with any `IncomingRequests` and `ServerResponse`s from the [built-in http module](https://nodejs.org/api/http.html). I think what you have is fine, though.

**Comment by followbl** [comment]
that is 100% why you ask the owner! complete oversight on my part. thanks, let me refactor

**Comment by EvanHahn** [comment]
@followbl Do you mind if I close this issue because it's not strictly part of Helmet? Happy to continue the discussion here if I can help in some way.

**Comment by followbl** [comment]
of course. thanks for your input, still need to finish it up, but isn't an issue on your part anymore.

**Comment by EvanHahn** [comment]
Sounds good.

Feel free to comment on this issue if I can help further!
