### ISSUE TITLE
Allow functions to be passed for middleware options

### ISSUE THREAD

**Issue by chaddjohnson** [helmetjs/helmet#162]
Hi! Thanks for the great middleware.

It would be great if it was possible to pass a function in addition to a boolean for each of the options accepted by `helmet()` so that each middleware can be conditionally used with each request. For instance, I might want to check on each request whether `req.hostname` should be allowed, and if so, disable frameguard:

```javascript
app.use(helmet({
    frameguard: function(request) {
        const whitelist = ['mydomain.com', 'myotherdomain.com'];
        return whitelist.includes(req.hostname);
    }
}))
```

Looking at the existing code, it seems this change is non-trivial, but maybe it's something to consider for the future.

**Comment by EvanHahn** [comment]
Is this something you'd be able to accomplish with [conditional middleware](https://github.com/elliotttf/express-conditional-middleware)? I think not, but I want to see if it can be done another way.

**Comment by EvanHahn** [comment]
@chaddjohnson Any updates on this?

**Comment by chaddjohnson** [comment]
@EvanHahn No sir, I never got around to pursuing this :)

**Comment by EvanHahn** [comment]
Okay. Do you feel like your problem has been resolved? If so, I'll close the issue. If not, I'll try to help!

**Comment by chaddjohnson** [comment]
Yes, I'm good! Not worried about this any longer. It's a very low priority nice to have feature for me. If it becomes necessary, I'll refer back to this issue. Thanks for checking!

**Comment by EvanHahn** [comment]
Sounds good! Feel free to comment here or open a new issue if anything comes up.
