### ISSUE TITLE
Can't seem to disable frameguard on specific route

### ISSUE THREAD

**Issue by Billy-** [helmetjs/helmet#163]
I have helmet configured like this:

```
const app = express()

app.use(helmet())
// ...
app.use('/specificRoute', helmet.frameguard(false), (req, res) => { /* ... */ })
```

I also tried using `helmet({ frameguard: false })` but had the same result - I still get the `X-Frame-Options: SAMEORIGIN` header.

**Comment by EvanHahn** [comment]
`app.use(helmet())` sets the `X-Frame-Options` header, and Helmet doesn't have any mechanisms for undoing these headers. You could do something like this:

```js
const app = express()

app.use(helmet())

function removeFrameguard (req, res, next) {
  req.removeHeader('X-Frame-Options')
  next()
}

app.use('/specificRoute', removeFrameguard, (req, res) => { /* ... */ })
```

Does that help?

**Comment by Billy-** [comment]
Yes, thanks. And thanks for the unfathomably fast reply!

Is this not something we could add to helmet? I'd be happy to submit a PR.

**Comment by EvanHahn** [comment]
It's something I've thought about but probably won't add. Conditional middleware in Express seems uncommon enough that it's not worth baking into the library. It seems like something that needs to be handled at the Express level—either built into Express or as a more general plugin. Does that make sense?

Gonna close this issue because your problem is solved, but lemme know if I am mistake and should reopen.

**Comment by Billy-** [comment]
I think you meant `res.removeHeader` rather than `req.removeHeader` ;)

> Conditional middleware in Express seems uncommon enough that it's not worth baking into the library. It seems like something that needs to be handled at the Express level—either built into Express or as a more general plugin. Does that make sense?

No, not really sure why you would say that, but maybe I'm missing something?

Disabling further down the line seems like a perfectly valid use-case; turn it on as a blanket-statement, then turn it off only as an exception. Shouldn't be too hard to check if `action === false` in frameguard and if so `res.removeHeader('X-Frame-Options')` if so.

**Comment by EvanHahn** [comment]
`res.removeHeader` is right—good catch.

Let's take the [body-parser](https://github.com/expressjs/body-parser) middleware as an example. (This is a contrived example but I hope it is demonstrative.) You might want to parse bodies on most routes, but not all—it can have performance implications.

Let's say you want to disable the body-parser middleware when rendering the `/about` page.

This is basically impossible to express (so to speak):

```javascript
app.use(bodyParser.json({ /* ... */ }))

app.get('/about',
  skipBodyParser,
  (req, res) => { /* ... */ })
```

You have to change the order you define middleware, like this:

```javascript
app.get('/about', (req, res) => { /* ... */ })

app.use(bodyParser.json({ /* ... */ }))
```

This sometimes works but can be inelegant. I'd argue that this is a shortcoming of Express, not of your application's design—what you want to do is valid!

I've mused on solutions for this and I think it involves a new framework (which I'm generally against), a brittle Express plugin, or something wild like this:

```javascript
const omit = require('lodash/omit')

const myMiddleware = {
  helmet: helmet(),
  bodyParser: bodyParser.json({ /* ... */ })
}

function middleware (exclude) {
  exclude = exclude || []
  return Object.values(omit(myMiddleware, exclude))
}

app.get('/route-that-uses-all-middleware',
  middleware(),
  (req, res) => { /* ... */ })
  
app.get('/route-that-skips-helmet',
  middleware(['helmet']),
  (req, res) => { /* ... */ })
```

Does that make sense?

**Comment by snallari** [comment]
I m not able to do a proper test when using helmet. It shows up in console, but when i set framegaurd to deny , it still loads on iframe. Can you help me with this

**Comment by EvanHahn** [comment]
@snallari Happy to help. Could you open a new issue and I can help debug?
