### ISSUE TITLE
Apply CSP inside callback on router middleware?

### ISSUE THREAD

**Issue by subversivo58** [helmetjs/helmet#164]
I have a route that is accessed with a token that I need to fetch from the database.

As this default route is accessed by an `iframe` I want to apply the **CSP** `frame-ancestors` rule to the source pre-stored in the database

```javascript

    let projectAuthCSP = (req, res, next) => {
        if ( 'query' in req && 'token' in req.query && /[a-z]/g.test(req.query.token) ) {
                 projects.findOne({
                     token: req.query.token
                 }, (err, doc) => {
                     if ( !!err || !doc ) {
                         next()
                     } else {
                         helmet.contentSecurityPolicy({
                             directives: {
                                 'frame-ancestors': [doc.origin]
                             }
                         })
                     }
                 })
        } else {
            next()
        }
    }

    router.get('/project/auth', projectAuthCSP, (req, res, next) => {
        // do stuff...
    })
```

I'm getting a pending status of loading this `iframe` and after some time the error **"Failed to fetch"**.

It is possible?

**Comment by EvanHahn** [comment]
I think what you have is close. Try changing your `helmet.contentSecurityPolicy` invocation to look like this:

```js
helmet.contentSecurityPolicy({
    directives: {
        'frame-ancestors': [doc.origin]
    }
})(req, res, next)
```

Does that work for you?

**Comment by subversivo58** [comment]
Yes, this works fine. Thank you very much :+1: 

I already used it directly on the route:

    router.get('/project/auth', helmet.contentSecurityPolicy({
        directives: {
            'frame-ancestors': ['https://example.com']
        }
    }), (req, res, next) => {
         // do stuff...
    })


When I moved to a midlleware to provide a source dynamically I was not aware of passing parameters to this invocation. I do not know if it would be useful, but I did not find any reference in the documentation.

Once again grateful for your help.

**Comment by EvanHahn** [comment]
Good point.

I'll think about adding something to the docs.
