### ISSUE TITLE
Empty array throws error, contradicts documentation

### ISSUE THREAD

**Issue by dodefey** [helmetjs/helmet#166]
Documentation for CSP (https://helmetjs.github.io/docs/csp/):
```objectSrc: [], // An empty array allows nothing through```
However it threw an error when I tried this.
```Error: object-src must have at least one value. To block everything, set object-src to ["'none'"].```

**Comment by EvanHahn** [comment]
Thanks for reporting—I'll take a look at this soon.

(My suspicion: the docs are incorrect.)

**Comment by EvanHahn** [comment]
This should be fixed in the docs. Thanks for reporting this!
