### ISSUE TITLE
Is helmet mostly for browser use cases?

### ISSUE THREAD

**Issue by vprasanth** [helmetjs/helmet#169]
What I mean is, the headers being set, is the value mostly when the service is hit from a browser? If I'm working on endpoint to endpoint calls (eg. webhooks), whats the milage like?

**Comment by EvanHahn** [comment]
Mostly made for browsers, though not entirely. Of the twelve Helmet middleware, there are a few that might have uses outside of browser-land:

- expectCt, hpkp, and hsts might be used by other HTTP clients
- hidePoweredBy removes a header that identifies that your app uses Express, which might deter hackers slightly
- noCache disables caching, which some non-browsers do

Does that answer your question?

**Comment by vprasanth** [comment]
That makes sense, yes this answers my question. Thank you!
