### ISSUE TITLE
Typescript definition missing for referrerPolicy on main config

### ISSUE THREAD

**Issue by dajomu** [helmetjs/helmet#170]
Hi,

I'm configuring helmet to have a referrerPolicy.
I thought that because I wanted to make a number of config changes I would use helmet with a configuration object, rather than a set of things like `app.use(helmet.referrerPolicy({ policy: 'same-origin' }));`.

So right now I am using -
```
app.use(helmet({
    hsts: {
        maxAge: 5184000
    },
    referrerPolicy: {
        policy: 'same-origin'
    }
}));
```

But I'm getting a typescript error for the referrerPolicy because it isn't defined in DefinitelyTyped.
I'm going to submit a pull request to DT to add the `referrerPolicy` in the main config object definition (and see if there are any others that need to be added).
Before I do, I just wanted to check whether this is a frowned upon way of configuring helmet, or if most users configure each middleware function individually?

**Comment by BlueHatbRit** [comment]
As one of the contributors to those DT types, that PR and it looks good, this should make the types more complete on there 👍

**Comment by EvanHahn** [comment]
Your PR and code style look good! Helmet supports both configuration styles (`app.use(helmet({...}))` and `app.use(helmet.hsts({...}))`.

I'm going to close this issue, but let me know if you have more questions or would like me to reopen it.
