### ISSUE TITLE
blob localhost img src blocked

### ISSUE THREAD

**Issue by lsbyerley** [helmetjs/helmet#171]
I'm generating a blob image dynamically in a vue application and using the following content security policy:

    imgSrc: ["'self'", "blob:", "www.google-analytics.com", "placehold.it"],

A blob img src such as `blob:http://localhost:3000/b07860fe-43cf-4315-b929-15244dafe3b1` is getting blocked. What's the appropriate way to allow this img src?

**Comment by EvanHahn** [comment]
That looks like a problem with your "blob:" URL.

I think it you should set the img src to
"blob:b07860fe-43cf-4315-b929-15244dafe3b1" (or whatever the result of
URL.createObjectURL(yourBlob) is) without the HTTP and localhost
stuff.

Does that help?

**Comment by lsbyerley** [comment]
Meant to circle back to this, but it was actually unrelated to helmet on the server side. I needed to add a CSP meta tag like so:

    <meta http-equiv="Content-Security-Policy" content="img-src 'self' blob: data:">

I'm thinking because the blob was generated client side.

**Comment by EvanHahn** [comment]
That's surprising to me—server-side CSPs are generally more secure—but
great if that works for you!

>
