### ISSUE TITLE
Chrome to drop HTTP-Based Public Key Pinning

### ISSUE THREAD

**Issue by nikwen** [helmetjs/helmet#172]
Chrome is about to drop support for HTTP-Based Public Key Pinning.

https://developers.google.com/web/updates/2018/04/chrome-67-deps-rems

**Comment by nikwen** [comment]
https://github.com/helmetjs/hpkp/issues/14

**Comment by EvanHahn** [comment]
Closing this issue—we'll discuss on https://github.com/helmetjs/hpkp/issues/14.
