### ISSUE TITLE
Feature Policy: A new Chrome feature that might be worth adding to helmet

### ISSUE THREAD

**Issue by nikwen** [helmetjs/helmet#173]
> **TL;DR**
>
> Feature Policy allows web developers to selectively enable, disable, and modify the behavior of certain APIs and web features in the browser. **It's like CSP but instead of controlling security, it controls features!**

Source and more information: https://developers.google.com/web/updates/2018/06/feature-policy

**Comment by EvanHahn** [comment]
I think we should add this to Helmet. It might take me some time to add but it's now on my radar.

Thanks for letting me know about this!

**Comment by Cherry** [comment]
Support is also being added to Safari: https://caniuse.com/#search=feature%20policy and there's some great info at https://scotthelme.co.uk/a-new-security-header-feature-policy/.

Hoping to see this in Helmet soon!

**Comment by EvanHahn** [comment]
While you wait, you can use a simple version:

```javascript
app.use(function (req, res, next) {
  res.setHeader('Feature-Policy', "geolocation 'none'")
  next()
})
```

I'll try to add more fanciness in the Helmet version (some validations and other improvements) but it won't be conceptually much more complex than that.

**Comment by EvanHahn** [comment]
This has been added in `helmet@3.14.0`. Check out [the documentation](https://helmetjs.github.io/docs/feature-policy/) for more.

Thanks for reporting this!
