### ISSUE TITLE
Cross-Origin-Opener-Policy

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#177]
We should implement `Cross-Origin-Opener-Policy`.

~We should pay attention to the `Cross-Origin-Window-Policy` header added in [Safari 12](https://webkit.org/blog/8332/release-notes-for-safari-technology-preview-59/).~

Because there's no spec yet, we shouldn't add this to Helmet yet. It could change quite a lot!

**Comment by Malvoz** [comment]
The header is now `Cross-Origin-Opener-Policy`.

Progress can be followed here: https://github.com/whatwg/html/issues/3740.

**Comment by EvanHahn** [comment]
Thanks! I'll take a look at this.

**Comment by Malvoz** [comment]
Chrome status: https://chromestatus.com/feature/5432089535053824

**Comment by Malvoz** [comment]
@EvanHahn I've updated https://github.com/helmetjs/helmet/issues/177#issuecomment-483816720 with some links that might be helpful.

**Comment by Malvoz** [comment]
And now the Chrome team has released an article on COOP + COEP (https://github.com/helmetjs/helmet/issues/198): https://web.dev/coop-coep/.

**Comment by siboulet** [comment]
Any updates on this? Google is now reporting this as a warning in Search Console. See https://github.com/helmetjs/helmet/issues/198 as well.

**Comment by EvanHahn** [comment]
I've added support for `Cross-Origin-Opener-Policy` (among other `Cross-Origin-` headers) in v4.5.0-rc.1.

You can install with `npm install helmet@4.5.0-rc.1`, see [the docs for 4.5.x on GitHub](https://github.com/helmetjs/helmet/tree/v4.5.x), and the pull request at #296.

Please try it and give me feedback! I will plan to release on April 17/18 unless something disrupts that, such as significant errors in my implementation.

**Comment by EvanHahn** [comment]
This was released in `helmet@4.5.0`. Check out the documentation to see how to use the header.
