### ISSUE TITLE
X-XSS Protection issue Mozilla/4.0

### ISSUE THREAD

**Issue by louiepiol** [helmetjs/helmet#179]
When request header has ```User-Agent: Mozilla/4.0 (compatible; MSIE 4.01; Windows 98)``` 
xss protection disabled.

```X-XSS-Protection → 0```

Can you help me on this?

**Comment by EvanHahn** [comment]
That looks like it's happening because of the "MSIE 4.0" bit. This middleware is disabled in old Internet Explorers for security reasons.

Does that help?

**Comment by louiepiol** [comment]
Is there any way to prevent this, security scanners throw a meduim risk for this issue and its seem someone can fetch anything using this User-Agent.

**Comment by EvanHahn** [comment]
The `setOnOldIE` option should be what you need.

If you're using the top-level `helmet` module, you'd do something like this:

```javascript
app.use(helmet({
  xssFilter: {
    setOnOldIE: true
  }
}))
```

If you're using the `x-xss-protection` module by itself, your code would look like this:

```javascript
app.use(xssFilter({ setOnOldIE: true }))
```

Note that this causes _worse_ vulnerabilities on old versions of Internet Explorer. For more, see [the documentation](https://helmetjs.github.io/docs/xss-filter/).

I'm 99% sure this solves your problem so I'm going to close this issue. Feel free to follow up in comments and let me know if I should reopen!
