### ISSUE TITLE
Remove hpkp from "mainline" Helmet

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#180]
See https://github.com/helmetjs/hpkp/issues/14.

Because this is a breaking change, it'll happen in Helmet version 4.

**Comment by FranklinYu** [comment]
FYI, Chrome has not yet removed support for HPKP as of version 70. They seems to have changed their plan.

**Comment by FranklinYu** [comment]
I don't think they publicly announced the change of plan, but you can test [this page](https://projects.dm.id.lv/Public-Key-Pins_test) with Chrome 70. For me it is still working, even if the deprecating message is still showing up claiming that it will be (should have been?) removed in 69.

**Comment by EvanHahn** [comment]
Hmm, interesting.

My plan is to do nothing until Chrome actually removes support. If they DON'T remove support, I'll reconsider its removal from "mainline" Helmet. If they DO remove support, I'll go ahead with its removal in Helmet 4.

Does that sound good to you?

**Comment by FranklinYu** [comment]
That's exactly what I would propose. 👍

**Comment by EvanHahn** [comment]
Perfect! Please let me know if you hear anything in the meantime.

**Comment by mkargus** [comment]
It appears that Chrome is removing it in [release 72](https://www.chromestatus.com/feature/5903385005916160).

**Comment by FranklinYu** [comment]
I can confirm with Chrome Dev (72).

**Comment by mkargus** [comment]
Chrome 72 is now released.

**Comment by EvanHahn** [comment]
I've updated the docs and added a deprecation warning to Helmet. This `helmet.hpkp` will be removed in Helmet 4.

**Comment by EvanHahn** [comment]
This was closed in #192 and merged into the `4.x` branch. I'm closing this because it will be released in Helmet 4 (though it's not technically released yet).
