### ISSUE TITLE
Add support for X-Content-Type-Options: nosniff header

### ISSUE THREAD

**Issue by nikwen** [helmetjs/helmet#181]
This seems to be a new feature in Chrome called Cross-Origin Read Blocking (CORB).

See https://developers.google.com/web/updates/2018/07/site-isolation for details.

**Comment by EvanHahn** [comment]
Helmet [already supports this header](https://helmetjs.github.io/docs/dont-sniff-mimetype/) with `helmet.noSniff`. It's enabled by default.

It _does_ sound like there's some work to be done to document this as part of CORB, though. Does that sound right?

**Comment by EvanHahn** [comment]
No worries! I just added some minor notes to both the `dont-sniff-mimetype` readme and the main Helmet docs site.

Thanks for reporting this!

**Comment by nikwen** [comment]
Awesome. Thank you for all your work, Evan, on this issue and in general! :wink:

**Comment by EvanHahn** [comment]
No problem! Thanks for your help reporting these.
