### ISSUE TITLE
DNS Rebinding protection

### ISSUE THREAD

**Issue by brannondorsey** [helmetjs/helmet#182]
Hi, I'm an independent security researcher and author of [`host-validation`](https://www.npmjs.com/package/host-validation), an NPM module for protecting Express.js servers from DNS rebinding attacks via host header validation. I've done a [fair amount of research on the subject](https://medium.com/@brannondorsey/attacking-private-networks-from-the-internet-with-dns-rebinding-ea7098a2d325) and I think DNS rebinding protection through header validation would be a perfect addition to helmet. I'm happy to spearhead this effort if there is interest. I'm willing to write a PR with updates to the lib, tests, and documentation, pending discussion. This is an amazing project and I'd like to contribute a small bit to make it even better.

**Comment by EvanHahn** [comment]
I didn't know about DNS rebinding—thanks for bringing it to my attention!

I've never been explicit about this, but I intend Helmet to be a middleware that deals with *response* headers, not request headers. Even though I'd argue that `Host` validation is more important than some of the headers Helmet sets, `Host` validation is a *request* header issue, and therefore out of this project's scope.

I think there are two action items for Helmet here:

1. After doing a quick audit of the code, recommend `host-validation` in the ["see also" section of Helmet's docs](https://helmetjs.github.io/see-also/).
2. Add documentation that makes Helmet's goal (HTTP *response* headers for Express) more explicit.

Does that sound reasonable?

**Comment by brannondorsey** [comment]
Throughout my research I've found many security folks aren't aware of DNS rebinding. You are not alone, haha ;) It's actually somewhat surprising to me how few folks know about it, especially considering it's been around for a decade and can be truly catastrophic. A lot of the work I've been doing in the last year is to simply raise awareness about the issue.

> I've never been explicit about this, but I intend Helmet to be a middleware that deals with response headers, not request headers.

Ah, I see. I wasn't aware of that restriction but I do now see that every header Helmet supports is indeed a response header. Would you mind elaborating a bit on why this distinction is important for Helmet? To me, it does seem like a bit of an arbitrary distinction, especially considering adding support for Host header validation could have a very positive real world outcome. As a brief aside, I think a lot folks out there really love and respect Helmet, and adding first-class support for DNS rebinding protection *with* the library could go a long way in raising awareness about the issue and lead to a lot more patched servers in the wild. That said, I imagine you have your reasons, especially considering you've obviously been invested in this library for a long time. I respect that a lot. 

As far as your suggestions, they do sound reasonable, even if I may disagree with the scope limitations. Let me know if I can be helpful in any of the processes moving forward!

**Comment by EvanHahn** [comment]
Helmet _could_ be expanded to more generic middleware collection for Express and "eat" things like SSL enforcement or CSRF tokens, but I've drawn the line here. I'm just one maintainer and still fall behind on some issues so a narrow focus is important. It is, as you say, a bit of an arbitrary decision.

If that makes sense, I'll move forward with the two action items I mentioned above.

**Comment by EvanHahn** [comment]
Sounds good! I'll make pull requests for these changes and @-mention you on both.

**Comment by EvanHahn** [comment]
Closing this issue now that I've addressed the action items. Thanks for bringing this to my attention!
