### ISSUE TITLE
Add support for `Report-To` header

### ISSUE THREAD

**Issue by Cherry** [helmetjs/helmet#184]
References: https://docs.report-uri.com/setup/reporting-api/
https://www.w3.org/TR/reporting/

The header essentially extends browser reporting from CSP, HPKP, etc. and adds things like deprecation, intervention and crash reporting.

Is this a good use-case for Helmet? Whilst the header itself isn't explicitly tied to security, it could alert site owners of security problems or issues with their visitors browsers/network configuration, especially in the `intervention` reports.

**Comment by EvanHahn** [comment]
Apologies for my slow response here. I need to take a look at this header to evaluate whether it'd be good for Helmet.

**Comment by EvanHahn** [comment]
Because this header isn't tied to security, I don't think this is a good candidate for Helmet. However, I'm more than happy to collaborate on a module that does this. Would you be interested in something like that?

Here's a quick draft (not tested):

```js
/* Usage:
 *
 * app.use(reportTo({
 *   groups: [
 *     {
 *       name: 'endpoint-1',
 *       maxAge: 10886400,
 *       endpoints: [
 *         {url: 'https://example.com/reports'}
 *       ]
 *     }
 *   ]
 * }))
 *
 */

module.exports = function reportTo (options) {
  // TODO: Add argument validation

  var headerValue = options.groups.map(function (group) {
    return JSON.stringify({
      group: group.name,
      max_age: group.maxAge,
      endpoints: group.endpoints
    })
  }).join(',')

  return function reportTo (req, res, next) {
    res.setHeader('Report-To', headerValue)
    next()
  }
}
```

**Comment by Cherry** [comment]
Yeah, I'd definitely be interested in something like that. I'm doing a similar thing as per your example in a few projects right now, and isolating it to an npm module would be a good idea.

**Comment by EvanHahn** [comment]
Sounds good! Feel free to email me@evanhahn.com if I can help at all.

**Comment by EvanHahn** [comment]
Fantastic! Let me know if I can help with either of those and I'll see if I have a spare moment.
