### ISSUE TITLE
Show how to use helmetjs without express

### ISSUE THREAD

**Issue by lukasoppermann** [helmetjs/helmet#185]
Hey, I think it would be awesome if helmetjs would be more open for other frameworks (or use without any).

As far as I understand, this is already possible (https://github.com/helmetjs/helmet/issues/100), correct? I think it would be good to document this prominently in the repo.

**Comment by EvanHahn** [comment]
This is totally possible. Are you interested in using it with "vanilla" Node (eg, its `http` module)? Or another framework like `connect` or `hapi`?

If so, here's something to help you out before it goes into the documentation:

```javascript
const applyHelmetHeaders = helmet()

http.createServer((req, res) => {
  applyHelmetHeaders(req, res, err => {
    // ...
  })
})
```

**Comment by EvanHahn** [comment]
@lukasoppermann Any updates here?

**Comment by lukasoppermann** [comment]
Hey, sorry it seems I did not hit send on my answer.

I am more interested in piecing together sometime from modules using the express router though. Mainly I need something that supports http/2 but I am using express currently and don't want to get locked into a different framework

**Comment by EvanHahn** [comment]
Helmet works with [Connect](https://github.com/senchalabs/connect), a lower-level middleware library than Express. You can use it just like you'd use it with Express.

You also asked for "vanilla" docs. Does the example above help?

**Comment by EvanHahn** [comment]
Okay. This isn't going to be a high-priority issue for me (I suspect that the vast majority of Helmet's users use it with Express) but I'll get to it at some point.

**Comment by EvanHahn** [comment]
Finally got around to this and put it in a wiki page, ["How to use Helmet without Express"](https://github.com/helmetjs/helmet/wiki/How-to-use-Helmet-without-Express).

I'm going to close this issue because I think I've addressed your issue, but feel free to comment further.
