### ISSUE TITLE
Any plan on adding ESlint to the source code?

### ISSUE THREAD

**Issue by ohpyupi** [helmetjs/helmet#186]
Curious if ESLint integration is welcomed to the repo

**Comment by EvanHahn** [comment]
Helmet uses Standard for linting (which uses ESLint under the hood). Does that help?

**Comment by ohpyupi** [comment]
I see. Didn't know about that. Thanks.

**Comment by EvanHahn** [comment]
No worries! Feel free to open a new issue if you have any other questions.
