### ISSUE TITLE
Error: "'unsafe-inline'" does not make sense in connect-src. Remove it.

### ISSUE THREAD

**Issue by jungalwala** [helmetjs/helmet#187]
I am getting the following error when I see add 'unsafe-inline' to connect-src.

> Error: "'unsafe-inline'" does not make sense in connect-src. Remove it.
> at /app/node_modules/helmet/node_modules/helmet-csp/lib/check-options/check-directive/source-list.js:32:13
> 

But according this the page below it is valid.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src

**Comment by GusRuss89** [comment]
The same thing happens with `styleSrc`. MDN says it's available - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

In my case I'm using a CSS-in-JS library that adds `<style>` tags. My main JS script has a nonce, but it's a pain to add it to each `<style>` tag (doable, but I thought this option would be easier until I ran into this issue).

The error:
```UnhandledPromiseRejectionWarning: Error: "'strict-dynamic'" does not make sense in style-src. Remove it.
    at /[projectpath]/node_modules/helmet-csp/lib/check-options/check-directive/source-list.js:32:13```

**Comment by EvanHahn** [comment]
Thanks, this seems like I made a mistake.

If anyone feels like making a pull request, feel free—otherwise I'll give it a shot when I next get the chance.

**Comment by EvanHahn** [comment]
Would one of you be able to close this issue and open a new one on the proper sup-repository, `csp`? [Here's a link to do that.](https://github.com/helmetjs/csp/issues/new)

**Comment by EvanHahn** [comment]
Opened https://github.com/helmetjs/csp/issues/82. Let's move discussion there.
