### ISSUE TITLE
Multiple value for referrerPolicy 

### ISSUE THREAD

**Issue by nayaabkhan** [helmetjs/helmet#191]
It is possible to have multiple `referrer-policy` as per the spec: https://w3c.github.io/webappsec-referrer-policy (Example 13).

What is the way to achieve this with Helmet.js? I tried to:
```js
app.use(
  helmet({
    referrerPolicy: {
      policy: 'no-referrer, strict-origin-when-cross-origin',
    },
  })
)
```

But it resulted in an error:
```
Error: "no-referrer, strict-origin-when-cross-origin" is not a valid policy. Allowed policies: "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url", and the empty string.
```

Docs don't mention any way to specify multiple values either.

**Comment by EvanHahn** [comment]
This looks like an issue with the `referrer-policy` middleware, so I've moved the issue there. See <https://github.com/helmetjs/referrer-policy/issues/7>.

Thanks for reporting.
