### ISSUE TITLE
Feature Policy: Disable all?

### ISSUE THREAD

**Issue by Bramzor** [helmetjs/helmet#193]
Documentation describes how to disable or configure specific features but I was wondering why wouldnt we just disable all and enable only the items we need? Or am I missing something?

**Comment by EvanHahn** [comment]
To quote [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy):

> If you do not specify a policy for a feature, then a default allowlist will be used. The default allowlist is specific to each feature.

A "disable everything" feature is an interesting idea...I assume that's something you'd be interested in?

**Comment by Bramzor** [comment]
Do we know the content of this default allowlist?
Yes, I would prefer to actually disable everything as on a normal website or service you do not need anything like camera, micro, geolocation etc. And per security best practices, it's always better to deny as much as possible. Although I tried disabling vibrate yesterday and apparently Chrome (desktop) was unaware of this feature so it started showing warnings. This might be a reason to not disable everything.

**Comment by EvanHahn** [comment]
I'm not sure, but another quote from MDN:

> For each policy-controlled feature, the browser maintains a list of origins for which the feature is enabled, known as an allowlist.

[The spec mentions default allowlists](https://w3c.github.io/webappsec-feature-policy/#default-allowlists), but it doesn't give specifics.

Unfortunately, I don't know of a great way to disable everything without giving those warnings. If there are any features that the browser doesn't recognize, it will give a warning (I assume, I haven't tested every browser).

**Comment by Bramzor** [comment]
There is a post talking about a possible default feature: https://github.com/w3c/webappsec-feature-policy/issues/189 . Apparently the allowlist is configured and configurable in the browser.

**Comment by EvanHahn** [comment]
Let's keep an eye on that issue. Thanks for finding!

**Comment by EvanHahn** [comment]
Let's move this discussion to https://github.com/helmetjs/feature-policy/issues/6.
