### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [helmetjs/helmet#207]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

I'm not familiar with your project, I'm just looking through a list of projects that depend on `feross/funding`. It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by EvanHahn** [comment]
This shouldn't affect Helmet users (because `funding` is a development-only subdependency), so I'm going to close this issue.

Let me know if you disagree with this decision and I'm happy to reopen.
