### ISSUE TITLE
Content Security Policy example code does no work. 

### ISSUE THREAD

**Issue by louguitar** [helmetjs/helmet#208]
Hi, 
I have a site build in Node/Express and I am trying to get around the Content Security Policy that blocks all inline scripts. I have used the example code at the [bottom of this page](https://helmetjs.github.io/docs/csp/). However it all works, it generates the nonce, the header is showing up properly, but as soon as I get to the last line of code, where it is supposed to inject the nonce into all the script tags, it just spits out that individual <script> tag onto a blank HTML page. It will not load my site anymore. 

Here is the code I get: 
![Screen Shot 2019-08-29 at 3 21 04 PM](https://user-images.githubusercontent.com/1406147/63977291-ada60f80-ca70-11e9-9e55-1032d5114c7b.png)

And here are the console errors I am getting: 
![Screen Shot 2019-08-29 at 3 22 35 PM](https://user-images.githubusercontent.com/1406147/63977382-efcf5100-ca70-11e9-91bd-39224e51e19e.png)

Has anyone else had this problem?

**Comment by EvanHahn** [comment]
Hmm, seems odd. Could you post the following?

1. Your call to `csp` (and any code that generates the nonce)
1. The code that renders the `<script>` tag
1. The final `Content-Security-Policy` header (from the Network tab in your browser)

**Comment by EvanHahn** [comment]
There hasn't been an update in this issue for some time so I'm going to close it. Let me know if you want me to reopen!
