### ISSUE TITLE
Exporting TypeScript types

### ISSUE THREAD

**Issue by benhjames** [helmetjs/helmet#209]
Whilst migrating the main `helmet` package over to TypeScript, I discovered an issue to do with exporting types:

```
Property 'dnsPrefetchControl' of exported interface has or is using name 'DnsPrefetchControlOptions' from private module '"./node_modules/dns-prefetch-control/dist/index"'.
```

In this example, I believe the `DnsPrefetchControlOptions` type needs to be exported in the main module definition. However, because we are using CJS exports, we cannot simply prefix the type definition with `export` (as there can only be a single export). Instead, the [suggested way](https://stackoverflow.com/questions/48708410/typescript-error-an-export-assignment-cannot-be-used-in-a-module-with-other-exp) is to use namespaces:

```ts
/* eslint-disable @typescript-eslint/no-namespace */
namespace dnsPrefetchControl {
  export interface DnsPrefetchControlOptions {
    /* ... */
  }
}

// eslint-disable-next-line no-redeclare
function dnsPrefetchControl (options: dnsPrefetchControl.DnsPrefetchControlOptions = {}) {
  /* ... */
}
```

In the interest of preserving CJS exports, does this seem like a reasonable way for now? In the future, we can make a breaking change to use ES modules everywhere which would make things a lot nicer, but this change would at least make it possible to migrate this module to TypeScript. 👍

**Comment by EvanHahn** [comment]
I'm getting ready to make breaking changes (for Helmet 4). I'd like to be able to support the following cases:

- CommonJS imports in Node (eg, `helmet = require('helmet')`)
- ES modules where shimmed (eg, `import helmet from 'helmet'`), like in TypeScript

Are those mutually exclusive?

**Comment by EvanHahn** [comment]
To add some additional info, Node has an official recommendation [not to publish ES modules right now](https://github.com/nodejs/modules/blob/master/doc/announcement.md#es-module-code-in-packages). I'd like to follow that recommendation for now.

**Comment by benhjames** [comment]
I think there are two ways of supporting the two cases above whilst following the Node recommendation, and also being able to export types:

1. Use namespaces (as described above). Not a breaking change for consumers, but namespaces are a TypeScript-only concept and are discouraged/deprecated in favour of using ES modules.

2. Write the source as ES modules, which get transpiled to CJS modules, for example:
```js
export default dnsPrefetchControl;
```

is compiled to...

```js
exports.default = dnsPrefetchControl;
```

This means consumers of helmet would need to write:

```js
const helmet = require('helmet').default;
```

... and is therefore a breaking change.

If we're planning on making breaking changes, personally I'd opt for the second method as it future-proofs for when ES modules are fully supported, whilst keeping the ability to use helmet in the CJS world. Interested to hear your thoughts!

**Comment by EvanHahn** [comment]
While I'd prefer the latter option in the future where ES Modules are widely used, I'm hesitant to require their usage (so to speak) given that Node basically recommends that we don't use them yet.

Is there a way to have all of these things work?

```js
const helmet = require('helmet')
const helmet = require('helmet').default
import helmet from 'helmet'
```

**Comment by benhjames** [comment]
Since we'd be authoring in ESM and compiling to/distributing in CJS I'm not sure the Node recommendation concerns us. Consumers of the package could still use CJS if required (pun not intended), though they would need to access the default export via `.default`.

> Is there a way to have all of these things work?

I believe there is only one way for `const helmet = require('helmet')` to work without `.default` on the end: by using `export =` in TypeScript like we do at present. However, this makes it tricky to export multiple things, like types, without utilising namespaces - hence this discussion! 👍

**Comment by EvanHahn** [comment]
Ah, okay, I think that all makes sense to me now.

Given that...

1. `helmet@4` is going to support all the way down to Node 8
1. Node 8 doesn't support ES modules natively (without a flag, at least)
1. I want to prioritize native, no-transpilation setups over setups that require a transpiler (TypeScript or otherwise)

I think we should use `export =` like we do now. If that means we have to use deprecated TypeScript namespaces, that's okay with me. It's not ideal, but based on the givens above (which we could certainly debate), I think that's the only option.

Does that sound right?

**Comment by benhjames** [comment]
Yes, makes sense! Let's go with that. I'll have a look at starting to fix up the individual packages over the coming days.

**Comment by ketan-shinde** [comment]
how to implement in angular 7 step by step?

**Comment by EvanHahn** [comment]
@ketan-shinde Let's answer your question in #213.

**Comment by EvanHahn** [comment]
I did some exploring today and I think there's another option that may work for TypeScript users: the `Parameters` type. Here's a sketch of what I came up with (emphasis on the fact that it's a sketch):

```typescript
import contentSecurityPolicy = require('helmet-csp')
import dnsPrefetchControl = require('dns-prefetch-control')
import expectCt = require('expect-ct')
import featurePolicy = require('feature-policy')
import frameguard = require('frameguard')
import hidePoweredBy = require('hide-powered-by')
import ieNoOpen = require('ienoopen')
import noSniff = require('dont-sniff-mimetype')
import permittedCrossDomainPolicies = require('helmet-crossdomain')
import referrerPolicy = require('referrer-policy')
import xssFilter = require('x-xss-protection')
import * as http from 'http';

type Middleware = (options?: {}) => (req: http.IncomingMessage, res: http.ServerResponse, next: () => void) => void;

type SubmoduleOptions<T extends Middleware> = boolean | Parameters<T>[0];

interface HelmetOptions {
  contentSecurityPolicy?: false | Parameters<typeof contentSecurityPolicy>[0];
  dnsPrefetchControl?: SubmoduleOptions<typeof dnsPrefetchControl>;
  expectCt?: SubmoduleOptions<typeof expectCt>;
  featurePolicy?: false | Parameters<typeof featurePolicy>[0];
  frameguard?: SubmoduleOptions<typeof frameguard>;
  hidePoweredBy?: SubmoduleOptions<typeof hidePoweredBy>;
  hsts?: SubmoduleOptions<typeof hsts>;
  ieNoOpen?: SubmoduleOptions<typeof ieNoOpen>;
  noSniff?: SubmoduleOptions<typeof noSniff>;
  permittedCrossDomainPolicies?: SubmoduleOptions<typeof permittedCrossDomainPolicies>;
  referrerPolicy?: SubmoduleOptions<typeof referrerPolicy>;
  xssFilter?: SubmoduleOptions<typeof xssFilter>;
}

function helmet (options: HelmetOptions = {}) {
  // ...
}

helmet.contentSecurityPolicy = contentSecurityPolicy;
// ...

export = helmet
```

@benhjames What do you think about this?

**Comment by benhjames** [comment]
I think this has the same issue as in the original post (I too was going in the direction of using the `Parameters` type!)

**Comment by EvanHahn** [comment]
I was able to get this to type-check when I tried it (though I'd want to verify that it totally works). What problems did you run into when using `Parameters`?

**Comment by EvanHahn** [comment]
TypeScript types were added to Helmet in version 4, which you can install with `npm install helmet@4`. Closing this issue because I believe this is resolved, but feel free to comment or open a new issue.
