### ISSUE TITLE
Redirect request

### ISSUE THREAD

**Issue by Georgeevergreen0** [helmetjs/helmet#210]
Why does helmet redirect users/logout to /

**Comment by EvanHahn** [comment]
Could you provide a code sample that reproduces this issue?

**Comment by jamilservicos** [comment]
@EvanHahn 
example fail:
```
const nanoexpress = require('nanoexpress');
const app = nanoexpress();
app.use(require('helmet')({
    hidePoweredBy: { setTo: 'test' }
}));
app.get('/', (req,res) => {
    res.redirect('/login.html');
});
```

example work:
```
const nanoexpress = require('nanoexpress');
const app = nanoexpress();
app.get('/', (req,res) => {
    res.redirect('/login.html');
});
```

**Comment by EvanHahn** [comment]
How does that fail? Does it not redirect, or does it give an error?

**Comment by Georgeevergreen0** [comment]
const helmet = require("helmet");
const app = express();
const indexRouter = require('./routers/users');
app.use(helmet());
app.use(function (req, res, next){
console.log(req.url )//when i visit user/logout it logs "/". if i comment out helmet it works normally
});
