### ISSUE TITLE
npm not published correctly?

### ISSUE THREAD

**Issue by BechtelCanDoIt** [helmetjs/helmet#212]
scott@MegaDev:...$ npm i helment --save
npm ERR! code E404
npm ERR! 404 Not Found: helment@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scott/.npm/_logs/2019-10-26T21_16_14_139Z-debug.log

---

I also tried helment@3.21.1 and .0 same 404.

---
scott@MegaDev:~/dev/serverless/mindarchitecting/Hypno_BE_MindArchitecting$ more /home/scott/.npm/_logs/2019-10-26T21_16_14_139Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/scott/.nvm/versions/node/v8.12.0/bin/node',
1 verbose cli   '/home/scott/.nvm/versions/node/v8.12.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   'helment',
1 verbose cli   '--save' ]
2 info using npm@6.5.0
3 info using node@v8.12.0
4 verbose npm-session 40f14e9c53a3fef6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/helment 1264ms
8 silly fetchPackageMetaData error for helment@latest 404 Not Found: helment@latest
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 1551ms
11 verbose stack Error: 404 Not Found: helment@latest
11 verbose stack     at fetch.then.res (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
11 verbose stack     at _drainQueueStep (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
11 verbose stack     at _drainQueue (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
11 verbose stack     at Async._drainQueues (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues (/home/scott/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:810:20)
11 verbose stack     at tryOnImmediate (timers.js:768:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
12 verbose cwd /home/scott/dev/serverless/projectname
13 verbose Linux 4.15.0-65-generic
14 verbose argv "/home/scott/.nvm/versions/node/v8.12.0/bin/node" "/home/scott/.nvm/versions/node/v8.12.0/bin/npm" "i" "helment" "--save"
15 verbose node v8.12.0
16 verbose npm  v6.5.0
17 error code E404
18 error 404 Not Found: helment@latest
19 verbose exit [ 1, true ]

**Comment by EvanHahn** [comment]
It looks like you’re trying to install helment, not helmet. Are you sure you’ve spelled it correctly?

**Comment by BechtelCanDoIt** [comment]
OMG spelling gets me every time. Nothing to see here folks...

**Comment by EvanHahn** [comment]
No problem—easy mistake to make!

Feel free to open a new issue if you run into any other problems.
