### ISSUE TITLE
how to implement in angular 7 step by step?

### ISSUE THREAD

**Issue by ketan-shinde** [helmetjs/helmet#213]
Can you explain? How to implement in angular 7 step by step?

**Comment by EvanHahn** [comment]
I don't know much about Angular. What help do you need?

**Comment by victor-perez** [comment]
@ketan-shinde I understand from the documentation https://angular.io/guide/universal that Angular SSR uses normal Express server so in that case it will be
```js
import * as helmet from 'helmet';
app.use(helmet())
```
in your `server.ts`

**Comment by EvanHahn** [comment]
This issue has been open for months and I *think* it's been resolved, so I'm going to close. Let me know if you want me to reopen this or continue the discussion!

**Comment by BruneXX** [comment]
Hi @victor-perez I know this task is closed @EvanHahn but I was realized that victor used helmetjs in his example, is there any constraint to use helmetjs in angular universal? also, will be a good practice? I can't found any informaton related to that. Thanks.

**Comment by EvanHahn** [comment]
I'm not aware of such a constraint but am unfamiliar with Angular Universal. I'm going to leave this issue closed but anyone can feel free to chime in.
