### ISSUE TITLE
Issue with Helmet and Express 4.17

### ISSUE THREAD

**Issue by teodem** [helmetjs/helmet#218]
Hi guys,
for a university project we are currently completing a web-app (we are using Express).
As I'm interested in the security issue, I wanted to make sure that our app is safe with Helmet.
Unfortunately, despite referring to the documentation, it doesn't seem to work.
The headers are exactly the same, without any variation.

<img width="791" alt="Schermata 2020-05-19 alle 11 20 14" src="https://user-images.githubusercontent.com/19976303/82308963-cbcaeb80-99c2-11ea-9d1d-ce45acc880a3.png">
I'm probably using Helmet not the right way, or could it be a limitation of this tool?

I also attach the App.ts file

[app.ts.zip](https://github.com/helmetjs/helmet/files/4649417/app.ts.zip)

**Comment by EvanHahn** [comment]
I suspect this is an issue with your Express server and not Helmet, but let's try to debug.

I see `X-Powered-By: Express` in your response headers. Helmet disables that header by default, but you also seem to disable it on line 36 of the code you attached:

```typescript
this.app.disable('x-powered-by');
```

That makes me think that this isn't a problem with Helmet, but a problem with how your app is being used. (I also think I'd be getting other issues about this problem.)

Is it possible that this app isn't being used correctly elsewhere in your app?

**Comment by EvanHahn** [comment]
I haven't heard back about this in a week and I don't think this is a problem with Helmet, so I'm going to close. Let me know if that's a problem—I'm happy to reopen.
