### ISSUE TITLE
Fetch Metadata Browser Headers

### ISSUE THREAD

**Issue by ThunderSon** [helmetjs/helmet#223]
# Feature Request

## Is the header supported by any user agent? If so, which?

Chrome v76 and chromium-based browsers v79. Firefox is working to release this soon.

## What does it do?

It's a resource isolation policy that the browser sends to the server in order to provide more context and allow the server to allow or deny the content access. Attacks such as CSRF, XSSI, XS-leaks, etc. will be much harder to pull once the server knows what the user-agent is allowing and expecting.

## What are the headers for this policy?

- Sec-Fetch-Site: ['same-origin', 'same-site', 'none', 'cross-site']
- Sec-Fetch-Mode: ['same-origin', 'no-cors', 'cors', 'navigate']
- Sec-Fetch-Dest: the destination of the returned content (_e.g._ image)

## Where does the specification live?

https://www.w3.org/TR/fetch-metadata/
I'd recommend reading the following article before checking the specification:
https://web.dev/fetch-metadata/

CC: @lweichselbaum
@EvanHahn I created a similar issue over at [secure_headers](https://github.com/github/secure_headers) project under issue 441 if you'd want the chat to occur with both teams.

**Comment by EvanHahn** [comment]
Helmet is only concerned with HTTP *response* headers, so I believe these headers are out of scope. If that's incorrect, let me know and I'll reopen this issue.

I'm happy to take a look at an Express package that deals with this, if that review would be helpful.

**Comment by ThunderSon** [comment]
That's true. These are headers that the browser will receive (such as origin, host, etc.). Thank you for pointing that out!

Would you be able to guide me into the appropriate party that help with this?
Thanks @EvanHahn 😄

**Comment by EvanHahn** [comment]
Not sure. But if you'd like help on an Express module, let me know and I can take a look.
