### ISSUE TITLE
X-XSS-Protection: header should be disabled by default

### ISSUE THREAD

**Issue by ThunderSon** [helmetjs/helmet#230]
Following a decision by Google Chrome developers to disable Auditor, developers should be able to disable the auditor for older browsers and set it to `0`.
The `X-XSS-PROTECTION` header was found to have a multitude of issues, instead of helping the developers protect their application.
The following discussion describes the issue at hand with more references: https://github.com/OWASP/CheatSheetSeries/issues/376
A PR is currently open to tackle the issue at the CheatSheet Series project: https://github.com/OWASP/CheatSheetSeries/pull/378

If approved, we can help with creating a PR for this issue.
Available for further discussions 😄

**Comment by EvanHahn** [comment]
This has been added to Helmet v4, which I plan to release this Sunday, 2020-08-02.

You can install the release candidate with `npm install helmet@next` if you want to try it out.

**Comment by EvanHahn** [comment]
Helmet v4 (and `x-xss-protection@2`) was just released, which disables this header.

Thanks for reporting and for discussing this with me.

**Comment by RezaRahmati** [comment]
@EvanHahn Hi Evan, I am using helmet: 4.4.1, still getting `x-xss-protection: 0` on response, based on your comment seems it should be `1` by default, right?

**Comment by EvanHahn** [comment]
@RezaRahmati It should be set to `0` in Helmet v4, so what you're seeing is expected.

**Comment by AdamSadek** [comment]
> @EvanHahn Hi Evan, I am using helmet: 4.4.1, still getting `x-xss-protection: 0` on response, based on your comment seems it should be `1` by default, right?
> 
> Or how can I change the behavior, there is no option in helmet.xssFilter to change the options

You can completely remove it from the response by setting `xssFilter: false`. For example:
`app.use(helmet(xssFilter: false))`
