### ISSUE TITLE
Permissions-Policy

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#234]
The `Feature-Policy` header has been deprecated in favor of `Permissions-Policy` and `Document-Policy`. I think it's too early to decide what Helmet should do with these headers, but I wanted to make an issue to track it.

See <https://github.com/helmetjs/feature-policy/issues/10> for a little more discussion.

**Comment by Hongbo-Miao** [comment]
Just added the reference for "Feature-Policy header has been renamed to Permissions-Policy" here.

Had a hard time to find it. Saving some time for future people.

https://w3c.github.io/webappsec-permissions-policy/#introduction

<img width="898" alt="image" src="https://user-images.githubusercontent.com/3375461/89116272-86e42a80-d4c4-11ea-90d3-7b7e527a6568.png">

**Comment by Cherry** [comment]
It seems like `Permissions-Policy` is the more direct successor to `Feature-Policy`, and as announced today by Scott Helme, will be the header that is looked for on https://securityheaders.com/ very soon.

https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

[`Document-Policy`](https://github.com/w3c/webappsec-permissions-policy/blob/master/document-policy-explainer.md) seems to be another great addition though, more tailored towards configuration features on a specific origin, rather than features that require a "permission". Seeing support for both of these headers in an upcoming Helmet version would be fantastic.

**Comment by EvanHahn** [comment]
@Cherry Thanks for the update here. Based on this, I'm going to do a few things (nothing too big):

- Create a new issue for `Document-Policy` (#258)
- Update this issue to be about `Permissions-Policy`, specifically

[Browser support for `Permissions-Policy` is basically nil](https://www.caniuse.com/permissions-policy), but I'll keep an eye on this as the header is rolled out. It'll almost certainly be disabled in Helmet by default.

For now, here's a simple example showing how to use `Permissions-Policy` with Express:

```js
app.use((req, res, next) => {
  res.setHeader(
    "Permissions-Policy",
    'geolocation=(self "https://example.com"), microphone=()'
  );
  next();
});
```

**Comment by jimjaeger** [comment]
@EvanHahn More and more browers support permission policy header. Any plans to migrate the helmet feature-policy package into the helmet base and update the header to Permissions-Policy? Seems people going forward and forked your project https://github.com/pedro-gbf/permissions-policy.

When you update the package, could you add googles interest-cohort https://github.com/WICG/floc#opting-out-of-computation aswell? :)

**Comment by EvanHahn** [comment]
Permissions-Policy still [appears to be an "editor's draft"][0], and is [only supported in Chromium-based browsers][1] (Chrome and Edge). Firefox [eventually intends to add support][2] but it's not available yet.

In the past, I've added support for headers to Helmet too soon and later regretted it, so I don't think I'll be adding support for Permissions-Policy to "mainline" Helmet yet.

However, I'll continue to keep an eye on this header and see if I can help out with [the fork](https://github.com/pedro-gbf/permissions-policy).

[0]: https://w3c.github.io/webappsec-permissions-policy/
[1]: https://www.caniuse.com/permissions-policy
[2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1694922#c2

**Comment by Flawe** [comment]
With the recent FLoC stuff from google, it might be useful to get this feature in so people can disable that tracking stuff.

 https://plausible.io/blog/google-floc#how-to-opt-out-of-floc-as-a-web-developer-set-a-permissions-policy

**Comment by EvanHahn** [comment]
I'm not yet ready to add Permissions Policy support to Helmet. The specification is still in flux.

For now, here are some options:

- Write a very simple middleware yourself. Here's an example:

  ```js
  app.use((req, res, next) => {
    res.setHeader(
      "Permissions-Policy",
      "geolocation=(), interest-cohort=()"
    );
    next()
  })
  ```

- Install the [permissions-policy package][0]. This package is not maintained by me but is a fork of a Helmet module and I have contributed a few changes.   This package, or something like it, may eventually be included in a future Helmet version.
- If your only goal is to block FLoC, I just published the [floc-block package][1] and [a blog post showing how to disable it][2].

Hope this helps!

[0]: https://github.com/pedro-gbf/permissions-policy
[1]: https://gitlab.com/EvanHahn/floc-block
[2]: https://evanhahn.com/block-googles-floc-tracking-with-express

**Comment by alfasin** [comment]
Any chance that Permissions-Policy header will be added in the future?

**Comment by EvanHahn** [comment]
Because [the specification](https://www.w3.org/TR/permissions-policy-1/) is still in a draft state, I don't intend to add support to Helmet yet. I don't want to have to make breaking changes to Helmet just because the specification has changed.

However, [my comment above](https://github.com/helmetjs/helmet/issues/234#issuecomment-821881561) outlines a number of options for setting this header yourself, or with other modules.

**Comment by JosephScript** [comment]
This package works for me. https://github.com/pedro-gbf/permissions-policy

**Comment by EvanHahn** [comment]
I'm planning the next major version of Helmet, version 5.

Because the `Permissions-Policy` spec is still a draft and [it's only supported in Chrome right now](https://caniuse.com/document-policy), I do not plan to add this as a default in Helmet 5.

That doesn't mean I don't plan to add it, just that it won't be enabled by default in the next major version. I'm removing the v5.0.0 milestone. Let me know if you disagree!

As I mentioned before, [you can easily set this header yourself](https://github.com/helmetjs/helmet/issues/234#issuecomment-821881561) if you need it.

**Comment by EvanHahn** [comment]
It's been almost two years since this issue was opened and the specification is still in a draft state. I don't think there's anything actionable here, so I'm going to close this issue.

_If you want to set this header_ despite this, you can! Here's an example:

```js
app.use((req, res, next) => {
  res.setHeader("Permissions-Policy", "geolocation=(), interest-cohort=()");
  next();
});
```

Alternatively, you can try the [permissions-policy package][0]. It is not maintained by me, but is a fork of a Helmet module and I have contributed a few changes.

If your only goal is to block FLoC, I just published the [floc-block package][1] and [a blog post showing how to disable it][2].

If `Permissions-Policy` makes it out of draft or gains wider browser support, I'm happy to reconsider this decision. For now, I'm going to close this issue to clean up the repository.

[0]: https://github.com/pedro-gbf/permissions-policy
[1]: https://gitlab.com/EvanHahn/floc-block
[2]: https://evanhahn.com/block-googles-floc-tracking-with-express

**Comment by kgrosvenor** [comment]
I would have expected this to be added, or a way to pass to helmet additional headers to set?

**Comment by EvanHahn** [comment]
@kgrosvenor Thanks for the ping. Because the header is still in a draft state and is unsupported by Firefox, [my comment above still stands](https://github.com/helmetjs/helmet/issues/234#issuecomment-1166305952). My small code snippet or the [permissions-policy package](https://github.com/pedro-gbf/permissions-policy) should be able to help here.
