### ISSUE TITLE
Expression is not callable in 4.0.0

### ISSUE THREAD

**Issue by MarluanEspiritusanto** [helmetjs/helmet#236]
After updating to 4.0.0 version the helmet middleware configuration throws an error:

```
This expression is not callable.
 Type 'typeof import("/node_modules/helmet/dist/index")' has no call signatures.ts(2349)
```

This is the code Im trying to run:

```javascript
import * as helmet from 'helmet';
import * as express from "express";

const app = express();

// express middleware configuration
app.use(helmet())
```

**Comment by EvanHahn** [comment]
What does your `tsconfig.json` look like, if you can share it?

**Comment by MarluanEspiritusanto** [comment]
@EvanHahn Here it is
```json
{
  "compilerOptions": {
    "paths": {
      "@modules/*": ["./src/modules/*"],
      "@database/*": ["./src/database/*"],
      "@common/*": ["./src/common/*"],
      "@utils/*": ["./src/utils/*"]
    },
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}
```

**Comment by EvanHahn** [comment]
Would you be willing to enable `esModuleInterop`, if that fixes your problem?

**Comment by Hongbo-Miao** [comment]
Seems like a TypeScript config issue.

I just upgrades to helmet 4.0.0, the code is at https://github.com/Hongbo-Miao/hongbomiao.com/blob/master/server/src/middlewares/helmet.middleware.ts
tsconfig.json is at https://github.com/Hongbo-Miao/hongbomiao.com/blob/master/server/tsconfig.json

Hopefully it helps.

**Comment by joshuajung** [comment]
I'm facing the same issue, and unfortunately `esModuleInterop` does not seem to fix it - still getting the `no call signatures` error. My full tsconfig.json, with TS 3.9.7:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "incremental": true,
    "strict": true,
    "esModuleInterop": true,
  },
  "exclude": ["node_modules", "dist"]
}
```

**Comment by anthony-telljohann** [comment]
I was able to resolve this by ignoring typescript errors before using `helmet`

```typescript
import * as helmet from 'helmet'
...
// @ts-ignore
app.use(helmet(helmetConfig))
```

I believe this is because the default `helmet` export has an incorrectly defined type.

**Comment by EvanHahn** [comment]
I'd like to fix the Helmet types.

Helmet is a CommonJS module (in other words, it uses `module.exports` and not `export ...`). Therefore, without `esModuleInterop`, I would expect users to do something like this:

```typescript
import helmet = require("helmet");
```

Though I'm not an expert at how TypeScript modules work.

**Comment by EvanHahn** [comment]
This issue looks the same as #235, so I'm going to close this issue and move discussion there.
