### ISSUE TITLE
CSP: report-to option

### ISSUE THREAD

**Issue by UziTech** [helmetjs/helmet#238]
Is there a way to add a [`report-uri`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri) or [`report-to`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to) with [`report-endpoints`](https://w3c.github.io/reporting/#header) header?

It looks like `report-uri` is deprecated in favor of `report-to` but Firefox and Safari don't support `report-to` yet.

**Comment by EvanHahn** [comment]
I'm unfamiliar with the `Reporting-Endpoints` header, but would something like this work for you?

```js
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        // ...
        reportUri: ["/path/to/report/uri"],
        reportTo: ["csp-endpoint"],
      },
    },
  })
);

app.use((req, res, next) => {
  res.setHeader("Reporting-Endpoints", "HEADER VALUE HERE");
  next();
});
```

**Comment by UziTech** [comment]
It should probably be separate from the directives.

```js
app.use(
  helmet({
    contentSecurityPolicy: {
      reportUri: ["/path/to/report/uri"],
    },
  })
);
```

I'm unfamiliar with the `report-to` and `Reporting-Endpoints` as well. I just learned about them yesterday and it looks a little too new to be stable. In fact some of the examples i've seen show a [`Report-To` header](https://developers.google.com/web/updates/2018/09/reportingapi#header) instead of `Reporting-Endpoints`.

**Comment by UziTech** [comment]
Looks like the `Report-To` header was changed to `Reporting-Endpoints` because they take different types of values.

https://github.com/w3c/reporting/issues/177#issuecomment-532347492

**Comment by UziTech** [comment]
I guess maybe it should be in directives according to https://content-security-policy.com/

**Comment by UziTech** [comment]
will the code you provided work right now or are the directives hard coded?

**Comment by UziTech** [comment]
and is there a way to append directives or will I need to specify the defaults as well?

**Comment by EvanHahn** [comment]
In Helmet 4 (which was recently released), directives are not hard-coded. That means you can supply any directive you want and it should work.

I expect my code snippet will be a good starting point and should work for you, but I'm happy to help debug.

**Comment by EvanHahn** [comment]
I believe this issue has been solved so I'm going to close, but let me know if that's wrong and I will reopen.

**Comment by Hongbo-Miao** [comment]
Hi @UziTech check this early thread https://github.com/helmetjs/helmet/issues/184

and two `report-to` related packages mentioned inside:
https://www.npmjs.com/package/report-to
https://www.npmjs.com/package/network-error-logging

**Comment by UziTech** [comment]
Thanks @Hongbo-Miao Those packages seem to be exactly what I need :tada:
