### ISSUE TITLE
Remove the default `block-all-mixed-content;`?

### ISSUE THREAD

**Issue by Hongbo-Miao** [helmetjs/helmet#239]
Currently I saw in readme,

> If no directives are supplied, the following policy is set (whitespace added for readability):
> 
>     default-src 'self';
>     base-uri 'self';
>     block-all-mixed-content;
>     font-src 'self' https: data:;
>     frame-ancestors 'self';
>     img-src 'self' data:;
>     object-src 'none';
>     script-src 'self';
>     script-src-attr 'none';
>     style-src 'self' https: 'unsafe-inline';
>     upgrade-insecure-requests

However, based on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content

> The upgrade-insecure-requests directive is evaluated before block-all-mixed-content and if it is set, the latter is effectively a no-op. It is recommended to set either directive, but not both, unless you want to force HTTPS on older browsers that do not force it after a redirect to HTTP.

if I understand correctly, just wonder should we remove the default `block-all-mixed-content` since `upgrade-insecure-requests` is provided? Thanks!

**Comment by EvanHahn** [comment]
I'll look into this in the next few days.

**Comment by EvanHahn** [comment]
Because this is a breaking change (and not _clearly_ wrong to me), I don't plan to address this.

I'll revisit this default (and all defaults) in the next major version, and I'll keep this issue in mind. I don't expect to release a new major version in 2020, though plans can change.

Thanks for bringing this up, and feel free to open a new issue if you have any other feedback or run into any other problems.

**Comment by Hongbo-Miao** [comment]
Got it, thanks for looking into it, @EvanHahn !

**Comment by AdrianDC** [comment]
For reference, this is a configuration to avoid HTTP to HTTPS upgrades with the mentioned rules removed:
```
    // HTTP CSP (Content-Security-Policy) directives
    const directivesCSP = helmet.contentSecurityPolicy.getDefaultDirectives();
    // HTTP CSP compatibility: Remote access over HTTP
    delete directivesCSP['block-all-mixed-content'];
    delete directivesCSP['upgrade-insecure-requests'];

    // Configure express middlewares
    this.app.use(
      helmet({
        contentSecurityPolicy: {
          directives: directivesCSP
        }
      })
    );
```
