### ISSUE TITLE
Helmet has no call signature

### ISSUE THREAD

**Issue by Stegosource** [helmetjs/helmet#247]
I have some type checking setup on my project and I'm getting a weird linting error.

`const helmet: typeof import(".../node_modules/helmet/dist/index")`

With the error being:
```
This expression is not callable.
  Type 'typeof import(".../node_modules/helmet/dist/index")' has no call signatures.
```

So far I'm just getting around this by casting the type to `any`. That works fine, but thought I might point it out here.

**Comment by EvanHahn** [comment]
This looks like a TypeScript error that's being discussed in #235, so I'm going to close this issue.

You should be able to fix this in the next version which should be released soon. You can try it out today with `npm install helmet@4.1.0-rc.2`.

Hope this helps!

**Comment by Stegosource** [comment]
Oh yeah looks like it. Sorry, I did a search and nothing came up. Thanks for taking a look

**Comment by EvanHahn** [comment]
No worries at all. Feel free to open a new issue if anything else comes up, and I'd appreciate your feedback on the release candidate.
