### ISSUE TITLE
How to define contentSecurityPolicy() directives whilst still using other middlewares?  

### ISSUE THREAD

**Issue by oshihirii** [helmetjs/helmet#253]
Re:  https://www.npmjs.com/package/helmet

>  The top-level helmet function is a wrapper around 11 smaller middlewares.
>  In other words, these two things are equivalent:
```js
// This...
app.use(helmet());
 
// ...is equivalent to this:
app.use(helmet.contentSecurityPolicy());
app.use(helmet.dnsPrefetchControl());
app.use(helmet.expectCt());
app.use(helmet.frameguard());
app.use(helmet.hidePoweredBy());
app.use(helmet.hsts());
app.use(helmet.ieNoOpen());
app.use(helmet.noSniff());
app.use(helmet.permittedCrossDomainPolicies());
app.use(helmet.referrerPolicy());
app.use(helmet.xssFilter());
```
I recently replaced this piece of code in my app:
```js
app.use(helmet());
```
with:
```js
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'", "https://somedomain.com"],
      styleSrc: ["'self'", "fonts.googleapis.com", "'unsafe-inline'"],
      fontSrc: ["'self'", "fonts.gstatic.com"]
    }
  })
);
```
My question is:

Using my new implementation, are all the other middlewares still applied?

Or does my new code now *only* use 1 middleware? (ie `helmet.contentSecurityPolicy()`)

If so, how can i define directives for `helmet.contentSecurityPolicy()` whilst also *keeping* all the other middlewares being applied?

Do I just have to do this?
```js
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'", "https://somedomain.com"],
      styleSrc: ["'self'", "fonts.googleapis.com", "'unsafe-inline'"],
      fontSrc: ["'self'", "fonts.gstatic.com"]
    }
  })
);
app.use(helmet.dnsPrefetchControl());
app.use(helmet.expectCt());
app.use(helmet.frameguard());
app.use(helmet.hidePoweredBy());
app.use(helmet.hsts());
app.use(helmet.ieNoOpen());
app.use(helmet.noSniff());
app.use(helmet.permittedCrossDomainPolicies());
app.use(helmet.referrerPolicy());
app.use(helmet.xssFilter());
```

Thank you.

**Comment by EvanHahn** [comment]
It's my fault that the documentation doesn't make this clear, and I'll fix that.

This will set all of the default middlewares and set custom options for `contentSecurityPolicy`:

```js
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: { /* ... */ },
    },
  })
);
```

You can also disable middlewares like this:

```js
app.use(
  helmet({
    contentSecurityPolicy: false,
  })
);
```

I'll update the docs now so that you're (hopefully) the last person to have this problem.

I think this answers your question so I'm going to close this issue, but let me know if that's wrong and I will reopen.
