### ISSUE TITLE
CSP policy not working properly

### ISSUE THREAD

**Issue by DevServo** [helmetjs/helmet#256]
Hello ,
 I have read the documentaion over and over again and tried various thing but CSP policy is not allowing imgaes from imgur
 here is the code 
```
app.use(
    helmet.contentSecurityPolicy({
        "default-src": ["'self'"],
        "base-uri": ["'self'"],
        "block-all-mixed-content": [],
        "font-src": ["'self'"],
       " frame-ancestors": ["'self'"],
       "img-src ["'self'", "https://imgur.com/"],
       " object-src": ["'none'"],
        "script-src": ["'self'"],
        "script-src-attr": ["'none'"],
       " style-src": ["'self'", "https: 'unsafe-inline'"],
        "upgrade-insecure-requests": []
    })
)
```
what am i doing wrong here??

**Comment by EvanHahn** [comment]
Not sure. When you open your browser's console, what errors do you see?

**Comment by DevServo** [comment]
Thnaks fro very quick response 
this is the error 
`Refused to load the image 'https://imgur.com/VWLnM9Y.jpg' because it violates the following Content Security Policy directive: "img-src 'self' data:".`

No idea why , I have closed the server and restarted it , have cleared everything in browser , tried edge, firefox, chrome nothing works

**Comment by EvanHahn** [comment]
That `img-src` is `'self' data:` which is different from what you specified in the JavaScript code.

If you go to the Network tab in your browser's developer tools and find the first request for the page, what value do you see for the `Content-Security-Policy` response header? Do you see the value you expect, or something else? If it's not what you expect, why not?

**Comment by DevServo** [comment]
> 
> 
> That `img-src` is `'self' data:` which is different from what you specified in the JavaScript code.
> 
> If you go to the Network tab in your browser's developer tools and find the first request for the page, what value do you see for the `Content-Security-Policy` response header? Do you see the value you expect, or something else? If it's not what you expect, why not?

for some reason the content-security-policy header does not show in headers while all the others are there 

as for the img-src self data , I have not already updated in code???  like this "img-src": ["'self'", "https://imgur.com"] or do I have to give somme value in daya as well?

**Comment by EvanHahn** [comment]
It's possible that you're overwriting the header after you use the middleware. For example, are you doing something like this?

```js
app.use(
  helmet.contentSecurityPolicy({ /* ... */ })
);

// This will overwrite the previous one.
app.use(helmet());
```

You might also be using another piece of middleware that causes this problem. You might also be using something "in front" of your Node app, such as nginx.

Does that help?

**Comment by DevServo** [comment]
nope I am not doing anything like that but I am using cookie-parser and express-session are they effecting this helmet? but all the other policies are being said like it does not show powered by and no sniff etc just the CSP that is not working

**Comment by EvanHahn** [comment]
The code snippet in your original issue shows you using `helmet.contentSecurityPolicy` which _only_ includes the `Content-Security-Policy` middleware. So if you're seeing other Helmet headers, it's likely that you are using Helmet in more than once place, or perhaps something else in your system is setting the headers.

Are you able to reproduce the problem in a completely new project?

**Comment by BobbySpoon** [comment]
The reason why it is not working is the options object you are using. As stated in the documentation:
`options.directives is an object.`

Or, if you prefer the raw code:
(https://github.com/helmetjs/helmet/blob/cb170160e7c1ccac314cc19d3b979cfc771f1349/middlewares/content-security-policy/index.ts#L61)

I do think though this could be either pointed at more directly in the docs or print a warning when CSP is invoked with options object that doesn't have the directives prop.

Hope that helped

**Comment by EvanHahn** [comment]
I think @BobbySpoon is right. In other words, you need to go from this:

```js
helmet.contentSecurityPolicy({
  'default-src': [/* ... */],
  // ...
});
```

To this:

```js
helmet.contentSecurityPolicy({
  directives: {
    'default-src': [/* ... */],
    // ...
  }
});
```

I'm going to close this issue because I think this solves your problem, but let me know if that's wrong and I can reopen.
