### ISSUE TITLE
Document-Policy

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#258]
As of this writing, the `Document-Policy` HTTP header isn't ready for prime-time yet, but we should keep an eye on it.

See comments below for the latest links.

**Comment by GrosSacASac** [comment]
404

**Comment by KrishnaRPatel** [comment]
The link above was removed in this PR: https://github.com/w3c/webappsec-permissions-policy/pull/416

Here's a link to the [Document Policy editor's draft on WICG](https://wicg.github.io/document-policy/) with an [FAQ here](https://github.com/w3c/webappsec-permissions-policy/blob/master/security-privacy-questionnaire-document-policies.md).

**Comment by EvanHahn** [comment]
I'm planning the next major version of Helmet, version 5.

Because the `Document-Policy` spec is still a draft and [it's only supported in Chrome right now](https://caniuse.com/document-policy), I do not plan to add this as a default in Helmet 5.

That doesn't mean I don't plan to add it, just that it won't be enabled by default in the next major version. I'm removing the v5.0.0 milestone.

**Comment by EvanHahn** [comment]
It's been awhile since this issue was opened and the specification is still in a draft state. I don't think there's anything actionable here, so I'm going to close this issue.

_If you want to set this header despite this_, you can! Here's an example:

```js
app.use((req, res, next) => {
  res.setHeader("Document-Policy", "foo=1.0, bar=?0");
  next();
});
```

If `Document-Policy` makes it out of draft or gains wider browser support, I'm happy to reconsider this decision. For now, I'm going to close this issue to clean up the repository.
