### ISSUE TITLE
Option setup for helmet use with SendGrid Email

### ISSUE THREAD

**Issue by gb53smith** [helmetjs/helmet#269]
I am sending email from my webserver using SendGrid.  The email is not sent when helmet is included in the middleware.

 ```
    app.use(helmet({
       contentSecurityPolicy: false,  // Allow links to other websites?
       permittedCrossDomainPolicies: false 
    }));  
```
I have turned contentSecurityPolicy and permittedCrossDomainPolicies OFF because I need to allow posting of links to other sites. (I have a whitelist to check for allowed URL prefixes.)

New to helmet, so I have no idea what other helmet option needs to be changed.

**Comment by gb53smith** [comment]
SendGrid works fine with the above settings.
I forgot to update my .env file with the SendGrid token when I ported from development to production.

**Comment by EvanHahn** [comment]
Glad you figured it out! Feel free to open a new issue if you run into any other problems.
