### ISSUE TITLE
X-Powered-By Helmet 3 vs 4

### ISSUE THREAD

**Issue by thernstig** [helmetjs/helmet#270]
I am unsure of this, but I recently discovered that X-Powered-By was included in the response headers. We upgrade to Helmet 4 a couple of weeks ago, but I thought that helmet by default disabled this in Helmet 3.

This issue is mainly to update https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide in case Helmet 3 did disable it. If not, then this issue can be closed.

**Comment by EvanHahn** [comment]
First of all, this shouldn't be too much of an issue. The removal of `X-Powered-By` offers little security benefit, so it's not a big deal if it's set.

Second, however, Helmet 4 should remove it. Are you seeing other Helmet headers be set (`X-XSS-Protection`, for example)? Can you make a small app that reproduces this problem?

**Comment by thernstig** [comment]
Yes, I can see that all other middleware works. `X-XSS-Protection: 0` is one of those headers. However, I still see `X-Powered-By: Express`.

Does it have anything to do with where in the flow I set `app.use(helmet());`? I set it immediately after `const app = express();`.

**Comment by EvanHahn** [comment]
That might be. What happens if you make a completely new Express app that just uses Helmet and has a simple request handler? Is the header there in that case?

As a workaround for now, you can run `app.disable('x-powered-by')` to disable the header at the Express level.

**Comment by thernstig** [comment]
I tested with `express-generator` and the results below show that `X-Powered-By` is indeed hidden by helmet() in that scenario. So this can be closed.

I actually found the real reason. We run Webpack, and in development Webpack runs its own Express server to serve static assets. And the config we set in our code does thus not affect the Webpack Express server.

```sh
~/code/test> http localhost:3000
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 170
Content-Type: text/html; charset=utf-8
Date: Tue, 13 Oct 2020 09:03:10 GMT
ETag: W/"aa-z+ebXSEdArbZ+EXlN/WQjf6HV8c"
X-Powered-By: Express

<!DOCTYPE html><html><head><title>Express</title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>Express</h1><p>Welcome to Express</p></body></html>

~/code/test> http localhost:3000
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 170
Content-Security-Policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
Content-Type: text/html; charset=utf-8
Date: Tue, 13 Oct 2020 09:03:47 GMT
ETag: W/"aa-z+ebXSEdArbZ+EXlN/WQjf6HV8c"
Expect-CT: max-age=0
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 0

<!DOCTYPE html><html><head><title>Express</title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>Express</h1><p>Welcome to Express</p></body></html>
```

**Comment by EvanHahn** [comment]
That makes sense. Glad we figured it out!

Feel free to open a new issue if you run into other problems.
