### ISSUE TITLE
CSP and sub domain 

### ISSUE THREAD

**Issue by aquinodaniel1994** [helmetjs/helmet#277]
Hi all, I'm using frameAncestors directives but I'm having trouble with the domains to specify them. at the moment I have to pass it all the domains and sub domains in clear text (http: //test.mydomanin.com https://devtest.mydomain.com).
However, I would like to make my code more flexible and use '* (https: //*.mydomanin.com)'. using this syntax, however, the library returns an error '[check csp]'
below is the code I am using.
`   .use(helmet.contentSecurityPolicy({
        directives: {
            defaultSrc: ["'self'"],
            frameAncestors: ["https://*.mydomain.com"]
        },
    }))`

**Comment by EvanHahn** [comment]
My reading of [the `frame-ancestors` documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) says that what you're doing should work. That code doesn't give me an error when I run it.

What problem are you running into? What specific error are you seeing?
