### ISSUE TITLE
Helmet silently causes failure to load react app (CRA) in production

### ISSUE THREAD

**Issue by marnixhoh** [helmetjs/helmet#288]
Hi,

First of all, thank you so much for this package and maintaining it! It is a really big help!

I have always used it without any problems locally while developing, but I just deployed my project on AWS Elastic Beanstalk and now the react app refuses to load. When I disable helmet, it does work in production... The below code snippet shows how I serve the react app (static) and the Helmet configuration:

```
mainApp.disable('x-powered-by')
mainApp.use(
    helmet({
        contentSecurityPolicy: {
            directives: {
                ...helmet.contentSecurityPolicy.getDefaultDirectives(),
                "script-src": ["'self'", "maps.googleapis.com"],
                "img-src": ["'self'", 'data:', 'maps.gstatic.com', '*.googleapis.com', '*.ggpht']
            }
        }
    })
)
mainApp.use('/static', express.static('static'))
mainApp.use(express.static('static/build'))

mainApp.use('/api', apiApp)

mainApp.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, '..', 'static/build/index.html'))
})
```

Again, locally this works just fine. However, in production, there is only one script tag - the one of the react runtime js file:
`<script src="/static/js/runtime-main.3f389e65.js"></script>`

(All the other script files are pending in the browser's network tab (developer tools).)

I believe that it is this script that should inject the other script tags, css, etc. for the react CRA app to work. However, this fails silently. I am pretty familiar with CSP error messages and how to solve them, however since no error messages are shown, I do not know where to start debugging this... While writing this, I just discovered that the pending script files are requested using https, while the app runs on http (for now). Could this be the culprit? Locally, this doesn't happen- these script files are requested using http.

Any help would be immensely appreciated. If I can provide any more information, please let me know!

Thank you so much

**Comment by EvanHahn** [comment]
Strange. I really don't know what could be causing that. Some ideas:

- What is the value of the `Content-Security-Policy` header?
- Does anything happen if you switch to using `Content-Security-Policy-Report-Only` (which you can do with `reportOnly: true` in the Helmet options)?
- I expect that the problem is related to CSP, but it _could_ be an issue with some of the other middlewares that Helmet sets. You could try disabling some of them to see if that fixes things, or try disabling CSP entirely (but keeping the rest) to see if that solves the problem.
- Does an error show up in another browser?

Would be keen to get to the bottom of this!

**Comment by marnixhoh** [comment]
Hi @EvanHahn,

Thank you so so much for helping me. As I was trying out your suggestions and writing up my findings here, I discovered the issue.

The CSP header of the GET request to the domain name was this:
```
Content-Security-Policy:
default-src 'self';
base-uri 'self';
block-all-mixed-content;
font-src 'self' https: data:;
frame-ancestors 'self';
img-src 'self' data: maps.gstatic.com *.googleapis.com *.ggpht xyz.s3.eu-central-1.amazonaws.com;
object-src 'none';
script-src 'self' maps.googleapis.com;script-src-attr 'none';style-src 'self' https: 'unsafe-inline';
upgrade-insecure-requests
```

I then found that disabling CSP fixed the problem:
```
helmet({
    contentSecurityPolicy: false
})
```
So I started taking a closer look at every individual CSP directive. I then noticed the 'upgrade-insecure-requests' one. I was unfamiliar with this specific directive, but luckily it is kind of self-explanatory... It turns any insecure (http) requests into secure (https) ones. This header indeed turned out to be the culprit.

The only thing that I don't understand yet, is why this problem only occurs in production and not locally in development... My guess is that it has something to do with the fact that my Elastic Beanstalk setup uses a reverse proxy (Nginx) for all incoming requests. Locally any requests are made directly to the Express server. Maybe I'm wrong, but I wanted to share this with you anyway in case it might help you or someone else in the future.

Thanks again for your help!!

**Comment by EvanHahn** [comment]
Glad your problem was solved.

One theory, which may be totally wrong, is that upgrade-insecure-requests behaves differently with localhost or for pages that are served via HTTP. In other words, if the page is already insecure, upgrade-insecure-requests is a no-op. Again, that might be incorrect.

**Comment by marnixhoh** [comment]
I'm afraid that isn't it. Both localhost and the production setup serve the page over http... But only with the production setup are the static assets, such as JS files requested over https.
