### ISSUE TITLE
reportOnly is not working in React SSR app

### ISSUE THREAD

**Issue by oageyeva** [helmetjs/helmet#293]
I tried to update helmet version to the latest (4.4.1) and ran into a problem with reportOnly directive. With reportOnly set to true I see multiple errors in the console and the app does not start.

![image](https://user-images.githubusercontent.com/62906145/108642391-d72bd580-7472-11eb-8feb-08762a0301ce.png)

Removing reportOnly directive fixes the issue. With the helmet 3.23.3 all worked fine. 

I followed the migration guide and set up nonce as follows:

```
  app.use((req, res, next) => {
      res.locals.nonce = uuid().replace(rhyphen, ``);
      cspConfig.directives.scriptSrc.push(`'nonce-${res.locals.nonce}'`);
      csp(cspConfig)(res, res, next);
    });
```
where cspConfig is a json containing all previously working directives (no functions) and reportOnly: true.

Any additional migration recommendations or tips would be appreciated. 

[Here is similar problem](https://community.auth0.com/t/helmet-content-security-policy-error-for-react-express-app-on-azure/50674) I found in the internet - the author could not make it work with the reportOnly directive on and had to remove it.

**Comment by EvanHahn** [comment]
Three things come to mind:

1. Can I see the full CSP config object you're using? Or a sample that reproduces the problem?
2. What is the value of the CSP header? You should be able to see this by going to the Network tab in your browser's developer tools.
3. You're pushing a new value onto an array for every request, which could cause the list to grow to a massive size. Something to keep in mind. It _might_ be your issue.

**Comment by EvanHahn** [comment]
I'm going to close this issue because I haven't heard back in a few days, but I'll reopen it as soon as I hear back (unless it's resolved).
