### ISSUE TITLE
How to disable block-all-mixed-content for Content Security Policy?

### ISSUE THREAD

**Issue by airglow923** [helmetjs/helmet#295]
I want to disable `block-all-mixed-content` from the default setting.

I'm using a config below:

```js
const config = {
  directives: {
    ...contentSecurityPolicy.getDefaultDirectives(),
    /* ... */
  },
  'block-all-mixed-content': false,
};
```

And I can still find `block-all-mixed-content` in the `Content-Security-Policy` section of the response header.

I don't seem to find a way to disable it in the [doc](https://helmetjs.github.io/).

Or do I have to remove the key from the object as shown in this [answer](https://github.com/helmetjs/helmet/issues/239#issuecomment-732007876)?

**Comment by EvanHahn** [comment]
`getDefaultDirectives()` returns an object with a key, `block-all-mixed-content`. It's up to you how you want to omit this.

You could remove it with Lodash's `omit`:

```js
import { omit } from "lodash";

// ...

const directives = {
  ...omit(contentSecurityPolicy.getDefaultDirectives(), [
    "block-all-mixed-content",
  ]),
  /* ... */
};

const config = {
  directives,
};
```

You could clone the object and `delete` the key:

```js
const directives = {
  ...contentSecurityPolicy.getDefaultDirectives(),
  /* ... */
};
delete directives["block-all-mixed-content"];

const config = {
  directives,
};
```

Or you could override all the defaults:

```js
const directives = {
  "default-src": ["'self'"],
  "base-uri": ["'self'"],
  "font-src": ["'self'", "https:", "data:"],
  "frame-ancestors": ["'self'"],
  "img-src": ["'self'", "data:"],
  "object-src": ["'none'"],
  "script-src": ["'self'"],
  "script-src-attr": ["'none'"],
  "style-src": ["'self'", "https:", "'unsafe-inline'"],
  "upgrade-insecure-requests": [],
  /* ... */
};

const config = {
  directives,
};
```

I'm going to close this issue because I think it answers your question, but let me know if that's wrong.
