### ISSUE TITLE
"Middlewares" is not grammatically correct

### ISSUE THREAD

**Issue by Fdawgs** [helmetjs/helmet#297]
Hi there!

Noticed the usage of "Middlewares" quite a bit in this repo.
"Middleware" is an uncountable noun, so the plural of "Middleware" is still "Middleware" and not "Middlewares".

I'm happy to make a PR to fix this if you want?

**Comment by EvanHahn** [comment]
_In summary: it's not clear to me that there's a consensus here._

This is something I thought about while writing this documentation and my old book about Express. It didn't seem like there was a clear consensus on whether "middlewares" was acceptable. Furthermore, it didn't seem like there was consensus about what the word "middleware" even meant.

The READMEs for [`body-parser`](https://github.com/expressjs/body-parser/blob/480b1cfe29af19c070f4ae96e0d598c099f42a12/README.md) and [`vhost`](https://github.com/expressjs/vhost/blob/18e6a24fc7fa2b613a6689141669e48688cc0cd3/README.md), both maintained by Express, say "middlewares" a few times. [Rails's documentation says "middlewares"](https://guides.rubyonrails.org/rails_on_rack.html) and [Redux uses the word in variable names](https://redux.js.org/understanding/history-and-design/middleware). In contrast, [Connect](https://github.com/senchalabs/connect/blob/54f2113270618960055f489e7cdd1a819750131f/README.md) and [Ruby's Rack](https://github.com/rack/rack/blob/bcefe0c8b33596639cc596aa2cd943090033dd38/README.rdoc) use "middleware", not "middlewares", to describe more than one.

To look at dictionaries: [Wiktionary says that the plural is "middlewares"](https://en.wiktionary.org/wiki/middleware); [Dictionary.com](https://www.dictionary.com/browse/middleware), the [Collins English Dictionary](https://www.collinsdictionary.com/dictionary/english/middleware), and [the American Heritage Dictionary](https://ahdictionary.com/word/search.html?q=middleware) don't seem to opine; [Merriam-Webster doesn't even have the word](https://www.merriam-webster.com/dictionary/middleware); the [Oxford Advanced Learner's Dictionary says the word is uncountable](https://www.oxfordlearnersdictionaries.com/definition/english/middleware), like you say. (I don't have an Oxford English Dictionary account so I don't know what they say, but it looks like the word was added in 2002 and I would expect it to be the same as the free Oxford Learner's resource I found.)

At times, it feels like people dance around ever using "middleware" or "middlewares" when describing more than one. [Express's documentation](https://expressjs.com/en/guide/using-middleware.html) always calls them "middleware functions" when pluralized, but "middleware" elsewhere. I certainly did this while writing my book.

There's also the question of what the words actually mean in the context of Express. [Express's docs](https://expressjs.com/en/guide/using-middleware.html) define them like this (emphasis and links removed):

> Middleware functions are functions that have access to the request object (req), the response object (res), and the next middleware function in the application’s request-response cycle.

You'll notice that they don't actually define the word "middleware"; they only define "middleware functions". `helmet()` returns a _middleware function_ (it's a function with `req`, `res`, and `next`), but is `helmet` itself a middleware function before you call it? I would say that it's not—it's a _middleware_—but it's not super clear, at least to me.

I don't know what the right answer is, but I've settled on the word "middlewares". Happy to discuss changing it.

**Comment by Fdawgs** [comment]
Thanks for the comprehensive response @EvanHahn !

**Comment by davidkhierl** [comment]
is this related to the issue I'm having? tried it on yarn 2 pnp and showing errors
```
.yarn/cache/helmet-npm-4.4.1-286ac392ee-32f5ca0517.zip/node_modules/helmet/dist/middlewares/content-security-policy/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.        

/// <reference types="node" />
 ```

**Comment by EvanHahn** [comment]
@Fdawgs No problem! I'm going to close this issue, but let me know if that's wrong and I can reopen.

@davidkhierl I don't think it's related. Would you open a new issue?
