### ISSUE TITLE
Pnp Node type definition

### ISSUE THREAD

**Issue by davidkhierl** [helmetjs/helmet#298]
I decided to migrate to yarn 2, the rest of packages works seamlessly apart form helmet.
```
.yarn/cache/helmet-npm-4.4.1-286ac392ee-32f5ca0517.zip/node_modules/helmet/dist/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
```

```
.yarn/cache/helmet-npm-4.4.1-286ac392ee-32f5ca0517.zip/node_modules/helmet/dist/middlewares/content-security-policy/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
```

**Comment by EvanHahn** [comment]
What happens if you install @types/node?

**Comment by EvanHahn** [comment]
I haven't heard back so I'm going to close this issue, but let me know if that's wrong and I'll reopen.

**Comment by davidkhierl** [comment]
sorry, got a bit busy this past weeks, seems installing the typing for node fix the issue, could this be added on the documentation when using plug n play?

**Comment by EvanHahn** [comment]
I don't currently have any documentation for Yarn usage. If I add that or more people start to report this problem, I'll add something.
