### ISSUE TITLE
Type 'true' is not assignable to type 'false'

### ISSUE THREAD

**Issue by byeze** [helmetjs/helmet#318]
Hello! 

I recently came in a problem when configuring "hidePoweredBy" property, visual studio gives me the following error:
![image](https://user-images.githubusercontent.com/7424138/117462502-1ff91380-af25-11eb-85e5-ad2ab6ac287e.png)
`index.d.ts(20, 2): The expected type comes from property 'hidePoweredBy' which is declared here on type 'Readonly<HelmetOptions>'`

I think that the correct type for this prop in Typescript will be:
`hidePoweredBy?: MiddlewareOption<boolean>`

**Comment by EvanHahn** [comment]
My best guess: you're not on the latest version of Helmet (this changed recently). Could you confirm you're on the latest version?

**Comment by byeze** [comment]
Yep! I installed the latest version and the problem disappeared. Thank you

**Comment by EvanHahn** [comment]
Glad to hear it!

Feel free to open a new issue if you have any other problems.
