### ISSUE TITLE
Helmet + Express + Typescript = No overload matches this call error

### ISSUE THREAD

**Issue by cehenriques** [helmetjs/helmet#325]
Issue similar to: #324 

My versions:
```
helmet@4.6.0
express@4.17.1
@types/express@4.17.13
@types/node@16.3.0
typescript@4.3.5
node@16.4.2
```

My code:
```
import express from "express";
import helmet from "helmet";
import cors from "cors";

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
```

tsconfig
```
{
  "compilerOptions": {
    "lib": ["es2020"],
    "module": "commonjs",
    "target": "es2020",

    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "outDir": "dist"
  },
  "include": ["**/*.ts", "./client/**/*"]
}
```

Error:
> No overload matches this call. The last overload gave the following error. Argument of type '(req: IncomingMessage, res: ServerResponse, next: (err?: unknown) => void) => void' is not assignable to parameter of type 'PathParams'. Type '(req: IncomingMessage, res: ServerResponse, next: (err?: unknown) => void) => void' is missing the following properties from type '(string | RegExp)[]': pop, push, concat, join, and 27 more.ts(2769)

I was able to workaround by making this change:
`app.use(helmet() as express.RequestHandler);`

I have the same issue with the `app.use(express.json());`, so not sure if this is related with helmet at all.

**Comment by EvanHahn** [comment]
If you're having this problem with other Express middleware, I suspect this is an issue with `@types/express` or possibly another tool. But I might be wrong!

I'm glad you have a workaround for now. I'm away from internet for the next week or so, which means I won't be able to release a patch for Helmet if this is indeed a Helmet issue.

**Comment by EvanHahn** [comment]
Any debugging you (or anyone else reading) could do would be appreciated.

**Comment by stuft2** [comment]
I experienced a similar issue. After looking through issues on express, I found this: 

[No overload matches this call -> use(express.json()) ?](https://github.com/expressjs/express/issues/4618)

☝🏻 his solution solves this issue as well: `npm upgrade`

**Comment by cehenriques** [comment]
> I experienced the same issue. After looking through issues on express, I found this:
> 
> [No overload matches this call -> use(express.json()) ?](https://github.com/expressjs/express/issues/4618)
> 
> ☝🏻 his solution solves this issue as well: `npm upgrade`

As I said above, I have all the packages up to date, and I still get the same error on both helmet() and express.json().
That issue doesn't help much because he never said what he actually updated that fixed the issue.

**Comment by EvanHahn** [comment]
I'm curious to know if it happens with other middleware. Do you get this error if you try writing your own middleware? What about things like `express.static` or `morgan`?

I also noticed that `@types/express` was updated recently. Could that be a culprit?

Again, I'm away from reliable internet for the next several days, so apologies if I can't be more helpful here.

**Comment by cehenriques** [comment]
I don't get the same error on my own middleware or with `cors()`.
I tried downgrading @types\express to 4.17.12, but it didn't solve.
There's no urgency with this since there's a workaround.

**Comment by cehenriques** [comment]
I downgraded some packages and found out that the issue is with `@types/node`.
I was using the latest version, v16.3.1, and when I downgraded to v14.17.4 the errors disappeared.

**Comment by ddialar** [comment]
I confirm the solution proposed by @cehenriques.

In my case, I downgraded the @types/node module to v14.14.45 and multiple typing errors disappeared.

**Comment by EvanHahn** [comment]
Maybe this is worth reporting an issue on DefinitelyTyped, or comparing what happened to cause this issue?

**Comment by ncxn** [comment]
I have same issue with 16.x
is Ok with 15.6.1

**Comment by 0x80** [comment]
15.9.x still gives me errors on bodyParser.json() and helmet()
15.6.x is 👌 for me

**Comment by EvanHahn** [comment]
I've been trying to reproduce this bug and have been unable. (I haven't tried everything in this issue yet, so I'm probably missing something.)

It seems like the type definitions for something other than Helmet are the issue, because body-parser also has a problem. Is that correct? Is anyone seeing TypeScript issues that only affect Helmet?

**Comment by 0x80** [comment]
@EvanHahn I think you might be right. If bodyParser.json() gives the same error then the source of the issue is likely outside the scope of Helmet.

**Comment by EvanHahn** [comment]
In that case, I recommend [checking the issues on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues) and opening a new one if you can't find one.

If this turns out to be a Helmet issue, I'm more than happy to reopen this!
