### ISSUE TITLE
Add support for manifest-src CSP value

### ISSUE THREAD

**Issue by jimsimon** [helmetjs/helmet#328]
It looks like it used to be possible to set the `manifest-src` value using helmet but it's not longer an option on the directives config for the CSP middleware. Can support for this please be re-added?

**Comment by EvanHahn** [comment]
Previous versions of Helmet had a list of supported directives, and setting an unsupported directive wasn't allowed (without a special override).

Helmet v4 allows you to sent any directive you want, including `manifest-src`. Just set it like any other directive.

I think this answers your question so I'm going to close this issue, but let me know if that's wrong and I'll reopen. Hope this helped!

**Comment by jimsimon** [comment]
This helped, thank you! It looks like koa-helmet needs to update their TypeScript typings to reflect this. I'll open an issue over there.
