### ISSUE TITLE
Add `form-action: 'self'` to default content security policy

### ISSUE THREAD

**Issue by davewichers** [helmetjs/helmet#335]
Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action - the form-action header is different than most other CSP headers in that it does NOT inherit a value from default-src since form-action is not in the list of attributes that DO inherit this value per: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src.  Likely because an 'action' is not a 'src'.

As such, seems like helmet should include a default form-action value of 'self'.  I happened to notice this because I was using OWASP ZAP, and it detected that the CSP response being generated by helmet was missing this CSP attribute and flagged it as a Medium severity security issue.  ZAP didn't report anything else against the default value, so I think this is the only issue ZAP has with the default helmet CSP value.

**Comment by EvanHahn** [comment]
This seems reasonable, probably defaulting to `'self'`. Do you agree?

If so, I can begin the work to put that into the next major version of Helmet.

**Comment by davewichers** [comment]
Yes. I agree. I suggested 'self' in the issue title. :-). Thanks for the super quick response!

**Comment by EvanHahn** [comment]
Ah, sorry, of course! I'll get on that.

I don't have an ETA for the next major version, but I'll start thinking about it.

**Comment by davewichers** [comment]
Not urgent, certainly. Thanks for working on it.

**Comment by EvanHahn** [comment]
If anyone wants to do this, it should be a matter of updating some tests and some values, and making a pull request against the `5.x` branch.

**Comment by EvanHahn** [comment]
Removing the "good starter task" label because I'm going to start on this work.

**Comment by EvanHahn** [comment]
Made #338 to add this to Helmet v5. Unless someone objects, I'll merge that in a few days.

**Comment by EvanHahn** [comment]
Merged! This will be part of the next major version.

**Comment by EvanHahn** [comment]
I just released Helmet v5.0.0-beta.1 which includes this change. Please give it a try with `npm install helmet@5.0.0-beta.1` and let me know if there are any problems! Feel free to reply here or email me@evanhahn.com with any feedback.

**Comment by EvanHahn** [comment]
This is now the default in `helmet@5`.
