### ISSUE TITLE
This expression is not callable.

### ISSUE THREAD

**Issue by csulit** [helmetjs/helmet#342]
src/main.ts:48:11 - error TS2349: This expression is not callable.
  Type 'typeof import("C:/Users/ChristianAngeloSulit/Documents/GitHub/hris_system/hris-backend/node_modules/helmet/dist/index")' has no call signatures.

48   app.use(helmet());

**Comment by EvanHahn** [comment]
Sorry about this!

Could you create a small sample app that demonstrates the problem? Also, what version of Helmet are you using?

**Comment by csulit** [comment]
> Sorry about this!
> 
> Could you create a small sample app that demonstrates the problem? Also, what version of Helmet are you using?

`import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import * as compression from 'compression';
import * as cookieParser from 'cookie-parser';
import * as helmet from 'helmet';
import * as hpp from 'hpp';
import * as xss from 'xss-clean';
import { AppModule } from './app.module';
import TransformInterceptor from './common/interceptor/transform.interceptor';
import HttpExceptionFilter from './common/serializer/exception/http.exception';
import PrismaExceptionFilter from './common/serializer/exception/prisma.exception';
import { PrismaClientService } from './prisma-client/prisma-client.service';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);

  app.useGlobalFilters(new HttpExceptionFilter());
  app.useGlobalFilters(new PrismaExceptionFilter());
  app.useGlobalInterceptors(new TransformInterceptor());

  if (process.env.NODE_ENV === 'development') {
    app.setGlobalPrefix('api');
  }

  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      forbidNonWhitelisted: true,
    }),
  );

  app.enableCors({
    origin: ['http://localhost:3000'],
    methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD'],
    credentials: true,
  });

  app.use(
    hpp({
      whitelist: [],
    }),
  );

  app.use(cookieParser());

  app.use(helmet());

  app.use(xss());
  app.use(compression());

  const prismaClientService: PrismaClientService = app.get(PrismaClientService);

  prismaClientService.enableShutdownHooks(app);

  await app.listen(process.env.PORT || 4001);
}
bootstrap();
`

**Comment by csulit** [comment]
@EvanHahn this solves the issue.

![image](https://user-images.githubusercontent.com/31933946/147899366-09770000-9ca2-482c-ae78-e5033bccdfd1.png)

**Comment by larshp** [comment]
Same problem here, using typescript, following the quick start, https://helmetjs.github.io with `app.use(helmet());`

**Comment by EvanHahn** [comment]
**tl;dr: change your import.**

```diff
-import * as helmet from 'helmet';
+import helmet from 'helmet';

 // ...

 app.use(helmet());
```

---

I believe this is working as expected. This kind of import should never work:

```js
// This should not work:
import * as foo from 'my-example-import';
foo();
```

That's because [`import *` imports the whole package as a namespace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_an_entire_modules_contents). TypeScript sometimes lets you get away with this, but it's not technically valid JavaScript as far as I understand.

You can fix it in one of two ways:

1. Import Helmet's default export:

   ```js
   import helmet from 'helmet';

   // ...

   app.use(helmet());
   ```
1. Import Helmet as a namespace, then use its subpackages. Be careful not to forget any! (This is the same as what @csulit suggested.)

   ```js
   import * as helmet from 'helmet';

   // ...

   app.use(helmet.contentSecurityPolicy());
   app.use(helmet.dnsPrefetchControl());
   // ...
   ```

I'm going to close this issue because I think things are working as intended, but let me know if that's wrong and I can reopen.
