### ISSUE TITLE
Cannot update from 4.6.0 to 5.0.1 on Node v16.13.2

### ISSUE THREAD

**Issue by imliuyzh** [helmetjs/helmet#346]
It seems like the dependency superagent is preventing me from doing so:
![image](https://user-images.githubusercontent.com/50005255/149011345-2804cb3a-ea0d-4a58-b506-c6185abf5b0f.png)

**Comment by EvanHahn** [comment]
Strange. Helmet has no dependencies (only devDependencies). Are you installing Helmet with devDependencies?

Also, it looks like the "required" versions would include Node 16, so that's also confusing.

**Comment by imliuyzh** [comment]
This is my package.json
`{
  "name": "antcatalog-server",
  "version": "1.0.0",
  "private": true,
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon index.js",
    "test": "jest",
    "coverage": "jest --coverage",
    "jslint": "npx semistandard"
  },
  "author": "Yizhen Liu",
  "license": "ISC",
  "devDependencies": {
    "jest": "^27.1.0",
    "nodemon": "^2.0.12",
    "semistandard": "^16.0.1",
    "supertest": "^6.1.6"
  },
  "dependencies": {
    "apicache": "^1.6.2",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "express-rate-limit": "^5.3.0",
    "express-validator": "^6.12.1",
    "fuse.js": "^6.4.6",
    "helmet": "^4.6.0",
    "node-cache": "^5.1.2",
    "sequelize": "^6.6.5",
    "sqlite3": "^5.0.2",
    "winston": "^3.3.3"
  }
}`

**Comment by EvanHahn** [comment]
What happens when you run `npm install`?

**Comment by imliuyzh** [comment]
I cloned my repository again and ran `npm i`:
![image](https://user-images.githubusercontent.com/50005255/149014582-da52111b-812d-4290-958f-998ba5fbc246.png)

**Comment by imliuyzh** [comment]
This is what happened after I ran `npm update`:
![image](https://user-images.githubusercontent.com/50005255/149014675-2f328fc5-d309-40da-a92c-6a3f20bbb591.png)

**Comment by imliuyzh** [comment]
I think it might be caused by Supertest after looking through this thread: https://github.com/visionmedia/superagent/issues/1665

**Comment by EvanHahn** [comment]
I think that's the problem. I'm going to close this issue but let me know if that's wrong and I'll reopen.
