### ISSUE TITLE
Static script file is blocked by CSP

### ISSUE THREAD

**Issue by reimarrosas** [helmetjs/helmet#357]
I'm mounting the default helmet middleware (`app.use(helmet())`) and I set up the correct directory to the static files. When I access the page, it says in the console that eval and inline script-src are blocked but I don't have any inline/eval scripts just a minified static script file without any evals.

**Comment by EvanHahn** [comment]
Strange. Some questions to help you debug:

1. Is it possible that a dependency uses `eval` or inline scripts?
2. Could you create a sample app that reproduces the problem?
3. What error are you seeing in your browser developer tools?

**Comment by reimarrosas** [comment]
To be precise, the script file in question is the bootstrap.bundle.min.js file.

I discovered that the script file IS working, there's only a slight problem with my template. However, I didn't realize that the script file is not the problem because there this thing showing up in my console:

![csp_error](https://user-images.githubusercontent.com/70522852/155259890-0218d8c0-79d4-42aa-a2fb-36d0f9e8c7f5.png)

**Comment by EvanHahn** [comment]
Some of those errors seem to have `moz-extension` on them. What happens if you remove _all_ JavaScript from your page? Do you still see those errors? What happens if you launch the page with Firefox extensions disabled?

**Comment by reimarrosas** [comment]
You're correct in that it's a firefox thing, I disabled all the script tags and it still exists. I tried a clean chrome install and it doesn't have anything. Thank you for helping me with this.

**Comment by EvanHahn** [comment]
Great! I'm going to close this issue but feel free to open a new one if you have other issues.
