### ISSUE TITLE
SUGGESTION: Add protection against (HTTP Parameter Pollution) attacks

### ISSUE THREAD

**Issue by tutyamxx** [helmetjs/helmet#362]
It would be awesome to add https://github.com/analog-nico/hpp protection against (HTTP Parameter Pollution) attacks.

**Comment by EvanHahn** [comment]
I don't think I'm going to do this, but it's a good suggestion.

Helmet is a module that sets HTTP response headers related to security. The hpp module is outside that scope, so it doesn't belong in Helmet.

However, I've put it on the "See also" page in Helmet's documentation.

Thanks for the idea! Let me know if you have any other thoughts about Helmet.

**Comment by tutyamxx** [comment]
Fair enough, thanks for the reply though.
