### ISSUE TITLE
COOP and COEP Issues in NestJS

### ISSUE THREAD

**Issue by ChristianHardy** [helmetjs/helmet#363]
Greetings Helmet team.

I'm using Helmet and NestJS and I'm having a COEP problem, I'm attaching a screenshot with the error:

![image](https://user-images.githubusercontent.com/9417617/166245038-5e70864a-76f3-466d-9d32-d34c51a4ed37.png)

I am using it as follows in main.ts file:
```
  app.enableCors({ credentials: true });
  app.use(helmet());

  app.use(cookieParser());
  await app.listen(PORT);
```

I would greatly appreciate your help

**Comment by EvanHahn** [comment]
I'm not sure where this error is coming from, but it looks like it's not detecting a Cross-Origin-Resource-Policy header. Helmet should set this header by default...

If you load your site, do you see that header? You can check it with `curl -I` or by using the Network tab in your browser's developer tools.

If the header is there, then something about this error is wrong. If it's not, we need to figure out why it's not there.

**Comment by ChristianHardy** [comment]
Solved, here the code for `main.ts` in NestJS

```
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { AppModule } from './app.module';
import config from './config/creds.config';
import { ValidationPipe } from '@nestjs/common';
import * as cookieParser from 'cookie-parser';
import helmet from 'helmet';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, { cors: true }); // Enable CORS in NestJS
  const { PORT } = config();

  app.useGlobalPipes(new ValidationPipe());

  app.use(cookieParser());

  app.use(helmet.crossOriginResourcePolicy()); // Use Helmet in standalone mode

  await app.listen(PORT);
}
bootstrap();

```

**Comment by EvanHahn** [comment]
Great! It looks like you're only using Helmet's `Cross-Origin-Resource-Policy` feature, so you might want to ensure that you're using the rest of its security features somewhere else in your app.
