### ISSUE TITLE
block-all-mixed-content directive is deprecated

### ISSUE THREAD

**Issue by fcrozatier** [helmetjs/helmet#372]
The block-all-mixed-content directive is deprecated and not recommended

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content

Should we remove it ? PR[#371](https://github.com/helmetjs/helmet/pull/371)

**Comment by EvanHahn** [comment]
Thanks for reporting! I'll look into this for the next major version.

**Comment by fcrozatier** [comment]
Ok let me know your thoughts on this !

**Comment by EvanHahn** [comment]
Will do. I'm busy this week but will take a look sometime after that.

**Comment by EvanHahn** [comment]
I spent a little time thinking about this.

The directive is deprecated, so we should eventually remove it. But some old browsers likely still respect it, and there's probably still some security benefit there.

I'm thinking of leaving it in and revisiting this in a year.

What do you think?

**Comment by fcrozatier** [comment]
Well this directive is not supported by ie so there is no benefits for really old browsers. 
[](https://caniuse.com/?search=block-all-mixed-content)
Also the `upgrade-insecure-requests` which effectively blocks the mixed content by redirecting over HTTPS has much better support and all browsers supporting the former support this one  [](https://caniuse.com/?search=upgrade-insecure-requests) so there is no security hole.

The `upgrade-insecure-requests` is evaluated before the `block-all-mixed-content` and when set the latter is a no-op. So we should only set one of these directives. 

I think that since we have set the `upgrade-insecure-requests`, the `block-all-mixed-content` directive is already ineffective so we can safely remove it.

**Comment by fcrozatier** [comment]
Forgot the links :
`block-all-mixed-content`not supported by ie: https://caniuse.com/?search=block-all-mixed-content 
`upgrade-insecure-requests` has much better support: https://caniuse.com/?search=upgrade-insecure-requests

**Comment by EvanHahn** [comment]
It doesn't benefit _really_ old browsers, but it does seem to benefit some. For example, according to [Can I Use](https://caniuse.com/?search=block-all-mixed-content), Firefox 48–101 supports this directive and has 2.85% usage globally. Maybe it makes sense to continue to support it for awhile? Does it _hurt_ anything, other than bandwidth?

**Comment by fcrozatier** [comment]
Indeed Firefox 48-101 supports it but it also supports [`upgrade-insecure-requests`](https://caniuse.com/?search=upgrade-insecure-requests) so in this case setting both would make `block-all-mixed-content` a no-op according to the note [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content).  

It doesn't hurt to keep it, but a no-op has no benefits doesn't it ? I haven't seen a browser supporting `block-all-mixed-content` and not `upgrade-insecure-requests` so it may have no effect whatsoever if both are set ? 
Does it make sense to keep supporting it if it's a no-op ?

**Comment by EvanHahn** [comment]
I agree that we should remove it if it's truly a no-op. Does it do anything on ANY browser if upgrade-insecure-requests is set?

**Comment by fcrozatier** [comment]
The MDN says 

> The [upgrade-insecure-requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests) directive is evaluated before `block-all-mixed-content`. If the former is set, the latter does nothing, so set one directive or the other – not both, unless you want to force HTTPS on older browsers that do not force it after a redirect to HTTP.

So the `block-all-mixed-content` directive does nothing in conjunction with `upgrade-insecure-requests`. The last bit is obscure to me.
What do you think ?

**Comment by EvanHahn** [comment]
I'll take a look. If it's completely useless for all browsers, I want to remove it. If it's useful for some browsers, then it's a harder question.

**Comment by fcrozatier** [comment]
What is your final decision ?

**Comment by EvanHahn** [comment]
Sorry, I haven't had time to look into this. It's still on my list.

**Comment by EvanHahn** [comment]
Took a look at this. We should remove the header. I'll review #371 now.

Sorry for the delay!

**Comment by EvanHahn** [comment]
`block-all-mixed-content` will be removed in Helmet v6. See more details in this comment: <https://github.com/helmetjs/helmet/pull/371#issuecomment-1204064888>.
