### ISSUE TITLE
TypeError: directiveValue is not iterable

### ISSUE THREAD

**Issue by danicunhac** [helmetjs/helmet#374]
Hi, I'm using version 5.1.0 and it's throwing me the following error:
```bash
/node_modules/helmet/dist/cjs/index.js:64
		for (const element of directiveValue) {
		                      ^

TypeError: directiveValue is not iterable
    at normalizeDirectives
```

I've just installed helmet the way it says in the docs. I'm using node v12.22.3 and no Typescript

**Comment by EvanHahn** [comment]
Could you post a code snippet of how you're using Helmet?

**Comment by danicunhac** [comment]
And I'm also importing it like
```js
const { default: helmet } = require('helmet')
```

**Comment by EvanHahn** [comment]
I'm away from my computer but `upgradeInsecureRequests: true` needs to be `upgradeInsecureRequests: []`, I believe. The report URI might also need to be in an array.

Let me know if this helps.

**Comment by danicunhac** [comment]
> I'm away from my computer but `upgradeInsecureRequests: true` needs to be `upgradeInsecureRequests: []`, I believe. The report URI might also need to be in an array.
> 
> Let me know if this helps.

This solution solved the original, the other two are separate ones. I'll close it as it's resolved. Thanks for the help @EvanHahn!
