### ISSUE TITLE
Hard to understand what are the defaults values

### ISSUE THREAD

**Issue by AlonMiz** [helmetjs/helmet#376]
when using helmet, im struggling to understand the default values.
especially with the version 5 changes in default values...
what is the result in using:
`app.use(helmet())`
would be great to see that object in the docs
Thanks

**Comment by EvanHahn** [comment]
You're right. This is a little confusing.

I've updated the readme in b99131e28fd194f5a31873da1c3252c602fe5c74 to make this clearer.
