### ISSUE TITLE
Remove Expect-CT in next major version

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#378]
See #310 for discussion.

**Comment by azu** [comment]
Note: Chrome 107 deprecates `Expect-CT` support
https://developer.chrome.com/blog/chrome-107-beta/#expect-ct
https://chromestatus.com/feature/6244547273687040

**Comment by EvanHahn** [comment]
This is done in the v7 branch. See #412.

**Comment by EvanHahn** [comment]
Merged in 38d7f6066cacb69d8d631f9c5a1dcd5aa0d81637.
