### ISSUE TITLE
Not working with express 4.17.2

### ISSUE THREAD

**Issue by Manik-Jtg** [helmetjs/helmet#380]
I'm using:
"express": "^4.17.2"
"helmet": "^5.1.1"

import express from "express";
import helmet from "helmet";
const app = express();
app.use(helmet());

None of the helmet headers show up and also x-powered-by remains there with value Express.

@EvanHahn

**Comment by EvanHahn** [comment]
I just tried to reproduce this and could not. Is it possible you need to clear your browser cache?

**Comment by Manik-Jtg** [comment]
i tried everything and did everything possible from [this](https://github.com/helmetjs/helmet/issues/134) issue as well but was not able to change even a single header on my localhost.
![Screenshot from 2022-08-25 21-11-54](https://user-images.githubusercontent.com/90383199/186710252-2e4383cc-f119-444c-a281-a55445c168f2.png)

**Comment by EvanHahn** [comment]
Could you build a full sample app that reproduce this problem?

**Comment by Manik-Jtg** [comment]
can i show u my implementation over call as in google meet?
Seems awkward to ask but if possible could u plz join this link and i would show u my app.
https://meet.google.com/zeq-iymj-cdy

**Comment by Manik-Jtg** [comment]
else i would try building the app

**Comment by Manik-Jtg** [comment]
Sure will just build it

**Comment by EvanHahn** [comment]
This issue hasn't had activity in a few months. I'm going to close it.

Let me know if that's wrong and I'll reopen!
