### ISSUE TITLE
Further reduce `package.json` size by removing `scripts` and `devDependencies` from published packages

### ISSUE THREAD

**Issue by Fdawgs** [helmetjs/helmet#384]
Care has already been taken to reduce the size of `package.json`:

https://github.com/helmetjs/helmet/blob/1140fb56d5e1cd606b36b68c347e81fd87a0ad81/.npmignore#L2

`package.json` could shave a few more bytes by running `npm pkg delete devDependencies` as part of the `prePublish` script.
If you want to go really crazy with it, you could also delete certain test scripts!

https://docs.npmjs.com/cli/v8/commands/npm-pkg

**Comment by EvanHahn** [comment]
I don't exactly know how I'd implement it (maybe `npm pkg delete`, maybe something else), but I like this idea!

**Comment by EvanHahn** [comment]
Updated the title to clarify what I think we want to do.

**Comment by EvanHahn** [comment]
This was done in 5bdac6ee041badcef118a52eb2c7e6d25f1acbb3.
