### ISSUE TITLE
Cross-Origin-Resource-Policy blocks all images

### ISSUE THREAD

**Issue by I-keep-trying** [helmetjs/helmet#385]
I hope it's ok to ask here. I have looked on stackoverflow, r/webdev, reactiflux, etc. to no avail.

Console error: "Specify a Cross-Origin Resource Policy to prevent a resource from being blocked"

On the front end, I have a regular old image element: 
`<img src='https://uilogos.co/img/logomark/nira.png' />` 

On the back end, I have helmet configured: 
```js
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        'img-src': [
          "'self'",
          'data:',
          'https://uilogos.co/img/logomark/nira.png',
          'https://images.unsplash.com',
        ],
      },
    },
    crossOriginResourcePolicy: { policy: 'same-site' },
  })
)
```
I added the `crossOriginResourcePolicy: { policy: 'same-site' },` option after first getting the error. 

I also added cors `app.use(cors())` after reading on SO that the CORP policy is intended in addition to CORS, not instead of. The only other suggestions I have found on SO are along the lines of, just don't use that policy or set it to 'cross-origin' but there's a warning in console against doing that. "⚠️If you set this header, any website can embed this resource."

[Published site](https://passport-email-signup-production.up.railway.app/)

[Back end repo](https://github.com/I-keep-trying/passport-email-signup)

Do I just need to download every image I need, so to avoid any calls to other origins?

**Comment by EvanHahn** [comment]
When I visit the published site in Firefox, I am able to load `nira.png`. What's the full error you're seeing?

**Comment by I-keep-trying** [comment]
@EvanHahn Thanks for the follow up. I apologize, I kinda forgot that I asked, and looking at my history, I can see that I commented out the csp configuration I had, (so it's now helmet default config) as well as downloading the image files on the front end, therefore circumventing the problem by not calling the urls that were blocked. That was 3 days ago, and your reply was 3 days ago, so I'm guessing maybe you saw it after I made the changes.

That being said, I would still like to understand how this feature works, because who knows, I might need to use image urls in the future. I'm going to roll back my deployment to how it was, and then I can get back to you with details about the error(s).

**Comment by I-keep-trying** [comment]
OK, here's a screen shot of the only error - there are no network errors

![csp-error](https://user-images.githubusercontent.com/26046173/200076813-da6bfea1-2709-4504-8371-a13b3365d425.png)

In case the image isn't clear enough, here's the text copy/pasted:

> Because your site has the Cross-Origin Embedder Policy (COEP) enabled, each resource must specify a suitable Cross-Origin Resource Policy (CORP). This behavior prevents a document from loading cross-origin resources which don’t explicitly grant permission to be loaded.

> To solve this, add the following to the resource’ response header:

> Cross-Origin-Resource-Policy: same-site if the resource and your site are served from the same site.

> Cross-Origin-Resource-Policy: cross-origin if the resource is served from another location than your website. ⚠️If you set this header, any website can embed this resource.

> Alternatively, the document can use the variant: Cross-Origin-Embedder-Policy: credentialless instead of require-corp. It allows loading the resource, despite the missing CORP header, at the cost of requesting it without credentials like Cookies.

Here's the helmet config: 

```js
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        'img-src': [
          "'self'",
          'data:',
          'https://uilogos.co',
          'https://images.unsplash.com',
        ],
      },
    },
    crossOriginResourcePolicy: { policy: 'same-site' },
  })
)
```

**Comment by EvanHahn** [comment]
Sorry I haven't responded here. This is still on my to-do list, but I've been busy.

I hope to get to it soon!

**Comment by EvanHahn** [comment]
You're embedding an image from another origin, triggering the document's "cross-origin embedder policy". This policy, controlled by the `Cross-Origin-Embedder-Policy` header, has three modes:

1. `unsafe-none`, the default value. Your page can load cross-origin resources without permission from the remote origin.

   For example, your page on `example.com` would be able to load `<img src="https://uilogos.co/img/logomark/nira.png">` with no issues.
2. `require-corp`, Helmet's default value. Your page can load cross-origin resources, but the remote origin has to give explicit permission. It can do this with the [`Cross-Origin-Resource-Policy` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy) or by using CORS.

   For example, your page on `example.com` can load `<img src="https://uilogos.co/img/logomark/nira.png">` _only if_ `uilogos.co` allows it. They'd need to do some work to support this.
3. `credentialless`. Your page can load cross-origin resources, but they can't include credentials like cookies. This isn't supported by all browsers.

I would recommend trying the `credentialless` policy to see if that works for you.

```js
app.use(
  helmet({
    // ...
    crossOriginEmbedderPolicy: { policy: 'credentialless' }
  })
)
```

One last thing: your `Content-Security-Policy` looks right to me. It's another way of restricting what your page can do, but isn't exactly related.

I think this answers your question, so I'm going to close this issue. Let me know if that's wrong and I'll reopen.
