### ISSUE TITLE
[Question] How to use helmet with angular cli?

### ISSUE THREAD

**Issue by marlonlom** [helmetjs/helmet#387]
**How to use helmet with angular cli?**
Im trying to use the library in conjuntion with angular cli, which, when using ng serve, deploys a web app for debugging/testing.

**Comment by EvanHahn** [comment]
Does the CLI let you write Express/Node code? If so, you should be able to add Helmet as middleware. If not, you may be unable to use Helmet here.

**Comment by EvanHahn** [comment]
I'm going to close this issue because there hasn't been a response. Let me know if that's wrong and I'll reopen.
