### ISSUE TITLE
Docs: README.md shows `expectCt()` being set by default

### ISSUE THREAD

**Issue by thernstig** [helmetjs/helmet#397]
Helmet 6.0.0 says that `helmet.expectCt()` is no longer set by default, as it was changed here https://github.com/helmetjs/helmet/issues/310

This still shows it being set though:

https://github.com/helmetjs/helmet/blob/151a7c5212d626e60d165948e29f3b2ac4806523/README.md?plain=1#L99

**Comment by EvanHahn** [comment]
Thanks for reporting. I'll take a look at your PR soon.

**Comment by EvanHahn** [comment]
This was fixed in a276e608e24054ef538c1bb2a65ace7066d8f9e5. Thanks for reporting!
