### ISSUE TITLE
X-DNS-Prefetch-Control is non-standard

### ISSUE THREAD

**Issue by tw0po1nt** [helmetjs/helmet#402]
Out of the desire for due diligence in knowing why I have configured my helmet setup the way I have (instead of just blindly accepting the defaults), I read up on the various headers. In the [MDN docs about the `X-DNS-Prefetch-Control` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control), there is a prominent warning:
> Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

With a warning this prominent, it seems like this header shouldn't be included in this package at all, let alone without so much as any mention of this warning in the documentation. I haven't seen any mention of this in any other issues or on SO, so I am not sure if this is just a new warning issued by MDN or if this header configuration was included deliberately despite the warning.

In any case, this should be addressed.

**Comment by EvanHahn** [comment]
Thanks for reporting. I'll think more about this.

Though MDN discourages its use, the header is supported by most major browsers. It can help improve user privacy while they browse your site.

However, it's a nonstandard header that has limited value. That, plus the warning on MDN, may mean it's worth removing.

Do you know if other similar modules include this header, too? (I recall that many do but haven't checked.)

Again, I'll think more about this and get back to you.

**Comment by EvanHahn** [comment]
I've decided I'm going to keep this header because I think it's useful. If you disagree, let me know.

**Comment by tw0po1nt** [comment]
As long as it is kept by deliberate decision, I'm fine with it. Just wanted to make sure that someone pointed out the warning on MDN.

**Comment by Aaronius** [comment]
The readme states that Helmet sets `X-DNS-Prefetch-Control` to `off` by default. That seems to be in conflict with native browser behavior: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control#directives

Is there a reason why Helmet would explicitly set `X-DNS-Prefetch-Control` to `off`?

**Comment by EvanHahn** [comment]
@Aaronius Privacy, mostly. More private for users (no DNS leaks) and more private for service operators (linked content can't be tied back to you). It's minor in any case.

If you want to discuss this further (it's a good question!), could you open a new issue?
