### ISSUE TITLE
import 6.0.1 TS project issue

### ISSUE THREAD

**Issue by deckikwok** [helmetjs/helmet#409]
Hi

imported "helmet": "^6.0.1" into express ts node project and faced the following error; Not sure why it would refer to the CJS module when I am using 

`import helmet from "helmet";
`

`TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("helmet")' call instead.   To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to ...`

uploaded tsconfig
[tsconfig copy.json.txt](https://github.com/helmetjs/helmet/files/11079229/tsconfig.copy.json.txt)

thanks for taking a look

**Comment by EvanHahn** [comment]
I've been working on fixes for this. Could you try this beta version to see if it works for you?

    npm install "https://evanhahn.com/tape/helmet-6.0.1.tgz"

(See #405 for more details.)

**Comment by EvanHahn** [comment]
What happens if you use `"module": "nodenext"` in your tsconfig?

**Comment by EvanHahn** [comment]
It's a little hard for me to figure out what's going wrong. Could you create a sample project that reproduces the issue? It probably just has a `package.json`, a `tsconfig.json`, and an `app.ts` file.

**Comment by deckikwok** [comment]
tried
https://github.com/deckikwok/test_helmet

issue only goes away with Typescript v5 and above.

**Comment by deckikwok** [comment]
ok worked with module:commonjs
https://github.com/deckikwok/test_helmet/settings

**Comment by EvanHahn** [comment]
Glad you solved it.

I'll see if I can improve this for other people in the future.
