### ISSUE TITLE
Error while building on local and digital ocean space

### ISSUE THREAD

**Issue by rashedulislam** [helmetjs/helmet#427]
I have a project setup where i have used NextJs on frontend and express in backend
While using using helmet for backend security headers following error thrown.

11:20 - error TS7016: Could not find a declaration file for module 'helmet'. '/.../node_modules/helmet/index.cjs' implicitly has an 'any' type.

Note: I have added @types/helmet as dev dependency

While deploying on digital ocean space it was throwing another error "tsc" not found. I was building through this command
npx tsc -p server && next build

**Comment by EvanHahn** [comment]
Sorry you're running into this.

If you're using the latest version of Helmet, you don't need @types/helmet.

If you still have problems after removing that, could you create a sample project that reproduces this issue?

**Comment by promise** [comment]
I had a similar issue on one of my projects, I was going to make a test project for this issue but figured out it was an issue with an old TypeScript version. For me, using `typescript@4.6.4` and `helmet@>=6.1.1` failed, but upgrading TS to `4.7.2` fixed the issue for me.

**Comment by EvanHahn** [comment]
There hasn't been activity on this issue in awhile and I think it's resolved, so I'm going to close.

If that's wrong, I'm happy to reopen this issue.
