### ISSUE TITLE
Cannot extract type for ContentSecurityPolicyOptions 

### ISSUE THREAD

**Issue by judithhartmann** [helmetjs/helmet#434]
With the changes in the type export from version 6.2 onwards, i do not find a way to correctly type our ContentSecurityPolicyOptions

I have tried the following workarounds:
```ts
// #1
type ContentSecurityPolicyOptions = Parameters<typeof helmet.contentSecurityPolicy>[0];

// #2
type ContentSecurityPolicyOptions = Extract<HelmetOptions['contentSecurityPolicy'], object>

// #3
type ContentSecurityPolicyOptions = HelmetOptions["contentSecurityPolicy"];
```

All of them result in a TS4023 Error:
Exported variable 'defaultPolicies' has or is using name 'ContentSecurityPolicyOptions' from external module "[PROJECT_PATH]/node_modules/helmet/index" but cannot be named.

```ts
import { HelmetOptions } from "helmet";
export type ContentSecurityPolicyOptions =
  HelmetOptions['contentSecurityPolicy'];

const defaultPolicies = {
  directives: {
    'default-src': ["'self'"],
    'script-src': [
      "'self'",
    ],
    'connect-src': [
      "'self'",
    ],
    'manifest-src': ["'self'"],
    'img-src': ["'self'"],
    'style-src': ["'self'"],
    'object-src': ["'none'"],
    'font-src': ["'self'"],
  },
} as ContentSecurityPolicyOptions;

export default defaultPolicies;
```

Typescript version: 4.9.5

As soon as an export is added to ContentSecurityPolicyOptions within the index.ts of helmet , this solution starts to work

**Comment by judithhartmann** [comment]
ok.. now i found a workaround, when not using the `as` syntax it works

```
export type ContentSecurityPolicyOptions =
  HelmetOptions['contentSecurityPolicy'];
  
const defaultPolicies: ContentSecurityPolicyOptions = {
}

export default defaultPolicies
```

i would still prefer importing the type directly from helmet, as now we need to either 
1. put the workaround everywhere we use it
2. put the workaround at a central place in our repo and import it from there

which it both more effort than just using it from helmet directly.

**Comment by EvanHahn** [comment]
I'm glad you found a workaround.

In the past, I have avoided adding additional features because they make it more difficult to make breaking changes in the future. However, this is a common request, so I may choose to add it despite that.

I'm unable to reproduce this error with the same code. It might be because I'm on a newer version of TypeScript...I wonder if upgrading TypeScript will fix the issue for you. (Probably not important because you have a solution, but maybe worth checking.)
