### ISSUE TITLE
Jest: Cannot find module 'helmet' or its corresponding type declarations

### ISSUE THREAD

**Issue by thorstenfleischmann** [helmetjs/helmet#435]
I try to run a ts-jest tests with supertest. The test fails with "Cannot find module 'helmet' or its corresponding type declarations".

helmet ^4.0.0 does not throw this error. Any idea what to look for?

Thanks so much.

**Comment by EvanHahn** [comment]
What version of Helmet are you using?

Could you share some sample code that reproduces the problem?

**Comment by thorstenfleischmann** [comment]
I don't know exactly what happened. But I was able to fix the problem by separating tests with jsdom environment from tests with node environment (using jest projects). Somehow jsdom caused this problem.

Sorry for bothering ;-)

**Comment by EvanHahn** [comment]
Glad you found a solution! Feel free to open a new issue if you run into any other problems.
