### ISSUE TITLE
Consider limiting helmet to document requests or add a note 

### ISSUE THREAD

**Issue by mariomc** [helmetjs/helmet#436]
Currently helmet middleware is applied to every single requese-response pair.

This makes it so that mixed applications (that serve documents, files or XHR requests) are applying security headers to non-document requests.

Example:
```js
const express = require('express');
const app = express();
const port = 3010;
const path = require('path');
const helmet = require('helmet');

app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        scriptSrc: ["'self'", () => `'nonce-stuff'`],
      },
    },
  })
);
app.use(express.static('static'));

app.get('/', (req, res) => {
  res.sendFile(path.resolve('pages/index.html'));
});

app.get('/api', (req, res) => {
  res.send({ test: 1 });
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
});
```

Result:
CSS             |  XRH/API
:-------------------------:|:-------------------------:
![](https://github.com/helmetjs/helmet/assets/887163/6d4a6c07-1dd7-4cc1-87d0-82cea1962ae2)  |  ![](https://github.com/helmetjs/helmet/assets/887163/86375ed6-9bb1-43fc-98ca-1d726b56d6e4)

This is unnecessarily inflating response sizes for clients and the documentation is not warning users about it.

I can help raise a PR if you find this a relevant issue but first, some questions:
- Is this considered a _bug_, misconfiguration or a new feature? 
- How should this be tackled? Via code or documentation?
- If via code, should it be within each internal middleware (ex: via a `req.accepts('html')` or `req.accepts(internalAllowListForMiddleware)`)? OR
- Given that all of them seem document related (are they?), should it be inside the main entry point?
- Should that be default behavior or should it be hidden behind an option?
- If behind an option, should it be a boolean or something else? What would be the default?

**Comment by mariomc** [comment]
> It's considered a side-effect of the design.
> 
> Helmet is designed to be easy to use. It's not always possible to do this, but I try to make something that can be included with one line. Ideally, you'd just be able to do this:
> 
> ```js
> // The ideal
> app.use(helmet());
> ```
> 
> As you point out, this creates a problem: many of Helmet's headers are wasteful for non-documents.

Thank you for the reply.

I'll open a PR adding a note below that line in the documentation.

> But even if it were supported, the [Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) isn't the right way to determine whether Helmet headers should be set. Just because a request accepts HTML doesn't mean that's what will be used in the response.

You're right. For something like this to exist, it would have to be derived on the response type somewhere.
Given how middlewares work, nothing ensures this plugin that - even though the response isn't _yet_ a document, it 
_could_  be transformed by the next middleware up in the chain.

I now understand what you mean't by being difficult to "reliably set the appropriate headers automatically." 😄 

Given how chaining works, should we also recommend (in the documentation) that this middleware should be the last one to be executed?

**Comment by EvanHahn** [comment]
Thanks for opening a PR.

> Given how chaining works, should we also recommend (in the documentation) that this middleware should be the last one to be executed?

Sorry, I don't understand this. Could you explain?

**Comment by mariomc** [comment]
> Sorry, I don't understand this. Could you explain?

Disregard my comment. 😄 
I was needlessly concerned about conflicting middleware that adds `X-Powered-By` or others.

Instead of:
```javascript
app.use(helmet());
app.use(middlewareThatAddsXPoweredBy());
``` 

Ensuring:
```javascript
app.use(middlewareThatAddsXPoweredBy());
app.use(helmet());
```

**Comment by EvanHahn** [comment]
I've added a page to the documentation, ["How should I use Helmet with non-document responses?"](https://helmetjs.github.io/faq/non-documents/).
