### ISSUE TITLE
helmet + sanitizeFilter

### ISSUE THREAD

**Issue by mejrimo** [helmetjs/helmet#442]
i read on the internet that you can use helmet and mongoose's sanitizer this way:
app.use(helmet({
  sanitizeFilter: true,
})); 
but i can't find it in your documentation. so i'm guessing if this is true and if it works the same way of mongoose.set("sanitizeFilter", true);.

thank you very much in advance for your reply

**Comment by EvanHahn** [comment]
I'm not familiar with Mongoose but this isn't a Helmet option. It looks like something that's part of Mongoose.

Hope this helps!
