### ISSUE TITLE
Require Node 18+

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#444]
[Node 16 is no longer supported.][0] Helmet v8 should drop support too.

Required subtasks:

- [x] Update the `engines` field of `package.json`
- [x] Remove old Node versions from CI configuration (bbcefa30146b613245ff22e5bc62b0ff49eaa808)
- [x] Update the changelog

[0]: https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by njmulsqb** [comment]
Hi @EvanHahn,

I am willing to work on this, can you tell me how much effort is required on this?

**Comment by EvanHahn** [comment]
The required subtasks are written in the description. I estimate <30 minutes of work.

Please make your change against the `v8.0.0` branch. Let me know if I can help with anything!

**Comment by njmulsqb** [comment]
Alright, can I get my NPM account under contributors on https://www.npmjs.com/package/helmet after working on this issue?

**Comment by EvanHahn** [comment]
I don't usually add people there, but I add lots of people to [the contributors list on the Helmet website](https://helmetjs.github.io/faq/contributors/). Feel free to add your name there after you make your change!

**Comment by EvanHahn** [comment]
Completed in #450. Thanks, @njmulsqb!
