### ISSUE TITLE
Support `unsafe-none` in `helmet.crossOriginEmbedderPolicy`?

### ISSUE THREAD

**Issue by mxxk** [helmetjs/helmet#446]
@EvanHahn thanks for your continued work on this package. 🙌

I noticed that although `unsafe-none` is a valid value for [`Cross-Origin-Opener-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) and [`Cross-Origin-Embedder-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy), and it is supported by `helmet` COOP,

https://github.com/helmetjs/helmet/blob/312383131ecc979c3c19112d26c06d4d344c4643/middlewares/cross-origin-opener-policy/index.ts#L3-L11

but it is not supported by `helmet` COEP:

https://github.com/helmetjs/helmet/blob/312383131ecc979c3c19112d26c06d4d344c4643/middlewares/cross-origin-embedder-policy/index.ts#L3-L7

I was wondering if this seems right to you, and if not, I'm happy to submit a PR! I don't believe this would be a breaking change.

**Comment by EvanHahn** [comment]
You're right. COEP should support "unsafe-none". Feel free to open a pull request!
