### ISSUE TITLE
Error "script-src-elem" is an invalid directive

### ISSUE THREAD

**Issue by nck** [helmetjs/helmet#452]
But it's valid, isn't it? 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem

**Comment by EvanHahn** [comment]
I'm not sure what's happening here. Could you share a code snippet that reproduces your problem?

**Comment by nck** [comment]
This was due to having an outdated version of helmet. Updating solved it.

**Comment by EvanHahn** [comment]
Glad you solved this! Feel free to open a new issue if you run into any other problems.
