### ISSUE TITLE
helmet default directives doesnt match helmet-csp default directives

### ISSUE THREAD

**Issue by NihilumPlays** [helmetjs/helmet#461]
while going from helmet to helmet csp i noticed that form-action 'self' is not part of helmet-csp default directives. 

is there a reason for this?
is it safe to omit form-acion?

i see you maintain both libraries so im just wondering about the difference

**Comment by EvanHahn** [comment]
Good point. helmet-csp is out of date. I'll update it.

**Comment by NihilumPlays** [comment]
For anyone running into this as well you can add a form-action: 'self' manually as a temporay fix if you're using helmet-csp

**Comment by EvanHahn** [comment]
Published `helmet-csp@4.0.0` to fix this. Thanks for reporting!
