### ISSUE TITLE
Strict-Transport-Security middleware should throw, not warn, when misspelling "includeSubDomains" option

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#462]
This should throw instead:

https://github.com/helmetjs/helmet/blob/892ed40f76183e7db4b434550b0b18a903cd4da3/middlewares/strict-transport-security/index.ts#L31-L35

To fix this, we should:

1. Update these lines to throw, not warn.
2. Fix the tests.

This change should be opened against the `v8.0.0` branch, not `main`.

**Comment by sohrb** [comment]
Here is the [PR](https://github.com/helmetjs/helmet/pull/464)

**Comment by EvanHahn** [comment]
Done in 2ccdab698767186ffb67f9c54e29e25eb7727168. Thanks, @sohrb!
