### ISSUE TITLE
csp header lack `script-src-elem`

### ISSUE THREAD

**Issue by Pomax** [helmetjs/helmet#466]
CSP keeps inventing new ways to make the web worse. `script-src-elem` is no exception, and will have to be added to the CSP header list.

**Comment by EvanHahn** [comment]
Sorry, I don't think I understand. What's the problem here?

**Comment by Pomax** [comment]
When using helmet, there is no [script-src-elem](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem) entry in the list of directives that are included in the header:

```
Content-Security-Policy: default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
```

Which means that with CSP 3 now rolling out, pages that use things like custom elements are starting to break in Firefox at the very least.

**Comment by EvanHahn** [comment]
I'm surprised that CSP 3 is introducing breaking changes. Can you give an example of something that breaks?

**Comment by Pomax** [comment]
Turns out I can't, instead firefox and noscript have a weird interaction that gave rise to completely useless CSP errors that weren't CSP errors at all, but noscript doing its thing.
