### ISSUE TITLE
[feature request] "simple allow everything" setting for development work?

### ISSUE THREAD

**Issue by Pomax** [helmetjs/helmet#467]
For setting up a quick dev server that browsers are at least willing to work with, it would be super useful if there was some way to say `app.use(helmet({ allowEverything: true }))` or something, so that people don't need to care about which policies and origins need to be set until that part of getting ready for production actually matters (if their project even ever makes it to production, rather than staying a local-only project).

**Comment by EvanHahn** [comment]
Would something like this work for you?

```javascript
if (!isDevelopment) {
  app.use(helmet());
}
```

**Comment by Pomax** [comment]
That only generates `Content-Security-Policy: default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests`, which means barely anything will work beyond "just loading the page" compared to `default-src * 'unsafe-eval' 'unsafe-inline' 'unsafe-dynamic' data: filesystem: about: blob: ws: wss:`. I'm hoping that helmet can add something that that sets all directives to their most permissive possible values.

**Comment by EvanHahn** [comment]
Disabling the CSP should have a similar effect. Would that work for you?

**Comment by Pomax** [comment]
Not really, tooling that expects a CSP header won't work that way.

**Comment by EvanHahn** [comment]
After some consideration, I don't think I'm going to add this. Helmet is designed to improve security, and (generally) disabling its headers is sufficient to remove those protections.

However, here are a couple of workarounds:

- Use a different Helmet configuration in development.

  ```js
  let helmetMiddleware;

  if (isDevelopment) {
    helmetMiddleware = helmet({
      contentSecurityPolicy: {
        directives: {
          "default-src": [
            "*",
            "'unsafe-eval'",
            "'unsafe-inline'",
            "'unsafe-dynamic'",
          ],
        },
      },
      xFrameOptions: false,
    });
  } else {
    helmetMiddleware = helmet({
      // ...some other config...
    });
  }

  app.use(helmetMiddleware);
  ```

- In development, disable Helmet completely.

  ```js
  if (!isDevelopment) {
    app.use(helmet());
  }
  ```

Hope this helps.

**Comment by Pomax** [comment]
cheers
