### ISSUE TITLE
is SSLPinning deprecated from latest versions?

### ISSUE THREAD

**Issue by saranrajui** [helmetjs/helmet#472]
I could not see the below implementation of SSL Pinning for server side using the latest version, but in older version like '0.15.0'

app.use(helmet.publicKeyPins({
  maxAge: ninetyDaysInMilliseconds,
  sha256s: ['AbCdEf123=', 'ZyXwVu456='],
  includeSubdomains: true,         // optional
  reportUri: 'http://example.com'  // optional
}));

**Comment by EvanHahn** [comment]
The HTTP public key pinning middleware, `helmet.hpkp`, was removed in version 4.0.0. I removed it because it is no longer recommended.

If you really still need it, you can use the [hpkp package](https://www.npmjs.com/package/hpkp).

I'm going to close this issue because I think I've answered your question.

**Comment by saranrajui** [comment]
I appreciate your response in no time, I was surprised to know that it was not recommended so it got removed. My aim is to enable ssl pinning to add an extra layer of security for my app, do you have any reason or explanation why it got removed ( eager to know by any other means the pinning can be done ) ?

indeed hpkp I'll use, is there any reason behind it wasn't considered from helmet?

**Comment by EvanHahn** [comment]
See ["Chrome is backing away from public key pinning, and here's why"](https://www.zdnet.com/article/google-chrome-is-backing-away-from-public-key-pinning-and-heres-why/) and ["RIP HPKP: Google abandons public key pinning"](https://www.theregister.com/2017/10/30/google_hpkp/) for details. Its usage is not recommended.
