### ISSUE TITLE
cannot use express-mongo-sanitize

### ISSUE THREAD

**Issue by TeemoSasuke** [helmetjs/helmet#475]
const express = require('express');
const bodyParser = require('body-parser');
const mongoSanitize = require('express-mongo-sanitize');

const app = express();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

// By default, $ and . characters are removed completely from user-supplied input in the following places:
// - req.body
// - req.params
// - req.headers
// - req.query

// To remove data using these defaults:
app.use(mongoSanitize());

// Or, to replace these prohibited characters with _, use:
app.use(
  mongoSanitize({
    replaceWith: '_',
  }),
);

// Or, to sanitize data that only contains $, without .(dot)
// Can be useful for letting data pass that is meant for querying nested documents.
// NOTE: This may cause some problems on older versions of MongoDb
// READ MORE: https://github.com/fiznool/express-mongo-sanitize/issues/36
app.use(
  mongoSanitize({
    allowDots: true,
  }),
);

// Both allowDots and replaceWith
app.use(
  mongoSanitize({
    allowDots: true,
    replaceWith: '_',
  }),
);

app.post('/test', (req, res) => {
    res.send('Sanitization test passed!');
});

app.listen(3001, () => {
    console.log('Test server is running on http://localhost:3001');
});

trying to test sanitize, but getting the following error info:

[nodemon] restarting due to changes...
[nodemon] starting `node testSanitize.js`
Test server is running on http://localhost:3001
TypeError: Cannot set property query of #<IncomingMessage> which has only a getter
    at /Users/nataliewang/Desktop/tryagain/node_modules/express-mongo-sanitize/index.js:113:18
    at Array.forEach (<anonymous>)
    at /Users/nataliewang/Desktop/tryagain/node_modules/express-mongo-sanitize/index.js:110:44
    at Layer.handleRequest (/Users/nataliewang/Desktop/tryagain/node_modules/router/lib/layer.js:145:17)
    at trimPrefix (/Users/nataliewang/Desktop/tryagain/node_modules/router/index.js:337:13)
    at /Users/nataliewang/Desktop/tryagain/node_modules/router/index.js:295:9
    at processParams (/Users/nataliewang/Desktop/tryagain/node_modules/router/index.js:575:12)
    at next (/Users/nataliewang/Desktop/tryagain/node_modules/router/index.js:289:5)
    at jsonParser (/Users/nataliewang/Desktop/tryagain/node_modules/body-parser/lib/types/json.js:116:7)
    at Layer.handleRequest (/Users/nataliewang/Desktop/tryagain/node_modules/router/lib/layer.js:145:17)

**Comment by EvanHahn** [comment]
I don't see Helmet anywhere in your configuration. What Helmet-specific issue are you running into?

**Comment by EvanHahn** [comment]
I'm going to close this issue because I don't see anything Helmet-related. Let me know if that's wrong and I'll reopen.
