### ISSUE TITLE
What have change in helmet 8.0.0 ?

### ISSUE THREAD

**Issue by Nick390** [helmetjs/helmet#476]
I use helmet in many projects and it caught my attention that the project reached version 8. 
First of all, thank you for your efforts. **This is great work.**

I would like to know the most important changes in the new version 8.0.0 In order to decide if there is something specific that will affect the work of my projects or I need to update it on my part.

**Comment by EvanHahn** [comment]
Check out the [changelog](https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md) for a full list of changes in every version.

Hope this answers your question!
