### ISSUE TITLE
helmet.defaults(app, { cacheControl: false });

### ISSUE THREAD

**Issue by linus-amg** [helmetjs/helmet#54]
that does not make a difference to caching behaviour, neither before nor after 
app.use(helmet.defaults());
i would like to include the defaults but i want caching to be enabled, removing the helmet.defaults() caching behaviour is like expected, maybe im implementing wrong? but i could not find a better explanation in the documentation.

**Comment by EvanHahn** [comment]
You can do something like this:

```js
app.use(function (req, res, next) {
  res.setHeader('Cache-Control', 'must-revalidate, max-age: 86400')
  next()
})
```
