### ISSUE TITLE
Support for defining CORS headers?

### ISSUE THREAD

**Issue by joelabair** [helmetjs/helmet#79]
Is there support for defining CORS response headers?   

- Access-Control-Allow-Origin
- Access-Control-Allow-Credentials
- Access-Control-Expose-Headers
- Access-Control-Max-Age
- Access-Control-Allow-Methods
- Access-Control-Allow-Headers

**Comment by binarykitchen** [comment]
What's the status of this ticket? Does helmet come with CORS utility functions now?

**Comment by EvanHahn** [comment]
I think we should just recommend some good CORS middleware (like above) and
add it to the readme. Thoughts?

**Comment by binarykitchen** [comment]
Maybe https://www.npmjs.com/package/cors ?

**Comment by EvanHahn** [comment]
Is anyone opposed to me adding a "other recommended modules" section to the
README, adding the cors package, and closing this issue?

**Comment by m13** [comment]
No, it's fine. Don't re-implement the wheel. It's better to focus.

**Comment by evilpacket** [comment]
+1
