### ISSUE TITLE
Weird AngularJS CSP code

### ISSUE THREAD

**Issue by binarykitchen** [helmetjs/helmet#88]
While debugging to find out why the helmet code isn't working properly with AngularJS I opened the console and found this error

```
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://localhost:8080 https://*.google-analytics.com"). bundle-3fe04b60.js:3811
```

Ok, I clicked on `bundle-3fe04b60.js:3811` and spotted these interesting code lines inside the AngularJS framework:

```js
var csp = function() {
  if (isDefined(csp.isActive_)) return csp.isActive_;

  var active = !!(document.querySelector('[ng-csp]') ||
                  document.querySelector('[data-ng-csp]'));

  if (!active) {
    try {
      /* jshint -W031, -W054 */
      new Function('');
      /* jshint +W031, +W054 */
    } catch (e) {
      active = true;
    }
  }

  return (csp.isActive_ = active);
};
```

What should I add under `'script-src'` to accept the above?

**Comment by EvanHahn** [comment]
Can you go into the Network tab and see what resource it's trying to load?

**Comment by binarykitchen** [comment]
Not relevant for me anymore. I found out that AngularJS is 30% slower with CSP enabled so I removed `app.use(helmet.csp(policy))` completely :(

**Comment by evilpacket** [comment]
It's really weird to me that it would have that drastic of a performance impact. @binarykitchen do you have a reference for that by chance?

**Comment by binarykitchen** [comment]
https://docs.angularjs.org/api/ng/directive/ngCsp

**Comment by mattjay** [comment]
That performance hit is seriously surprising. Cc: @prozachj

**Comment by EvanHahn** [comment]
Is this still an issue? I'll close if not.

**Comment by binarykitchen** [comment]
Yes, it is still an issue

**Comment by EvanHahn** [comment]
This mostly looks like an Angular issue. From the [ngCsp docs](https://docs.angularjs.org/api/ng/directive/ngCsp):

> AngularJS uses `Function(string)` generated functions as a speed optimization. Applying the `ngCsp` directive will cause Angular to use CSP compatibility mode. When this mode is on AngularJS will evaluate all expressions up to 30% slower than in non-CSP mode, but no security violations will be raised.

You have four options:

1. disable CSP altogether, forgoing any of its security benefits
1. drop Angular altogether
1. add `'unsafe-eval'` to your CSP policy, forgoing that security benefit but keeping the rest
1. add the `ng-csp` directive and take a performance hit

I'd recommend option 3 or 4; option 2 would be crazy and option 1 is no better than option 3.

**Comment by binarykitchen** [comment]
Thanks for the recommendations - I'll give option 3 or 4 a try.

**Comment by binarykitchen** [comment]
Correction @EvanHahn, even with `unsafe-eval` AngularJS complains. Here my code:

```js
     // not working well, see https://github.com/evilpacket/helmet/issues/28
    var policy = {
        defaultPolicy: {
            'default-src': [
                "'self'",
                "data:",
                "'unsafe-inline'",
                "'unsafe-eval'"
            ],
            'img-src': [
                "'self'",
                "data:",
                "www.google-analytics.com"
            ],
            'script-src': [
                "'self'",
                "'unsafe-inline'",
                "'unsafe-eval'",
                "www.google-analytics.com"
            ]
        }
    }

    app.use(helmet.csp(policy))
```

I won't consider option 4 due to the performance hit.

**Comment by EvanHahn** [comment]
Would you be able to create a simple test app that recreates this issue?
I'd imagine it's just a simple Angular app with these CSP directives, but
I'm not sure.

**Comment by EvanHahn** [comment]
@binarykitchen Any chance you could make a simple example app that tests this?

**Comment by binarykitchen** [comment]
Sorry, too busy right now and for now I have disabled this module in my code.

**Comment by EvanHahn** [comment]
Okay. Let me know if we can help.

Do you mind if we close this issue? It seems to be an issue with Angular and not Helmet.

**Comment by binarykitchen** [comment]
Sure, closed
