### ISSUE TITLE
Lo-Dash version

### ISSUE THREAD

**Issue by netmiller** [helmetjs/helmet#89]
With __iojs__ I have updated my __lodash__ package -> v.3.2.0.
Now npm is warning :

````
npm WARN unmet dependency /Users/esa/devel/iris/node_modules/helmet/node_modules/helmet-csp requires lodash@'2.4.1' but will load
npm WARN unmet dependency /Users/esa/devel/iris/node_modules/lodash,
npm WARN unmet dependency which is version 3.2.0
````

Do you think there will be any problem that I might be afraid.

**Comment by EvanHahn** [comment]
Just pushed Helmet 0.6.1. Could you try updating?

**Comment by netmiller** [comment]
OK, now it's clean (update). I also removed with __npm remove helmet__, and deleted this dependency from __package.json__, and installed again.  No warnings.  Thank you very much !

[closing this issue]

**Comment by EvanHahn** [comment]
:+1:
