### ISSUE TITLE
Add Support for HTTP Public Key Pinning (HKPK)

### ISSUE THREAD

**Issue by ajinabraham** [helmetjs/helmet#90]
For your ref: https://timtaubert.de/blog/2014/10/http-public-key-pinning-explained/

**Comment by EvanHahn** [comment]
Thanks for pointing this out!

Here's what I'm thinking the API might look like:

```js
// Specifying the SHAs
app.use(helmet.publicKeyPins({
  sha256s: 'AbC123...=',  // could also be an array
  maxAge: 12345,
  includeSubdomains: true
});

// Instead, pass paths to the keys
app.use(helmet.publicKeyPins({
  keys: '/path/to/key.pem',  // could also be an array
  // ...
});
```

What do you think?

**Comment by ajinabraham** [comment]
The first one looks good.
According to IETF draft on public key pinning, there can be options like report-uri. 

ex:
```
   Public-Key-Pins: max-age=3000;
       pin-sha256="d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=";
       pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";

   Public-Key-Pins: max-age=2592000;
       pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";
       pin-sha256="LPJNul+wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ="

   Public-Key-Pins: max-age=2592000;
       pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";
       pin-sha256="LPJNul+wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ=";
       report-uri="http://example.com/pkp-report"

   Public-Key-Pins-Report-Only: max-age=2592000;
       pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";
       pin-sha256="LPJNul+wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ=";
       report-uri="https://other.example.net/pkp-report"

   Public-Key-Pins:
       pin-sha256="d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=";
       pin-sha256="LPJNul+wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ=";
       max-age=259200

   Public-Key-Pins:
       pin-sha256="d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=";
       pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";
       pin-sha256="LPJNul+wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ=";
       max-age=10000; includeSubDomains

```
If you are going with the second option then the following are my concerns.
Pinning can happen at different levels of certificate. Like someone will pin the root CA and the leaf node, someone else will pin the intermediate CA and the leaf node. So if you are reading the pem file with the chain of certificates. The choice of selecting certificates to be used for pinning needs to be specified or else the developer has to extract these from the chain and specify as an array. Thinking of all this I would say you should go with the first approach.

**Comment by EvanHahn** [comment]
Good points. Your second point should also make the code much simpler.

This probably means making a new repo. I'll get to this soon (unless you'd
like to).

**Comment by EvanHahn** [comment]
See work at <https://github.com/helmetjs/hpkp>

**Comment by EvanHahn** [comment]
Just pushed Helmet 0.7.0 with HPKP support. You can use it with `helmet.hpkp` or with the [standalone hpkp module](https://github.com/helmetjs/hpkp).
