### ISSUE TITLE
HTTP Parameter Pollution Attacks

### ISSUE THREAD

**Issue by analog-nico** [helmetjs/helmet#91]
Hi guys, I found these [excellent slides](https://speakerdeck.com/ckarande/top-overlooked-security-threats-to-node-dot-js-web-applications?slide=48) which pointed me to helmet. Your toolbelt helped me a lot! However, I didn't find a solution to defend against HTTP Parameter Pollution Attacks (see slides 48 to 61) so I wrote the library [HPP](https://www.npmjs.com/package/hpp).

I think HPP would be a perfect addition to Helmet. What do you think?

**Comment by EvanHahn** [comment]
I've always found Express's querystring handling to be poorly designed. I will almost certainly add HPP to my upcoming Express book—I've been looking for _exactly_ that library.

I'm not sure if HPP fits in the scope of this library. On one hand, Helmet is "a series of middleware that help secure your Express/Connect apps". On the other hand, it mostly handles HTTP headers (with the exception of [crossdomain](https://github.com/helmetjs/crossdomain)) and we decided [some things are out of the library's scope](https://github.com/helmetjs/helmet/issues/79#issuecomment-72681468).

What do people think?

In any case, I've added HPP to the "recommended modules" list.

**Comment by analog-nico** [comment]
Thanks for recommending HPP!

Although it is also a no-brainer single-line middleware (`app.use(hpp())`) I think one aspect is important: You have to add HPP after the body parser middleware. Currently, all Helmet middlewares can be added anywhere.

Anyway, the more I read about Helmet the more I understand its focus. Let's leave it at the recommendation.
