### ISSUE TITLE
frameguard do not allow file upload

### ISSUE THREAD

**Issue by Torone** [helmetjs/helmet#93]
Hi, I don't really know if it is an issue or not, it is the first time I use Helmet.

I have a MEAN stack application and it allow my users to upload images within their folder. The folder is created by the server once the user upload the first image.

In my configuration I have: `app.use(helmet.frameguard('deny'));` and I also tried all the various alternatives but it seems to block the creation of the folder and the image upload...

Commenting out that row the app works fine.

I think it is very important to keep `app.use(helmet.frameguard('deny'));` enabled but how can I let my server to create folders and my users to upload files within it if I have it enabled?

Thanks

**Comment by EvanHahn** [comment]
Does this give any errors, or does it silently fail?

**Comment by Torone** [comment]
Unfortunately it silently fail just redirecting me to the `/report-violation` url.

It happen only if the image exceed the nginx `client_max_body_size` but I was expecting a different error in this case. Commenting out the frameguard I correctly receive the server error of the max file size.

It is just a weird behaviour because it should not block the upload, it should block something not related with it.

I will try to test it again to see where is the relation between the frameguard and the file uploads and if I will found something I will report it to you.

Thanks

**Comment by EvanHahn** [comment]
Are you using any other Helmet middleware? And where does the `/report-violation` URL come from?

**Comment by EvanHahn** [comment]
@Torone Any updates?

**Comment by Torone** [comment]
Not yet sorry, I just commented it out at the moment and I'm going ahead with the project.

**Comment by EvanHahn** [comment]
Okay. Do you mind if I close this issue?

**Comment by Torone** [comment]
Sure, thanks.
