### ISSUE TITLE
Feature: Validate payload's content length

### ISSUE THREAD

**Issue by ericmdantas** [helmetjs/helmet#94]
Hi!

First of all, nice module.

I'd like to know if it's interesting enough to have a middleware for validations for the content length of a given payload, be it a POST or a PUT.

I have written a middleware to do so [(express-content-length-validator)](https://github.com/ericmdantas/express-content-length-validator), so if you're interested we could merge it to helmet.

**Comment by EvanHahn** [comment]
This isn't well-communicated (and is something we need to fix, see #92), but Helmet is only for setting security-related HTTP headers. Your library is good but is out of this library's scope.

I've added it to the "other recommended modules" section of the readme (in commit 690787415882dfa31a8e191e153740e561261e3e). Thanks!

**Comment by ericmdantas** [comment]
Thanks!
