### ISSUE TITLE
Investigate removing Connect dependency

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#97]
To quote my comment in #95:

> As far as Connect goes, we don't need it. We just need something that can "concatenate" a bunch of middlewares together. We could likely use something like [Async's `compose`](https://github.com/caolan/async#compose) or something similar.

We should investigate what it'd take to remove Connect.

**Comment by EvanHahn** [comment]
Does anyone care about this? Personally, I don't think this is a big issue. (cc @trygve-lie @hdf)

**Comment by MarkHerhold** [comment]
I honestly couldn't care about the use of the Connect dependency. Connect is well tested and works, which is the best you can ask for.

What I really do care about though it the ability to use helmet in Koa (same as @KevinMartin mentioned in #92). I honestly have no idea if Connect helps or hurts that goal though. Just my 2 cents.

**Comment by EvanHahn** [comment]
@MarkHerhold Added #100 about the Koa issue.

I tend to agree—honestly, Connect is probably more reliable than something I would write.

**Comment by dcousens** [comment]
@EvanHahn I don't think dropping `connect` is a good solution,  as it is probably already quite generic given its use case.

However,  in light of #100,  you could probably just make a wrapper module? `helmet-koa`?
How different is `koa`?  I thought it was just `connect`-like but with promises instead of callbacks.

**Comment by EvanHahn** [comment]
@dcousens Let's bring the Koa discussion to #100.

Closing this issue—seems like we're fine with the Connect dependency.
