### ISSUE TITLE
Deprecate crossdomain

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#98]

**Comment by EvanHahn** [comment]
Done. The majority of the work was done in bf65c0f479d673651213aa751b5234123ae95efe but there were a few other commits too.

**Comment by VynceMontgomery** [comment]
is there any explanation of why this change or what replaces it?  I see that there's a separate helmet-crossdomain package on npm ( https://www.npmjs.com/package/helmet-crossdomain ), but it's not clear if that is *also* deprecated, or the replacement for this, or what. Can you clarify?

/

**Comment by EvanHahn** [comment]
Helmet is for HTTP headers only, and `crossdomain.xml` doesn't fall under that blanket. The `crossdomain` package will continued to be maintained but won't be included in Helmet 1.0.0.

**Comment by VynceMontgomery** [comment]
when you say "the corssdomain package" do you mean the one called "helmet-crossdomain"? or are you changing the name to reflect the fact that it's not part of helmet anymore?

**Comment by EvanHahn** [comment]
Ah, sorry for the confusion.

1. `helmet.crossdomain` won't be present in version `1.0.0`.
1. We will continue to maintain the `helmet-crossdomain` package ([this one](https://github.com/helmetjs/crossdomain)), even though it won't be included in "core" Helmet.
1. We will [consider renaming the package](https://github.com/helmetjs/crossdomain/issues/4).

Does that clear things up?

**Comment by VynceMontgomery** [comment]
I suppose so. limiting helmet to things that are done with headers seems a little arbitrary, but at least what is happening is now clear.

**Comment by EvanHahn** [comment]
A lot of smart people were sending pull requests for [various Express-compatible security modules](https://github.com/helmetjs/helmet#other-recommended-modules). They were great, but I didn't want the scope of the project to grow too much. That's why I decided to stick to HTTP headers.
